### ISSUE TITLE
Redact reason: clarify things

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#1003]
Status:
- Users do not want to leak their locale. This is why we have done #977 

But:
- It seems a bit useless to ask for a reason when user want to delete his own message
- It can be useful for moderation purpose, when deleting other users' messages.

So:
- Do not display the check box and the edit text of the confirmation dialog (see screenshot in #977) when user wants to delete its own messages.
- We will use the full dialog when RiotX will support moderation/admin actions, so keep the code in place.
- When redacting a message, do not provide a reason
- Remove the default reason set in the layout
- We display a 'redacted message' notice when this message is previewed (ex: in the Message bottom sheet or in the room list, as last event of the room) if:

1. the userId of the redaction is the same that the userId of the original message and a reason **is not** provided: use 'R.string.event_redacted_by_user_reason' ("Event deleted by user")
2. the userId of the redaction is the same that the userId of the original message and a reason **is** provided: use the new string 'R.string.event_redacted_by_user_reason_with_reason' ("Event deleted by user, reason: %1$s")
3. the userId of the redaction **is not** the same that the userId of the original message and a reason **is not** provided: use 'R.string.event_redacted_by_admin_reason' ("Event moderated by room admin")
4. the userId of the redaction **is not** the same that the userId of the original message and a reason **is** provided: use the new string 'R.string.event_redacted_by_admin_reason_with_reason' ("Event moderated by room admin, reason: %1$s")

**Comment by BillCarsonFr** [comment]
LGTM
I'll wheck with nad if we really need a confirmation popup when deleting our own messages, but for now let's stay consistent with web

**Comment by bmarty** [comment]
(FTR https://github.com/vector-im/riotX-android/issues/967) I think we definitely need a confirmation dialog before deleting a message. Riot-Web has one
