### ISSUE TITLE
After jump to unread, newer messages are never loaded

### ISSUE THREAD

**Issue by justdave** [vector-im/riotX-android#1008]
When hitting the "jump to unread messages" banner and there are lots of them, it fails to load messages when you scroll down. I have to switch to a different channel and switch back and then manually scroll back to find where I left off in order to see the stuff in between.
I've had that happen to me 2 or 3 times the last couple days
It just sits and spins like in the screenshot forever
<img alt="Screenshot_20200213-131533_RiotX" src="https://user-images.githubusercontent.com/307334/74471171-c31bc400-4e6d-11ea-9a97-a86e30006961.jpg" width="200">

**Comment by bmarty** [comment]
I can reproduce the issue sometimes. #791 has reduce the number of occurrence, but it's not fixed yet.
