### ISSUE TITLE
otherMemberIds is empty for rooms the user is invited to

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#1013]
@david1hyman is reporting that RoomSummary.otherMemberIds is empty for rooms the user is invited to.

It was working as expected in 0.12.0 and is broken since (at least) 0.15.0

So should be a regression after recent rework on this part.

Note that I have not tested myself, but the bug may be there

**Comment by david1hyman** [comment]
Additional context:
We are using only the SDK layer of RiotX. 
When observing room summaries we filter the incoming array to remove rooms where RoomSummary.otherMemberIds.isEmpty(). 
After that filtering we look for rooms where RoomSummary.membership == INVITE and accept those invites automatically. 
After updating from 0.12.0 to 0.15.0, RoomSummary.otherMemberIds.isEmpty() was always true for rooms where RoomSummary.membership == INVITE. Therefore, we could never accept the invite and things were haywire downstream.
We were able to work around by accepting invites before the RoomSummary.otherMemberIds.isEmpty() filtering.

**Comment by bmarty** [comment]
Bug confirmed. Due to https://github.com/vector-im/riotX-android/blob/3189c114dc79601b4477204a53582f5bff43f345/matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/sync/RoomSyncHandler.kt#L227

Event for invited rooms are not full Event, they do not contain `eventId`. We should parse them as `StrippedState` (see https://matrix.org/docs/spec/client_server/latest). So the model has to be updated, to properly fix the issue

**Comment by bmarty** [comment]
Should be fixed by #1049
