### ISSUE TITLE
New direct chat: selecting a participant sometimes results in two breadcrumbs

### ISSUE THREAD

**Issue by steef435** [vector-im/riotX-android#1022]
This only happens about 2/3 of the times on my device.

Steps to reproduce:
1. Click on the new direct chat fab
2. Click on a username

What I expect: one breadcrumb containing the username appears

What happens: two breadcrumbs containing the username appear. One can be removed by clicking on the cross, after which it the create room button disappears (probably because no usernames are selected) but the other breadcrumb remains and cannot be removed (nothing happens when clicking it). On the debug version of the attachment process branch, clicking to remove the second breadcrumb crashes the app as well. (freezes up entirely, so can't rageshake, if this turns out hard to reproduce I can search for some logs)

**Comment by bmarty** [comment]
Thanks for the feedback. Probably a regression after rework on ViewEvents
