### ISSUE TITLE
Prevent screenshots

### ISSUE THREAD

**Issue by 35609902357** [vector-im/riotX-android#1027]
Screenshots of the app can be taken and its content is not hidden in recent apps preview, this poses a huge security risk and protection should be mandatory or at least optional but enabled by default. Please add Android's `FLAG_SECURE` and enable it by default.

**Comment by vurpo** [comment]
I don't know if this would be useful or wanted by most. What kind of security risk does it pose that screenshots can be taken of the app? You're still not preventing anyone from copying messages or other information out of the app.

**Comment by tulir** [comment]
There's no security risk, please do not add pointless security theater like this. You can't protect the messages against the intended recipient.

**Comment by bmarty** [comment]
It's worth noting that it could prevent other (evil) apps from taking screenshots too.

**Comment by bmarty** [comment]
Ok, I've done a quick 5 minutes impl in #1091.
The setting is disabled by default.

**Comment by vurpo** [comment]
Evil apps aren't able to record the screen/take screenshots without given permission anyway. Having this setting enabled would provide basically no protection while significantly reducing the usability of the app.

**Comment by bmarty** [comment]
Yes, I globally agree with you. If user enables the setting it's their choice. Also we are not always sure that we can trust the system, or even trust that our code has no security issue. Else why using an encrypted database to cache data, already saved to the application private storage area?
