### ISSUE TITLE
Whitespace at the end of the password is not removed

### ISSUE THREAD

**Issue by telmich** [vector-im/riotX-android#1038]
If you paste the backup key password into riotx and there is a space at the end, it will be kept. As c&p from other apps might cause this, this causes unexpected user experience.

Tested on 0.16.0

**Comment by bmarty** [comment]
Space is a valid character for passwords in lmatrix world, and we cannot take the responsibility to trim what user is entering, else, some users will be stucked

**Comment by telmich** [comment]
What if you add the following logic to riotx:

* try logging in with whitespace at beginning and end not trimmed
* if that fails: try logging in with whitespace at beginning and end trimmed

This way there is no surprise for users who copied & pasted their password and neither for the (I assume very rare) cases when someone has a leading or ending whitespace.

**Comment by bmarty** [comment]
Password field has a reveal button (an eye), user can see the password in clear and detect a possible mistake with spaces.
I'm not sure it's a good idea to try several trimmed password, but why not...
We could also add a warning under the password field if a space is detected at beginning or end of password, the same way computer warn if the CAPS lock is on when entering password.

**Comment by telmich** [comment]
If you want to be very explicit, maybe the last variant is the best, notifying the user of something that might possible go wrong.

**Comment by bpcurse** [comment]
> I'm not sure it's a good idea to try several trimmed password, but why not...

True, it could trigger security mechanisms in very sensitive setups

**Comment by JavaZauber** [comment]
Removing whitespaces is mentioned in the NIST password guideline although it does not mention that whitespaces might be completely omitted.
Speciically it allows >=2 Whitespaces to be downsized to one single whitespace

### [NIST Special Publication 800-63B, Digital Identity Guidelines: Authentication and Lifecycle Management](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf)

> **5.1.1.2   Memorized Secret Verifiers**
> Verifiers SHALL require subscriber-chosen memorized secrets to be at least 8 characters in length. Verifiers SHOULD permit subscriber-chosen memorized secrets at least 64 characters in length. All printing ASCII characters as well as the space character SHOULD be acceptable in memorized secrets. Unicode characters SHOULD be accepted as well. To make allowances for likely mistyping, verifiers MAY replace multiple consecutive space characters with a single space character prior to verification, provided that the result is at least 8 characters in length. Truncation of the secret SHALL NOT be performed. For purposes of the above length requirements, each Unicode code point SHALL be counted as a single character.

With focus
