### ISSUE TITLE
Leaving a room creates a stuck "leaving room" loading screen.

### ISSUE THREAD

**Issue by Flam3z** [vector-im/riotX-android#1041]
Each time I leave a room it stays on "leaving room" until i restart the app. 

Mobile Info: Samsung S10 [Android 10]
Version info: 0.16.0

**Comment by bmarty** [comment]
It takes times for the sync to come back with the left room.
We should not wait locally for this information though

**Comment by bmarty** [comment]
ok, there is a bug, I fix it right now
