### ISSUE TITLE
Update user avatar

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#1054]
Not implemented yet… :)

**Comment by bmarty** [comment]
I assume this issue refer to user avatar.
FTR room avatar is tracked by #859

**Comment by fbruetting** [comment]
Yes, I found no already existent issue for that (and thought that with you currently working on the image editing stuff, this might be low-hanging fruit).

**Comment by Kiwimaster** [comment]
yip....not being able to set the avatar is a major problem for us.
Any idea on when this feature will be added?
