### ISSUE TITLE
add by matrix id not working

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#1065]
Steps to reproduce:

1. go to direct message tab
2. Hit the + new message bubble FAB
3. tap Add by matrix ID
4. type a matrix id, i.e.@cadair:cadair.com
5. Only get an empty 'no results' list with no way to proceed.

**Comment by Bubu** [comment]
Related: #499

**Comment by bmarty** [comment]
Yes, we should add an entry in the result list to add the entered matrixId

**Comment by bahur142** [comment]
Currently this is the main reason that stopping me to give RiotX to friends. Adding new DM contacts with RiotX is impossible.
Thank you all for the great work! RiotX is great chat client.
