### ISSUE TITLE
CreateRoomParams.initialStates not working

### ISSUE THREAD

**Issue by david1hyman** [vector-im/riotX-android#1070]
`CreateRoomParams.enableEncryptionWithAlgorithm`
and
`CreateRoomParams.setHistoryVisibility`
both write to the the initialStates variable using a copy block like this:
`copy(
                    initialStates = initialStates.orEmpty().filter { it.type != EventType.STATE_ROOM_ENCRYPTION } + algoEvent
            )`
Whatever this is trying to do the end result is that `initialStates` is always null. There's some Kotlin secret sauce with `copy()` that I've never used. It appears to fail to do whatever is intended.

I've fixed this by changing `initialStates` to a variable but that's against the spirit of what's being attempted here.

**Comment by bmarty** [comment]
As discussed together, the mistake is that you do not use the returned value of both methods
The contract is unclear, the doc is not up to date. I will improve this
