### ISSUE TITLE
riotX uploads media attachments using the invalid image/jpg MIME type

### ISSUE THREAD

**Issue by chr-1x** [vector-im/riotX-android#1075]
`image/jpg` is not a valid MIME type: the registered MIME type for jpeg images is `image/jpeg`: https://www.w3.org/Graphics/JPEG/

While I'm sure that most programs are robust to this difference (it's a common enough error that there's [a highly rated StackOverflow post about it](https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg)), Synapse is not. Images uploaded to synapse using riotX with the invalid `image/jpg` MIME type fail to have thumbnails generated for them (filed as https://github.com/matrix-org/synapse/issues/6993).

riotX should follow standards and submit JPEG images using the `image/jpeg` MIME type, even if the file extension is `.jpg`.

**Comment by chr-1x** [comment]
I believe the simplest solution is to have the `Resource` class in https://github.com/vector-im/riotX-android/blob/develop/vector/src/main/java/im/vector/riotx/core/resources/ResourceUtils.kt normalize the MIME type. I'll try to develop a fix and submit it this weekend.

**Comment by bmarty** [comment]
Ok, cool, thanks
