### ISSUE TITLE
Composer decoration: shields 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#1077]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/9841565/75336500-8e573600-588b-11ea-951b-4cfba692bb1a.png">

**Comment by bmarty** [comment]
Maybe take the opportunity to iterate on the hint too... They are too long (so displayed on 2 lines on small device, which is very ugly), and not correct from UX point of view.

I propose to use "Type message" and "Type secret message"

**Comment by bahur142** [comment]
Or secure instead secret.

**Comment by steef435** [comment]
Will the shields disappear once the user starts typing? Otherwise I fear it would be a little bit of wasted message space in 90% of the cases, because we can already see the security in the top bar and in the hint text. Maybe the same effect would be achieved by putting the shield on top of the send message button like with the avatars? Or maybe remove the avatar of the sender and put the shield there?

**Comment by barudaret** [comment]
Maybe you could locally/temporarily toggle encryption by tapping it, so you could send a quick plaintext message in an otherwise encrypted room.

**Comment by BillCarsonFr** [comment]
> Maybe take the opportunity to iterate on the hint too... They are too long (so displayed on 2 lines on small device, which is very ugly), and not correct from UX point of view.
> 
> I propose to use "Type message" and "Type secret message"

As per discussion with nad, we will just put 'message' now

**Comment by BillCarsonFr** [comment]
> Will the shields disappear once the user starts typing? Otherwise I fear it would be a little bit of wasted message space in 90% of the cases, because we can already see the security in the top bar and in the hint text. Maybe the same effect would be achieved by putting the shield on top of the send message button like with the avatars? Or maybe remove the avatar of the sender and put the shield there?

Yes this is web design, will be adapted for mobile constraints
