### ISSUE TITLE
v0.18 : pictures are not sent and it can not be canceled

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riotX-android#1092]
I updated RiotXdev to v0.18 to try the resized sending picture and it first did work.
However, one of the picture didn't send and stay on waiting. I tried to send other pictures and they all are "waiting".
I can't cancel it and now no pictures are being sent.
What to do?

**Comment by Thatoo** [comment]
solved going to settings -> advanced -> developer mode and then clear the queue.

**Comment by Destroyer** [comment]
Hi, how did you clear the queue? You mean the cache or something else?
