### ISSUE TITLE
logout doesn't reset theme

### ISSUE THREAD

**Issue by ZerataX** [vector-im/riotX-android#1097]
which results in the login screen looking rather weird
![Screenshot_2020-03-03-03-38-48-077_im vector riotx](https://user-images.githubusercontent.com/5024958/75738889-c2a37a00-5d03-11ea-8015-58de4dbead58.jpg)

**Comment by bmarty** [comment]
It's [expected](https://github.com/vector-im/riotX-android/blob/1276d1f39d0576febec0781322e00d9b6bea539d/vector/src/main/java/im/vector/riotx/features/settings/VectorPreferences.kt#L229) that logout does not reset the theme.

Thanks for creating the issue for login screen. We've already heard of it, but did not fix it yet, as it's not p1.

**Comment by bmarty** [comment]
@nadonomy could you please propose an dark theme alternative in Figma for this screen please?
