### ISSUE TITLE
Reactions: Emoji picker

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#110]
@manuroe commented on [Tue Apr 16 2019](https://github.com/vector-im/riot-android/issues/3119)

Create a classic fullscreen emoji picker. 

Requirements are:
 - list native emoji (custom emoji will be managed later)
 - group them by category
 -  search

We could use the same dataset as riot-web: https://github.com/missive/emoji-mart/tree/master/data

**Comment by bmarty** [comment]
The current emoji picker can be improved, we will open dedicated issue if needed later on
