### ISSUE TITLE
crash after upgrading to 0.17.0

### ISSUE THREAD

**Issue by foresto** [vector-im/riotX-android#1108]
After upgrading from 0.13.0-dev to 0.17.0, RiotX crashes immediately upon launch.

This is an android 5.1.1 (LineageOS 12.1) device.

logcat at crash time:

    D/GmsGcmRegisterSvc(20885): onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
    E/FirebaseInstanceId(21502): Token retrieval failed: SERVICE_NOT_AVAILABLE
    I/Timeline(20969): Timeline: Activity_launch_request id:im.vector.riotx time:190762160
    I/ActivityManager(20152): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=im.vector.riotx/.features.Alias bnds=[360,853][508,1020] (has extras)} from uid 10018 on display 0
    V/WindowManager(20152): addAppToken: AppWindowToken{2411db88 token=Token{31511b2b ActivityRecord{17ad77a u0 im.vector.riotx/.features.Alias t9651}}} to stack=1 task=9651 at 0
    V/WindowManager(20152): Adding window Window{85bc4a3 u0 Starting im.vector.riotx} at 2 of 6 (after Window{dad82c u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher})
    I/ActivityManager(20152): Start proc 22386:im.vector.riotx/u0a65 for activity im.vector.riotx/.features.Alias
    V/WindowManager(20152): rotationForOrientationLw(orient=-1, last=0); user=0 
    I/MultiDex(22386): VM with version 2.1.0 has multidex support
    I/MultiDex(22386): Installing application
    I/MultiDex(22386): VM has multidex support, MultiDex support library is disabled.
    W/keystore( 1751): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    W/keystore( 1751): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    W/keystore( 1751): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    W/keystore( 1751): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    W/keystore( 1751): Could not read CACERT_matrix-sdk-auth
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    W/linker  (22386): libolm.so: unused DT entry: type 0x6ffffffe arg 0x69a4
    W/linker  (22386): libolm.so: unused DT entry: type 0x6fffffff arg 0x2
    I/art     (22386): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.platform.ConscryptPlatform$configureTrustManager$1>
    I/art     (22386): Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.platform.ConscryptPlatform$configureTrustManager$1>
    E/SQLiteLog(22386): (283) recovered 98 frames from WAL file /data/data/im.vector.riotx/databases/androidx.work.workdb-wal
    W/keystore( 1751): Could not read CACERT_session_db_2a8329155df60af39b9c3a37296aeaf8
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    I/art     (22386): Background sticky concurrent mark sweep GC freed 69306(4MB) AllocSpace objects, 8(128KB) LOS objects, 19% free, 17MB/21MB, paused 5.365ms total 63.305ms
    W/keystore( 1751): Could not read CACERT_crypto_module_2a8329155df60af39b9c3a37296aeaf8
    E/QCOMKeyMaster( 1751): ION allocation  failed
    W/keystore( 1751): device couldn't sign data
    W/OpenSSL-keystore-rsa(22386): No valid signature returned
    W/REALM_JNI(22386): Java exception has been occurred. Terminate JNI by throwing a c++ exception.
    W/REALM_JNI(22386): (/Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsRealmConfig.cpp:163)
    W/REALM_JNI(22386): There is a pending Java exception.
    D/AndroidRuntime(22386): Shutting down VM
    E/AndroidRuntime(22386): FATAL EXCEPTION: main
    E/AndroidRuntime(22386): Process: im.vector.riotx, PID: 22386
    E/AndroidRuntime(22386): java.lang.RuntimeException: Unable to create application im.vector.riotx.VectorApplication: java.io.InvalidClassException: im.vector.matrix.android.internal.crypto.model.MXDeviceInfo; Incompatible class (SUID): im.vector.matrix.android.internal.crypto.model.MXDeviceInfo: static final long serialVersionUID =-9102964973591845542L; but expected im.vector.matrix.android.internal.crypto.model.MXDeviceInfo: static final long serialVersionUID =5399830165027485869L;
    E/AndroidRuntime(22386): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4596)
    E/AndroidRuntime(22386): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
    E/AndroidRuntime(22386): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
    E/AndroidRuntime(22386): 	at android.os.Handler.dispatchMessage(Handler.java:102)
    E/AndroidRuntime(22386): 	at android.os.Looper.loop(Looper.java:135)
    E/AndroidRuntime(22386): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
    E/AndroidRuntime(22386): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(22386): 	at java.lang.reflect.Method.invoke(Method.java:372)
    E/AndroidRuntime(22386): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    E/AndroidRuntime(22386): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    E/AndroidRuntime(22386): Caused by: java.io.InvalidClassException: im.vector.matrix.android.internal.crypto.model.MXDeviceInfo; Incompatible class (SUID): im.vector.matrix.android.internal.crypto.model.MXDeviceInfo: static final long serialVersionUID =-9102964973591845542L; but expected im.vector.matrix.android.internal.crypto.model.MXDeviceInfo: static final long serialVersionUID =5399830165027485869L;
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.verifyAndInit(ObjectInputStream.java:2341)
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.readNewClassDesc(ObjectInputStream.java:1643)
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:657)
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1782)
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
    E/AndroidRuntime(22386): 	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.store.db.HelperKt.deserializeFromRealm(Helper.kt:99)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration$migrate$1.apply(RealmCryptoStoreMigration.kt:99)
    E/AndroidRuntime(22386): 	at io.realm.MutableRealmObjectSchema.transform(MutableRealmObjectSchema.java:299)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStoreMigration.migrate(RealmCryptoStoreMigration.kt:96)
    E/AndroidRuntime(22386): 	at io.realm.BaseRealm$6.onMigrationNeeded(BaseRealm.java:782)
    E/AndroidRuntime(22386): 	at io.realm.internal.OsSharedRealm.runMigrationCallback(OsSharedRealm.java:533)
    E/AndroidRuntime(22386): 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
    E/AndroidRuntime(22386): 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
    E/AndroidRuntime(22386): 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
    E/AndroidRuntime(22386): 	at io.realm.BaseRealm.<init>(BaseRealm.java:136)
    E/AndroidRuntime(22386): 	at io.realm.BaseRealm.<init>(BaseRealm.java:103)
    E/AndroidRuntime(22386): 	at io.realm.Realm.<init>(Realm.java:163)
    E/AndroidRuntime(22386): 	at io.realm.Realm.createInstance(Realm.java:499)
    E/AndroidRuntime(22386): 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:360)
    E/AndroidRuntime(22386): 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
    E/AndroidRuntime(22386): 	at io.realm.Realm.getInstance(Realm.java:428)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.store.db.HelperKt.doRealmQueryAndCopy(Helper.kt:43)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.store.db.RealmCryptoStore.getAccount(RealmCryptoStore.kt:204)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.MXOlmDevice.<init>(MXOlmDevice.kt:89)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.newInstance(MXOlmDevice_Factory.java:29)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:21)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.MXOlmDevice_Factory.get(MXOlmDevice_Factory.java:8)
    E/AndroidRuntime(22386): 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factory.get(DefaultCryptoService_Factory.java:164)
    E/AndroidRuntime(22386): 	at im.vector.matrix.android.internal.crypto.DefaultCryptoService_Factor
    W/ActivityManager(20152):   Force finishing activity 1 im.vector.riotx/.features.Alias

Unfortunately, attempts to downgrade to an earlier version fail. F-Droid says, "failed to install due to an unknown error."

**Comment by dvalter** [comment]
Same issue on Android 8.1 after F-Droid upgrade from 0.14.3

**Comment by jtrees** [comment]
I'm also experiencing this.

**Comment by SergeyDjam** [comment]
me to. Asus ZenFone, Android 9, RiotX 1.7.0 f-droid. Crashed on the start

**Comment by bmarty** [comment]
Sorry, you will have to clear data to fix the crash.

**Comment by jtrees** [comment]
Ok, that worked. Is there a way to decrypt old messages again?
