### ISSUE TITLE
pinch to zoom in e2ee rooms

### ISSUE THREAD

**Issue by lub** [vector-im/riotX-android#1123]
It seems zooming only works in non-encrypted rooms. I've sent a rage shake.

**Comment by duncanturk** [comment]
Maybe this one should be tagged with `riotx-go-live` since it makes people using unencrypted over encrypted rooms.

**Comment by horstvogel** [comment]
in the meantime Riotx is out in beta 0-91-1, with Riot rooms are now encrypted by default, so you can no longer zoom pictures now, very unfortunate. Has the problem been tackled at all?
