### ISSUE TITLE
Server too old?

### ISSUE THREAD

**Issue by meaz** [vector-im/riotX-android#1161]
HI,

I've installed riotx to test it. But I can't, I have a message saying that the server is too old. What is then the minimum version needed for the server?
![riotx](https://user-images.githubusercontent.com/13604424/77244606-f1cc4d80-6c16-11ea-940a-9cd57516bdae.jpg)

**Comment by BillCarsonFr** [comment]
r0.5.0
or should have the m.lazy_load_members flag
