### ISSUE TITLE
Crypto | RiotX sometimes rotate the current device keys

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#1170]
#See https://github.com/vector-im/riot-web/issues/12681#issuecomment-598285014

Looks like riotX uploaded new keys for the current device:
```
"keys":{"curve25519:NSMNEBBVCL":"QS56HSc9wOuu61ZZ2rX9YmdtMG9T370JxniiFIdozh8","ed25519:NSMNEBBVCL":"4hnnOjs/y6PAEELmJ+A+q6JKvzCh5t0bsL7m2NyyOpA"}

"keys":{"curve25519:NSMNEBBVCL":"ULIgCdMs6/06Eb6w2dSCh3I8hoTMpqHZ8nGKppvT7j0","ed25519:NSMNEBBVCL":"BQgEflTOV7SoQFxNFkI5r2o7ITsTY4g5ciYkwpKtPtU"}

```

**Comment by ara4n** [comment]
May be related to the fact i had to keep hammering the login button to actually get in? https://github.com/vector-im/riotX-android/issues/1164
