### ISSUE TITLE
Duplicate outgoing messages

### ISSUE THREAD

**Issue by mordae** [vector-im/riotX-android#1171]
Sometimes messages are sent twice, sometimes with a significant delay.

1. Message is sent and another copy of it is sent in a couple of minutes afterwards.
2. Message is sent and another copy of it is sent a day afterwards, probably as the user opens the application on their phone to read some other messages.

If the message is sent to an encrypted room, the second message is identical, resulting in the following warning in the web client: "Unable to decrypt: Error: Duplicate message index, possible replay attack:"

This is all on the matrix.org instance.

**Comment by BillCarsonFr** [comment]
Hello,

This is due to matrix.org beeing currently overloaded
https://github.com/matrix-org/synapse/issues/3365
