### ISSUE TITLE
Video calling support

### ISSUE THREAD

**Issue by rajil** [vector-im/riotX-android#1208]
Hello,

I was wondering what is the plan for video calling support. Will it be same as Riot.IM with direct P2P and conference through Jitsi?

If the conferencing will be through Jitsi, I hope there will an option to use self hosted Jitsi server rather than a hardcoded server,.

Thanks

**Comment by tulir** [comment]
Duplicate of #611

**Comment by almereyda** [comment]
And also a duplicate of #43, to cover both video calling cases.
