### ISSUE TITLE
be able to Favorite a room as a long hold option

### ISSUE THREAD

**Issue by raedah** [vector-im/riotX-android#1217]
Riot web supports marking rooms as 'favorites' which pins them at the top of the list. RiotX shows my favorited conversations, but doesnt let me tag rooms as favorites or remove them from favorites. I would expect this to be a property of the room that is viewable on the long hold options.

Also just noticed the Low Priority option as well, which would be another case of the same, needing to add it or remove it as a property of the room in the users room list. On mobile would likely be with a long hold.

**Comment by bmarty** [comment]
Favorite a room is now possible since RiotX v0.22.0

I do not know how we will handle low priority room, this is tracked by #1490
