### ISSUE TITLE
RiotX fetches nonexistent URL /_matrix/media/v1/...

### ISSUE THREAD

**Issue by auscompgeek** [vector-im/riotX-android#1227]
https://github.com/vector-im/riotX-android/blob/1e11d4492b8255d053facfe7cf6075f74371dde4/matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/content/DefaultContentUrlResolver.kt#L24

Shouldn't this use `NetworkConstants.URI_API_MEDIA_PREFIX_PATH_R0`?

**Comment by bmarty** [comment]
Yes, maybe, I'm not sure. I'm checking internally.

NetworkConstants.URI_API_MEDIA_PREFIX_PATH_R0 is defined to "_matrix/media/r0/"

**Comment by bmarty** [comment]
Ok, you're right, it should be the `r0` path. I will do the change
