### ISSUE TITLE
Message Editing: Display edits as diffs

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#123]
From riot-web created by [jryans](https://github.com/jryans): vector-im/riot-web#9493  

We'd like to display [edit history](#121) as a diff to make it obvious what was added / removed / changed.

However, we should only do this if we can be absolutely certain that we know the immediate predecessor of an edit without gaps, etc.

<img width="256" alt="Screenshot 2019-04-30 at 14 10 57" src="https://user-images.githubusercontent.com/8418515/56960642-cdc0d300-6b51-11e9-8870-a2fef352aed8.png">

**Comment by bmarty** [comment]
@BillCarsonFr I think we can close this one now?

**Comment by bmarty** [comment]
Who is silent consents :)
