### ISSUE TITLE
No notification for cross signing a new device

### ISSUE THREAD

**Issue by MatMaul** [vector-im/riotX-android#1249]
When logging a new device with riot-web, I get no notification for validation of the device through cross-signing in RiotX. The notification shows up fine in another riot-web.
I am not talking Android notif here but the internal "header" notif for verification that you get when you do the reverse (sign in a new RiotX device).

**Comment by ara4n** [comment]
@BillCarsonFr i'm also hearing reports anecdotally of this from others

**Comment by MatMaul** [comment]
FYI I just updated to last develop build for both riot-web and RiotX, and updated synapse to 1.12.4 : still the same, nothing shows up in my RiotX. No problem to validate with another riot-web.

**Comment by MatMaul** [comment]
Fixed in develop ! Thanks.
