### ISSUE TITLE
Display full public key in Security & Privacy

### ISSUE THREAD

**Issue by raedah** [vector-im/riotX-android#1253]
Short identifer is shown for the session, but some people verify with the full public key. There is currently no way to show this in the app.

**Comment by BillCarsonFr** [comment]
We should match web 

On manually verify the current session should cross sign the device and upload signature

![image](https://user-images.githubusercontent.com/9841565/80369050-f0cdb200-888d-11ea-8aab-889800ce4e27.png)

![image](https://user-images.githubusercontent.com/9841565/80369058-f3300c00-888d-11ea-817e-c2f1d0db1a40.png)

**Comment by BillCarsonFr** [comment]
Fixed in https://github.com/vector-im/riotX-android/pull/1296
