### ISSUE TITLE
Invite member(s) to an existing room

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#1276]
Currently it's only possible with /invite command.

The UI/UX when adding members during DM creation could be reused, with just modifying the title of the screens. Also the current members of the room has to be filtered out.

It's not possible to invite by email for the moment, only by userIds.

The entry point has to be validated by @nadonomy : For the moment, we can add a simple FloatingActionButton on the room detail members list.

Displaying the list of invited members is already implemented.

**Comment by nadonomy** [comment]
I think for sure as part of the user list via room profiles, will amend Figma to include next week.

**Comment by benedikrok** [comment]
Link to the design document: https://www.figma.com/file/yHjHSAOTYzEszOiZN5U9tx/Invite-Members?node-id=30%3A971&viewport=-5365%2C-3340%2C1
