### ISSUE TITLE
Message Editing: Update notifications

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#128]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2410  

We should update notifications with updated messages

**Comment by manuroe** [comment]
Moved to phase:3 as there is no notifications in RiotX currently.

**Comment by manuroe** [comment]
Moved to phase:4 as per this [comment](https://github.com/vector-im/riot-ios/issues/2410#issuecomment-508432786)

**Comment by bmarty** [comment]
This remaining issue of `Reactions & Message Editing` is moved to `Stabilization1` to be handled
