### ISSUE TITLE
recent nightlies keep crashing

### ISSUE THREAD

**Issue by lub** [vector-im/riotX-android#1283]
shortly after opening it

2465 and 2466 are both crashing for me. I can't downgrade to older buolds to test it further.

it seems other users also have problems:
https://matrix.to/#/!gGkYcJLTzcNrfERksd:matrix.org/$8ToUA06h3c_Tya_gFdejOI-yEk81Lgk66jnzUOJTluM

**Comment by BillCarsonFr** [comment]
Yes we did a bad database migration at somepoint. You'll have to uninstall and re-install again (or clear app storage). sorry for inconvenience
