### ISSUE TITLE
e2ee shields display wrong colour if room history has other users

### ISSUE THREAD

**Issue by Cadair** [vector-im/riotX-android#1284]
I have a DM which at somepoint in the past had 3 accounts in it (the other person changed servers), we have now done the xsign dance and on riot-web it shows as a green shield. On RioX it shows as a black shield. All other rooms behave as expected.

I assume it's because the history of the room had a third account, but I assume RiotX should ignore this when working out the shield colour?

**Comment by BillCarsonFr** [comment]
In the room members list what do you see?

**Comment by Cadair** [comment]
Two members listed under "admins" with both showing green ticks.

**Comment by BillCarsonFr** [comment]
fixed in https://github.com/vector-im/riotX-android/pull/1297
