### ISSUE TITLE
Emoji completion :tada: does not completes to 🎉 like on web

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#1285]

**Comment by progserega** [comment]
such situation for `:curious:`

![element-android](https://user-images.githubusercontent.com/1297163/115342126-19f8f800-a1ed-11eb-8155-9300776238bc.png)
![element-web](https://user-images.githubusercontent.com/1297163/115342130-1b2a2500-a1ed-11eb-8327-1e53ae8fb92f.png)
element desktop: Element: 1.7.23
element-android: 1.1.5

**Comment by SimonBrandner** [comment]
@progserega, opening a new issue might be best

**Comment by progserega** [comment]
> @progserega, opening a new issue might be best

create #3487 3487
