### ISSUE TITLE
Input type on message text field

### ISSUE THREAD

**Issue by vurpo** [vector-im/riotX-android#129]
It seems that the text input field for messages is missing some flag (probably `android:inputType="textCapSentences"` or `InputType.TYPE_CLASS_TEXT`, see https://stackoverflow.com/a/4808749 ), because my phone keyboard doesn't automatically start with a capital letter in Riot X, even though it does in other messaging apps (including the current/old Riot.im app for Android).

**Comment by bmarty** [comment]
Hi @vurpo ,

thanks for reporting, it will be fixed in the next build

Benoit

**Comment by vurpo** [comment]
Thanks for fixing this. However, it seems that it has regressed to the previous behavior at some point recently.

**Comment by vurpo** [comment]
After upgrading to the latest revision, it's working again. Maybe I had some weird intermittent issue with my phone's keyboard, or maybe there were mysterious forces affecting the type of the input text box across different commits?

**Comment by bmarty** [comment]
No no, the issue was back, after a painful merge :).
Sorry about that :)
