### ISSUE TITLE
"Unverified login. Was this you?" doesn't help you navigate which login it's talking about.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riotX-android#1293]
I was testing against matthewtest, which had ~15 unverified sessions on it.  This banner kept coming up (on build 2482):

![image](https://user-images.githubusercontent.com/1294269/80366851-e3aac600-8881-11ea-8ee5-5d818e47574a.png)

Because the device name is truncated, doesn't include a device ID, and doesn't include a "1/15" style prompt, it's very unclear as to which device(s) it's actually telling me about, and if it keeps repeating the same prompt for the same device, or moving onto the next device.

It's also not clear whether tapping "skip" is the same as "later" on Web - how long does "skip" dismiss the banner for?

**Comment by BillCarsonFr** [comment]
See https://github.com/vector-im/riotX-android/pull/1287

**Comment by BillCarsonFr** [comment]
@nadonomy if you think we should add later button to this notification?

**Comment by nadonomy** [comment]
@BillCarsonFr is this issue not redundant now with the changes to aggregate toasts?

**Comment by BillCarsonFr** [comment]
yes probably

**Comment by BillCarsonFr** [comment]
-> Now only show one popup for unverified sessions

Design 

<img width="318" alt="image" src="https://user-images.githubusercontent.com/9841565/80474709-13bc9c80-8948-11ea-83e3-f583dcbdd7b5.png">

https://www.figma.com/file/wwqBo5oAFfk8XKmtd2YaIs/Cross-signing?node-id=0%3A1
