### ISSUE TITLE
Manage Session Settings / Cross Signing update

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#1295]
This issue describes what the manage session list screen should display, and available actions.

This screen depends on whether cross signing is enable in the account, and if the current session is verified

### And Current session is trusted

    - Current Session:
    	- Green Shield, on tap the bottomsheet shows:
    		- Verified
    		- Shows device name / id 
    		- (action) Rename 
    - Other Sessions:
    	- Shields reflects the cross signed status (local trust ignored), on tap the bottom sheet shows
    		- If not cross signed
    			- [red shield] NOT Verified
    			- Shows device name / id 
    			- (action) Manually verify by text
    			- (action) Interactively Verify by Emoji
    			- (action) Sign out of this session
    			- (action) Rename
    		- If cross signed
    			- [green shield]  Verified
    			- Shows device name / id 
    			- (action) Sign out of this session
    			- (action) Rename
    		- If not E2E capable
    			- (No shields / header)
    			- Shows device name / id 
    			- No crytpographic information available
    			- (action) Sign out of this session

 
### And Current session is NOT trusted

	- Current Session:
		- Red Shield, on tap the bottomsheet shows:
			- Verify this login
			- Confirm your identity by verifying this login from one of your other sessions, granting it access to encrypted messages.
			- Shows device name / id 
			- (action) Verify this login 
		- + Shortcut button to Verify this login
		
	- Other Sessions:
		- Shields are all black, on tap the bottomsheet shows:
			- If E2E capable
				- (TBD text?) 
				- (action) Sign out of this session
				- (action) Rename
			- If not E2E capable
				- (No shields / header)
				- Shows device name / id 
				- No crytpographic information available
				- (action) Sign out of this session
 

## If Cross Signing Is not Enabled in the account

    - Current Session:
    		- Green Shield, on tap the bottomsheet shows:
    			- [green shield]  Verified
    			- Shows device name / id 
    			- (action) Rename
    			
    - Other Sessions:
    	- Shields reflect local trust and show same as first case based on local trust

**Comment by BillCarsonFr** [comment]
![image](https://user-images.githubusercontent.com/9841565/80396434-e96dcf00-88b4-11ea-855f-2281c59b3a6d.png)

![image](https://user-images.githubusercontent.com/9841565/80396443-ee328300-88b4-11ea-8837-5ac8a2529c5b.png)

**Comment by nadonomy** [comment]
Feedback from my side:

- [ ] Complete Security in the bottom sheet title should be 'Verify this login'
- [ ] The 'Complete Security' button in the session list is a little strange— it could work, but needs more visual on the visual side & implementation so think we should just remove it for now. Users will navigate to the same path via the red shield -> [Verify this login]
- [ ] If trivial, through this path, 'Skip' should be 'Cancel'
- [ ] 'Sign out this session' should be 'Sign out of this session'
- [ ] 'NOT Verified' should be 'Not Verified'
