### ISSUE TITLE
Some themes not not formatted correctly.

### ISSUE THREAD

**Issue by DumbMachine** [vector-im/riotX-android#130]
Dark mode and Black mode themes are not correctly formatted in the sense that the color of the text remains dark grey, making it difficult to see the texts.

Also when changing themes, the theme changes instantly for the settings tab but not for the chat rooms. A restart of the app is required for the change to take place in chatrooms,

**Comment by bmarty** [comment]
FTR, changing theme on RiotX is not fully implemented

**Comment by bmarty** [comment]
I think it's better now (v0.4.0). Can you confirm @DumbMachine ?

**Comment by DumbMachine** [comment]
Yep the formatting now seems to work better now.  Thank you for your work
