### ISSUE TITLE
RiotX is much heavier than Riot.im

### ISSUE THREAD

**Issue by Thatoo** [vector-im/riotX-android#131]
I've installed RiotX this morning, it was 130Mo at install and few minutes after the first connection it raise up to 250Mo making it the second heaviest app in my phone after OSMand.
Riot.Im in comparison is only 89Mo.

**Comment by bmarty** [comment]
Thanks for feedback.
We will see if we can do something about this.
RiotX is faster than Riot, but it can use more resource to be faster: more disk space (image cache, ...), more RAM, etc.

**Comment by bitmvr** [comment]
I'd argue this should be expected 🤷‍♂ ...
