### ISSUE TITLE
<img> in HTML messages are not rendered correctly

### ISSUE THREAD

**Issue by auscompgeek** [vector-im/riotX-android#1320]
> The strongly suggested set of HTML tags to permit […] is: […], img.
>
> […]
>
> Clients should only permit the attributes listed for the tags below. […]
>
> img: width, height, alt, title, src (provided it is a Matrix Content (MXC) URI)

https://matrix.org/docs/spec/client_server/latest#m-room-message-msgtypes

**Comment by tulir** [comment]
Duplicate of #351

**Comment by auscompgeek** [comment]
Gah, I didn't find that issue when I did a search just earlier. Thanks.
