### ISSUE TITLE
saved images don't show up in gallery

### ISSUE THREAD

**Issue by duncanturk** [vector-im/riotX-android#1324]
Long pressing on an image in the timeline and selecting "save" option should make the picture show up in the gallery app, but it does not.
A toast saying "Media file added to gallery" shows up.

Tested on LineageOS 16.0 with Simple Gallery and LOS stock gallery.

play store v0.19.0

Relates to #973 and PR #1242

**Comment by Mayankmkh** [comment]
Hi @duncanturk 
My name's Mayank Kharbanda. I'm new to open source and excited to contribute.
I think this issue would be a good starting point for me and would like to work on it.
