### ISSUE TITLE
Downloading audio

### ISSUE THREAD

**Issue by barudaret** [vector-im/riotX-android#1325]
I know there's no player, so I would like to just download the file and open it in vlc, but riotx doesn't provide that option.  If I want to download, I have to use the old app (which also does not have a player, but will let me download)

![Screenshot_20200505-133957_RiotX dbg](https://user-images.githubusercontent.com/32847759/81114140-4a5d5e80-8ed6-11ea-94b0-be9daeb96f71.jpg)

**Comment by barudaret** [comment]
Oh, it's in the long-press menu.  That's not torribly intuitive, but it works.

**Comment by bmarty** [comment]
Yes. Also, when there is a toast "Not implemented yet..." that a sign that in the future something will be done to improve it :). But when is the question :/
