### ISSUE TITLE
Name rendered non-uniformly per room

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#1326]
v0.19

In I think all rooms, my name is rendered as „Frank“, but in the RiotX room, I get rendered with my MXID afterwards.

![IMG_20200505_222718](https://user-images.githubusercontent.com/10520767/81114495-6edf2800-8f22-11ea-8a76-309ee6f752ae.jpg)

![IMG_20200505_222759](https://user-images.githubusercontent.com/10520767/81114509-73a3dc00-8f22-11ea-93f8-82c5c2a9647e.jpg)

**Comment by bepvte** [comment]
I believe thats because someone else had the name 'Frank' in the room during any point in the rooms history. I think its for security.

**Comment by fbruetting** [comment]
Makes sense. 🤔

**Comment by bmarty** [comment]
Yes, @bepvte is right, this is what we call "disambiguated display name" (Ref: https://github.com/vector-im/riotX-android/blob/f0f3e8ddb9e5ba46f6eda056e62a5a3a2a02d97a/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/sender/SenderInfo.kt#L28)

In the room member list of the RiotX room you will see that there are two users with display name "Frank"
