### ISSUE TITLE
Images always sent original size

### ISSUE THREAD

**Issue by fredronnv** [vector-im/riotX-android#1333]
Regardless of checking "Send image with the original size" the images seem to always get sent using the original size. This seems to have appeared in the latest update (0.19.0) as it worked as expected previously.

**Comment by squarepupil** [comment]
Can confirm. 6MB image gets sent as 6MB image!

**Comment by Thatoo** [comment]
Same for me

**Comment by bmarty** [comment]
Image compression has been disabled by @onurays because the library we were using is not compatible with Android 10.

**Comment by bmarty** [comment]
FTR https://github.com/vector-im/riotX-android/issues/1333

**Comment by bmarty** [comment]
To restore the lib usage, see commit f7fd23b153c3821b7e98efdf7047eca9a9405f23 for file im.vector.matrix.android.internal.session.content.UploadContentWorker

**Comment by Linuxine** [comment]
Hi, as Android 10 seems to be used by about 10% of devices only, why disable this feature and penalize about 90% of Android users ? Beside, why leave the non working checkbox in this case, this is confusing ?

For users like me hosting a homeserver, images can easily fill a lot of disk space if not compressed. Any idea if this will be enabled again soon ? This is no big deal since the compression is still working on the classical Riot (non X) , but I was getting used to RiotX, it is nicer :D

**Comment by flackr** [comment]
It looks like you could also add `android:requestLegacyExternalStorage="true"` per https://github.com/zetbaitsu/Compressor/issues/134 temporarily to maintain support on Android 10. I'm not aware how this code in RiotX works, but perhaps you could copy the image to scoped storage first per the [article](https://heartbeat.fritz.ai/implementing-scoped-storage-in-android-10-4b657280c066) linked on that issue.

**Comment by witchent** [comment]
I just saw that the pull request will close this issue while not fixing it for android 10. As there is no other issue open about this (and I think this one is fine as it is) maybe you shouldn't close this issue before fixing it for android 10 as well?

**Comment by onurays** [comment]
> I just saw that the pull request will close this issue while not fixing it for android 10. As there is no other issue open about this (and I think this one is fine as it is) maybe you shouldn't close this issue before fixing it for android 10 as well?

@witchent I am working on covering Android 10 and above too and won't close the issue without solving this.

**Comment by witchent** [comment]
> > I just saw that the pull request will close this issue while not fixing it for android 10. As there is no other issue open about this (and I think this one is fine as it is) maybe you shouldn't close this issue before fixing it for android 10 as well?
> 
> @witchent I am working on covering Android 10 and above too and won't close the issue without solving this.

This is awesome news, thank you so much for your work.
