### ISSUE TITLE
All users seems to be able to see the enable encryption option in room settings

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#1341]
![image](https://user-images.githubusercontent.com/9841565/81304305-2daf5b00-907d-11ea-85a3-0c49729750a6.png)

On tap, user sees that
<img width="378" alt="image" src="https://user-images.githubusercontent.com/9841565/81304335-3acc4a00-907d-11ea-819b-70815fef5a54.png">

**Comment by bmarty** [comment]
Fixed in #1665
