### ISSUE TITLE
No option to permanently dismiss "Review where you're logged in" banner

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#1347]
The "Review where you're logged in" banner keeps reappearing on every app startup. I currently cannot verify all my sessions as I don't have access to the devices where these are on for a while.

I'd like riotX to stop showing me this banner after I dismissed it once.

**Comment by BillCarsonFr** [comment]
If you swipe this session out, it should disappear and not be shown ever again

**Comment by Bubu** [comment]
I've since resolved the untrusted device for me, but I remember the banner popping up again every riotx app start (after swiping away from latest, phone reboot or force stop from settings.)

**Comment by Bubu** [comment]
Haven't seen this since.
