### ISSUE TITLE
Rageshake screenshot doesn't take modals

### ISSUE THREAD

**Issue by tuxayo** [vector-im/riotX-android#1349]
v0.19.0 via F-Droid.

It was for this modal (I don't know the right term): ![Screenshot_20200510-142423](https://user-images.githubusercontent.com/2678215/81499218-25982b00-92ca-11ea-8f65-e39363792bcc.png)

**Comment by T-bond** [comment]
![20200512_170556](https://user-images.githubusercontent.com/3778556/81710233-e3f6b400-9472-11ea-934a-d67962a4294e.jpg)
I think more elements are missing. I had the following problem two times, but rageshake did not captured it. The text ,,de te is :D" and all the three read markers are floating and fixed to the screen (absolute position). Also this is a Direct chat room, so I don't know where the avatar with the ,,J" came from, as there is no more member in the room.
So if I scroll the 3 read marker (duplicated two white background image, and the misterious default ,,J") are staying at the same place, and it is the same story with that one text, mentioned above too.
If I go to the room chooser/main menu, and come back, those things are gone, and everything is working correctly again.
