### ISSUE TITLE
riot-x on android

### ISSUE THREAD

**Issue by Motocycle347** [vector-im/riotX-android#1359]
This is a request for a feature

When I close the application I would like to have my session to be automatically signed off.  

### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce
openriot-x on android 10 finish what I am doing close the app.
I will remain signed on. I would like to at this point to be signed off.

**Comment by bmarty** [comment]
Sorry, we won't implement that.
