### ISSUE TITLE
Feature request: search in rooms/people list

### ISSUE THREAD

**Issue by hydrargyrum** [vector-im/riotX-android#1384]
When I join a lot of rooms, the list of rooms is messy, ordered by last activity I guess. However, if I want to send a message to a specific room, I don't have a search field to find the desired room in the mess, so I have to scroll all the rooms list until I find it, hoping I won't overlook it. It's tedious.

Such a search feature was present in the base Riot app. For example, see on https://techwiser.com/wp-content/uploads/2018/01/riot.jpg

**Comment by violoncelloCH** [comment]
@bmarty @ganfra well that's why I suggested to use a search icon and not that filtering icon at the top right... even though it's technically filtering, most people don't find it that way; a search (magnifying-glass) icon would be much more discoverable for the average user

**Comment by bmarty** [comment]
I agree the icon is not clear for all users.
I assume we will have a unified search in the future, so the icon will be replaced by the magnifying glass.
Let's replace it now :)
