### ISSUE TITLE
Will session syncing be improved

### ISSUE THREAD

**Issue by hussi1** [vector-im/riotX-android#1386]
In this version will we see fast session syncup ? currently it is very slow in riot android and there is no way to force refresh existing session.

**Comment by bmarty** [comment]
Hi @hussi1, RiotX is way faster than Riot-Android to start. FTR, RiotX will replace Riot-Android in the PlayStore in a near future

**Comment by hussi1** [comment]
What about matrix sdk ? will it be enhanced ?
