### ISSUE TITLE
We need a way to enter an URL in the SSO screen.

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#1400]
When connecting to RiotX using SSO, for instance using `mozilla.modular.im`, if user choose to enter an email and click "Enter" here: 

<img width="317" alt="image" src="https://user-images.githubusercontent.com/3940906/82804903-60ca5a80-9e83-11ea-8439-014a37545156.png">

He receives an email with a link which has to be open in the same webview.

Extract of the e-mail content:

> Click and confirm that you want to sign in to mozilla.modular.im. Please sign in using the same web browser that you used to generate this link. The link will expire in fifteen minutes.

and a URL to click or copy

But currently there is no way in RiotX to enter the received url.

**Comment by auscompgeek** [comment]
I think instead of opening a webview, the SSO flow should open a real browser instead.

**Comment by bmarty** [comment]
We are using a Webview because there is a Javascript bridge to the app to send the credentials back.
