### ISSUE TITLE
Enable encryption by default in RiotX when creating a private room

### ISSUE THREAD

**Issue by Regia2** [vector-im/riotX-android#1407]
Currently, when creating a private room, the default encryption is enabled only on Riot Desktop. 

Riot Desktop : 

<img width="385" alt="Create a new private room (Desktop)" src="https://user-images.githubusercontent.com/63846091/82878883-6a63c900-9f3c-11ea-9624-10e0491d419c.PNG">

RiotX : 

![Create a new private room (RiotX)](https://user-images.githubusercontent.com/63846091/82878912-794a7b80-9f3c-11ea-80be-2ce1a324d531.jpeg)

**Suggestions of features that could improve the user experience :**
- RiotX : enable encryption by default  when the user creates a private room
- RiotX : disable encryption when the user creates a public room
- RiotX : propose to add an alias when the user creates a public room 
- Riot Desktop : Add a button to publish the room in the room directory
- RiotX and Riot Desktop : add a field to let user set a topic immediately after creating the room

**Comment by bmarty** [comment]
Yes, this is nearly the same issue than #1314 
I keep it open to check the overlap :/

**Comment by Regia2** [comment]
> Yes, this is nearly the same issue than #1314
> I keep it open to check the overlap :/

Thank you very much @bmarty !

**Comment by tulir** [comment]
When this is implemented, RiotX should respect the .well-known option to disable e2ee by default: https://github.com/vector-im/riot-web/blob/develop/docs/e2ee.md
