### ISSUE TITLE
Can't make voice call from web client to riotX

### ISSUE THREAD

**Issue by David-Else** [vector-im/riotX-android#1408]
This is my first time using the software, and am finding the lack of instructions frustrating. I am using v0.20.0 from FDroid.

I have created a room using the web client and invited the person using RiotX into it. We both have a little black blob next to us, I don't know what that means. I try to call from the web and on RiotX it rings... I got some kind of notification that when clicked did nothing. In RiotX I can't answer! It says:

`RiotX does not handle events of type 'm.call.candidates'

Is this app ready to use for voice chat yet? Does the web client work calling another web client? THANKS!

**Comment by rakshazi** [comment]
RiotX does not support calls yet, but you may subscribe to feature request (check issues)

The most wanted feature for me, tbh

**Comment by bmarty** [comment]
Yes, this is handled in #611 and we are currently working on it 🎉

**Comment by David-Else** [comment]
Cheers, I subscribed to https://github.com/vector-im/riotX-android/issues/611 :)
