### ISSUE TITLE
Support clear reactions in e2e rooms

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#142]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2448  

As explained by Ryan at https://github.com/vector-im/riotX-android/issues/142#issuecomment-505907002) for riot-web

**Comment by manuroe** [comment]
It works in phase:1 but for main use cases. e2e will be officially supported in phase:2.

**Comment by jryans** [comment]
Riot Web has changed to [special case reactions](https://github.com/matrix-org/matrix-js-sdk/pull/968) so that they are sent without encryption to [avoid notifications](https://github.com/vector-im/riot-web/issues/10130).

**Comment by manuroe** [comment]
Encrypted reactions will be supported later in phase:3

**Comment by manuroe** [comment]
Just tested on RiotX. They are already sent in clear.
