### ISSUE TITLE
Missing required field when sending `m.key.verification.accept`

### ISSUE THREAD

**Issue by Dominaezzz** [vector-im/riotX-android#1433]
In [`m.key.verification.accept`](https://matrix.org/docs/spec/client_server/r0.6.0#m-key-verification-accept), `method` is a required field but it is not specified [here](https://github.com/vector-im/riotX-android/blob/master/matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/verification/VerificationInfoAccept.kt) the `method` field is not specified.

Riot-web does the [same thing](https://github.com/matrix-org/matrix-js-sdk/issues/1390) for some reason.

**Comment by bmarty** [comment]
It's maybe an error in the documentation. @BillCarsonFr could you check that please?

**Comment by uhoreg** [comment]
This was a spec bug (now fixed), rather than a bug in the implementation.
