### ISSUE TITLE
Replace "filtering rooms" with "search rooms"

### ISSUE THREAD

**Issue by babolivier** [vector-im/riotX-android#1434]
What RiotX calls "filtering" rooms is effectively searching through them. I find the use of this wording, and especially of the filter icon, counterintuitive and really confusing.

In most apps I use, that icon and terminology are used to apply a defined filter on the data in the view, i.e. if you click on that icon it shows a drop down menu with several filtering options. For example, with the trainline app, clicking on the filtering icon on the "trips" tab, it offers me to either view "upcoming trips" or "past trips".

In RiotX, this icon and terminology are used for what almost every other app I use call "search" and use the search icon for. This means each time I want to search a room in RiotX I have to spend a few seconds wondering where the search icon is, then remembering RiotX considers it filtering and that I need to click on the filter icon. I personally find this quite annoying.

**Comment by violoncelloCH** [comment]
The icon has already been replaced with a search (magnifying glass) icon recently...

**Comment by babolivier** [comment]
Ah, well, ignore me then. The reason I opened this issue is because it's still using the filter icon on the released app (i.e. not the develop releases), so if that's fixed on develop let's close this issue.
