### ISSUE TITLE
Dark theme has very low contrast

### ISSUE THREAD

**Issue by sephii** [vector-im/riotX-android#1438]
When selecting the "dark" or "black" modes, the text is too dark, making it very difficult to read:

![signal-attachment-2020-06-03-072145_001](https://user-images.githubusercontent.com/754333/83598917-40795a80-a56b-11ea-94d2-8ed3e00499d1.png)
![signal-attachment-2020-06-03-072145_002](https://user-images.githubusercontent.com/754333/83598919-4111f100-a56b-11ea-9f84-4da3cd75bc59.png)

* RiotX version: 0.21.0 [40021002] (G-b2731)
* Matrix SDK version: 0.0.1 (997101a4)
* Android version: 9

**Comment by rakshazi** [comment]
Same problem here on v0.21, some additions:

v0.19 and (if I remember correctly) v0.20 had good text contrast in dark theme.

Low contrast only for user chat text (system messages like "user changed avatar" not affected)

**Comment by bmarty** [comment]
Yes, it's a regression, already fixed on v0.22.0-dev.
You can workaround the pb by restarting the app after the theme change.

**Comment by rakshazi** [comment]
Workaround works!
If it's already fixed in Dev, may be that issue should be closed?

**Comment by sephii** [comment]
Thanks, the workaround works! I'll test on v0.22 when it's out and reopen the bug if necessary.
