### ISSUE TITLE
Error when handling /version responses

### ISSUE THREAD

**Issue by timokoesters** [vector-im/riotX-android#1442]
Response to /versions:
1.  [r0.5.0, r0.6.0] works
2.  [r0.5.0, r0.6.1] doesn't work
3.  [r0.6.0] doesn't work

If 1. works, I would expect 2. to work too, because it's just a minor version upgrade. [Servers have to send only the latest minor version.](https://matrix.org/docs/spec/client_server/unstable#get-matrix-client-versions).

**Comment by bmarty** [comment]
Hello @timokoesters , thanks for reporting, I've implemented a fix in #1447
