### ISSUE TITLE
Wrong /query request

### ISSUE THREAD

**Issue by timokoesters** [vector-im/riotX-android#1444]
https://matrix.org/docs/spec/client_server/unstable#post-matrix-client-r0-keys-query

/query has a field device_keys that maps a user id to a list of devices.
RiotX sends this json: `"device_keys":{"@olaf:matrixtesting.koesters.xyz":{}`
But `{}` is not an empty list. It should be `[]` instead.

**Comment by bmarty** [comment]
True!
Thanks for reporting, I'm on it
