### ISSUE TITLE
Room Settings: Name, Topic, Photo, Aliases, History Visibility

### ISSUE THREAD

**Issue by onurays** [vector-im/riotX-android#1455]
- [ ] Edit room name

- [ ] Edit room topic

- [ ] Select room photo from Gallery

- [ ] Set room photo from Camera

- [ ] Remove room photo

- [ ] List aliases

- [ ] Add / remove aliases

- [ ] Select room history visibility

**Comment by bmarty** [comment]
Maybe mutualize code with #1314 ?
