### ISSUE TITLE
Aggregation API: Local echo

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#149]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2453  

Update the SDK to improve UX responsiveness by using local echo.

**Comment by BillCarsonFr** [comment]
Web related issues: https://github.com/vector-im/riot-web/issues/9675

Edge cases for local echo:

* Manage sending errors for reaction:
If a reaction event enters fails to send state (after several retry). Should we just discard the event? Is it possible to display somewhere in the UX a failed to send status with retry?

* Redaction of sending event:
If a reaction is beeing sent, is it possible to cancel it (might be a race condition), or just block the undo UI while the reaction is sending

* Undo an undo, (maybe should debounce reaction toggle?)
