### ISSUE TITLE
RiotX calls /keys/upload/{deviceId} instead of just /keys/upload

### ISSUE THREAD

**Issue by timokoesters** [vector-im/riotX-android#1502]
https://matrix.org/docs/spec/client_server/r0.6.1#post-matrix-client-r0-keys-upload

**Comment by bmarty** [comment]
I assume it comes from the legacy SDK, I have to check that

**Comment by bmarty** [comment]
It has been a (pretty) recent change on the JS SDK: https://github.com/matrix-org/matrix-js-sdk/commit/1b6a74fd93febadda1778f311f7c4a4704689115

I do it for RiotX
