### ISSUE TITLE
RiotX doesn't use the unstable prefix

### ISSUE THREAD

**Issue by timokoesters** [vector-im/riotX-android#1503]
For example for /room_keys/version

**Comment by bmarty** [comment]
Yes, RiotX does not use the unstable prefix for KeysBackup API, and it has never be the case, even for the legacy Riot-Android application. I will check with the team if we should use the unstable prefix for keys backup, as it is pretty old now (but still not in the official spec)

**Comment by bmarty** [comment]
Seems that the [JS-SDK uses the unstable prefix](https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.js#L1481), so I will do the change

**Comment by bmarty** [comment]
https://github.com/matrix-org/matrix-js-sdk/blob/develop/src/client.js#L1481
