### ISSUE TITLE
Incomplete predicate in RealmCryptoStore#getOutgoingRoomKeyRequest

### ISSUE THREAD

**Issue by johnjohndoe** [vector-im/riotX-android#1519]
I stumbled upon [RealmCryptoStore#getOutgoingRoomKeyRequest](https://github.com/vector-im/riotX-android/blob/d2f14889344dac8f25b945ea96afadb2c01c3cff/matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/crypto/store/db/RealmCryptoStore.kt#L899-L902) which contains the following inline function and predicate:

``` groovy
}.firstOrNull {
    it.requestBody?.algorithm == requestBody.algorithm
    it.requestBody?.roomId == requestBody.roomId
    it.requestBody?.senderKey == requestBody.senderKey
    it.requestBody?.sessionId == requestBody.sessionId
}
```

This looks as if we are missing some chaining here. I guess it should be something like:

``` groovy
}.firstOrNull {
    it.requestBody?.algorithm == requestBody.algorithm &&
    it.requestBody?.roomId == requestBody.roomId &&
    it.requestBody?.senderKey == requestBody.senderKey &&
    it.requestBody?.sessionId == requestBody.sessionId
}
```

Can someone with more insides please verify my assumption?

**Comment by bmarty** [comment]
Yes, absolutely, this is a mistake. I will fix it, thanks!
