### ISSUE TITLE
How to download?

### ISSUE THREAD

**Issue by gerroon** [vector-im/riotX-android#156]
Hi

Can yopu please tell me how to download the build? I goto buold site it is very confusing and I cant find the build apk files.

thanks

**Comment by bmarty** [comment]
Hi @gerroon ,
RiotX is not yet available on the PlayStore, and development builds can be downloaded here:
https://buildkite.com/matrix-dot-org/riotx-android/builds/latest?branch=develop&state=passed - click on *Assemble Debug version* then on *Artifacts*
Benoit

**Comment by gerroon** [comment]
@bmarty

Thanks, that works. The download process was not that obvious. I was able to download with your instructions.
