### ISSUE TITLE
Re-order home tabs

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#1565]
**EDIT**: Final decision:
We keep only 2 tabs, one for DMs and one for rooms. Invites will be displayed in the corresponding tab. We will iterate later to improve the Catchup tab behavior.

See #1592 

----

This is a temporary quick win to improve UX on the home.

New order:
DMs - Rooms - Catchup.

At first launch the DMs tab should be displayed.

Also in the Catchup, we keep displaying invitations, but now we only display rooms with mentions (room with highlightCount > 0)

And the catchup tab does not display numbers, but rather a (always red) dot instead, to avoid having twice the same number as currently. This was previously the case on legacy Riot-Android for favorite tab: we only used a dot.

We will need a new icon for the catchup tab (currently it is a home).

The FAB with submenu on the catchup tab should be hidden now.

Dev:
Do not remove the FAB with submenu, we will reuse it later (for unified view, see below)

In the future:

As suggested below, it should be nice to have all secrtions in one list and an option to split in several tabs if user wants it.

**Comment by duncanturk** [comment]
I think an alternative to changing the order would be to show all rooms in the catchup tab.
So the "catchup" tab is used as a "home" tab in which all chats are listed (maybe exclude low-prio and/or public rooms). This unified view would be a huge UX improvement for users that are used to Whatsapp-like messengers.

These changes would justify the current prominent position of the catchup/home tab.

**Comment by kojid0** [comment]
> I think an alternative to changing the order would be to show all rooms in the catchup tab.
> So the "catchup" tab is used as a "home" tab in which all chats are listed (maybe exclude low-prio and/or public rooms). This unified view would be a huge UX improvement for users that are used to Whatsapp-like messengers.
> 
> These changes would justify the current prominent position of the catchup/home tab.

Also please consider the possibility to disable tabs completely. I'm fine with one view listing all my DMs and rooms together (whatsapp/telegram-style). No need to complicate things for normal users with lots of tabs. Option for power users to enable tabs would be a nice thing though.

**Comment by violoncelloCH** [comment]
Additionally it could be suggested automatically to enable the tabbed interface if there is a certain number of 1:1 _AND_ #group rooms

**Comment by progserega** [comment]
I hope you will return  "Catchup tab" as main first tab. It is was very nice feature.

I think it is nice if in options will be settings like "tabs organisation" with 3 variants:
1. No tabs - all (invites, DM, rooms) - in one list (whatsapp style) - enabled by default
1. two tabs (DM and rooms) - as today, after this commit.
1. 3 tabs - "cachup tab" (first and main), DM, rooms - as was before this commit.

P.S. In the pursuit of more users - we should not forget the geeks who use/integrate/tell other people about the matrix who are far from it :-)
