### ISSUE TITLE
File isn't downloaded when another file with the same name already exists

### ISSUE THREAD

**Issue by mawalu** [vector-im/riotX-android#1578]
```
RiotX version: v0.22.0
Android version: 9 / Lineage 16.0
```

RiotX does not download a file if their already exists another one with the same name in the riotx download folder. I get a notification that the new file was downloaded but only the old exists one on my device

**Comment by bmarty** [comment]
Yes, thanks for reporting, I think it's now fixed (in Riot-Android v0.91.3-beta). @BillCarsonFr could you confirm please?
