### ISSUE TITLE
ability to change chat alignment

### ISSUE THREAD

**Issue by jimmasters** [vector-im/riotX-android#1615]
Most chat clients use alignment.  For instance WhatsApp and SMS clients have your comments aligned to the right and all other group members aligned left.  This helps the chats in terms of readibility.

Please consider adding this as an option in the setting menu.

**Comment by jimmasters** [comment]
![Screenshot_20200704-183856_Messages](https://user-images.githubusercontent.com/51320372/86509309-514b1380-be2a-11ea-831d-0e5af450f2eb.jpg)

**Comment by jimmasters** [comment]
Please see example of alignment in above screenshot.

**Comment by duncanturk** [comment]
May be a duplicate of #979

**Comment by jimmasters** [comment]
I agree, it's a duplicate.  I will close this request.
