### ISSUE TITLE
Not available on PlayStore with a chromebook

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/riotX-android#1617]
With the new Riot.IMx an old bug reappeared (#932), app isnt as beta available at the Google playstore for my Chromebook

**Comment by bmarty** [comment]
Ok, I will check that, maybe due to the permissions we have added related to VoIP.

**Comment by Wandelstock** [comment]
Could it be the camera permission for scanning qr-codes?

**Comment by bmarty** [comment]
This is normally already handled (in the fix for #932)

**Comment by Wandelstock** [comment]
Works now after the update

**Comment by bmarty** [comment]
Ok, thanks for the update, so I reject #1641
