### ISSUE TITLE
Empty Home is displayed before the end of the initial sync

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#162]
After logging in the user see an empty home during the initial sync.

We should either wait for end of initial sync before entering the Home, or display a loader in the Home during the initial sync.

Maybe the second solution is better because the loader can also be displayed during catchup sync: for the moment, when a logged user launch again RiotX, the (not up to date) data in cache are displayed, then the catchup sync finished and the screen is rendered with the last data.

**Comment by ganfra** [comment]
At the moment it will show a linear progress bar in top of the screen. It might be improved later.
