### ISSUE TITLE
call button position

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1621]
Interface should be consistent across platforms:

ios:
![image](https://user-images.githubusercontent.com/14617699/86517374-1dbfb780-be31-11ea-9242-5a86daacedde.png)

android:
![image](https://user-images.githubusercontent.com/14617699/86530314-6ffbe980-bec0-11ea-8949-24ea9a03b0f5.png)

**Comment by kojid0** [comment]
Androids riotx call buttons are better positioned, IMO.

**Comment by 532910** [comment]
not sure, the send button is useless until something is typed

**Comment by kojid0** [comment]
The send button while no message is in the field will most likely eventually be replaced when voice messages #29 are being implemented

**Comment by 532910** [comment]
If so, then I'm on your side (:
