### ISSUE TITLE
trying to share media does nothing

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1622]
Just nothing happens selecting the `Share` from the long-pressing menu on media file.

**Comment by duncanturk** [comment]
For me the share options show up delayed.
It seems to download the file first and than show the share options. So depending on file size and connection this may feel like it never shows the dialog.

**Comment by 532910** [comment]
I'm unable to share even a tiny media, less than 1Mb size.

**Comment by BillCarsonFr** [comment]
Fixed by #1651

**Comment by 532910** [comment]
Works fine now.
