### ISSUE TITLE
verification: don't error if we don't know about some keys 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#163]
related to https://github.com/matrix-org/matrix-js-sdk/pull/939
> This is needed for compatibility with cross-signing, because with cross-signing, the client will be asked to verify the cross-signing key, but current clients don't know how to do that, so they should just ignore it rather than failing.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2484)

**Comment by BillCarsonFr** [comment]
Not application for riotX
