### ISSUE TITLE
Regression Composer does not grow, crops out text

### ISSUE THREAD

**Issue by ManDay** [vector-im/riotX-android#1650]
Between 804d712848718f823f830f1262d64612e7dd13eb and b2f6476f78acd17c87d6feb5d52611f0bd2e4488 as far as I can bisect from the buildkite APKs of develop.

The composer does not grow when text more than 1 line is typed. Up to 3 lines are still visible as they seem to fit in the reserved space for 1 line (fontsize Normal). When even more lines (>3) are added, both the beginning and the end (thus the currently typed text) are cropped, making it virtually impossible to type, since you don't see what ends up in the textbox.

**Comment by ManDay** [comment]
As multiple users have not been able to reproduce this, I might add:

 - This is reliably reproduced for me. Uninstalling, reinstalling, different updates and clearing the cache all did not resolve the issue.
 - Android 9.
 - I submitted a corresponding rageshake, no idea where those end up, though.

**Comment by tulir** [comment]
Can confirm on Riot.imX dbg G-b3182, Android 10

**Comment by ganfra** [comment]
Yes, one of the updated dependency breaks it.

**Comment by bmarty** [comment]
Fixed in #1665
