### ISSUE TITLE
Input text cut of for long texts

### ISSUE THREAD

**Issue by samuel-p** [vector-im/riotX-android#1663]
If you enter a long text over multiple lines the text is cut of at the top and at the bottom, because the field is not growing or scrollable. I'm using the latest beta (`0.91.5-dev`). If you edit a message, it seems to work without any problems.

Here is a screenshot:

![Screenshot_20200710-201028_Riot imX_dbg](https://user-images.githubusercontent.com/7959516/87186896-910f7080-c2ec-11ea-9420-edbd047ede59.png)

**Comment by witchent** [comment]
I think this is a duplicate of https://github.com/vector-im/riotX-android/issues/1650

**Comment by samuel-p** [comment]
@witchent Yes it look similar. I didn't found it before, but I'll closing it now.
