### ISSUE TITLE
swipe message to right as shorthand for reply to

### ISSUE THREAD

**Issue by violoncelloCH** [vector-im/riotX-android#167]
the new design is already really nice with the long tap on message and this menu coming in form the bottom! however if you use the reply to message option quite a lot, this becomes a little bit painful...
so a really nice UX could be a shorthand for the reply to option as a swipe to the right on the respective message

**Comment by bmarty** [comment]
Hi @violoncelloCH , thanks for the suggestion.
I know other messaging app uses this UX pattern to reply to messages, but I'm not really found of it.
Maybe a simple tap on the message should be a shortcut to the reply action, or even the single tap action may be configurable in the setting.
Let's discuss this with @BillCarsonFr and @nadonomy

**Comment by violoncelloCH** [comment]
thank you for considering @bmarty !
I'm not opposed against a different UX pattern as a shorthand for replys, however I think it's important that a shorthand is easy accessible but at the same time not triggered accidentally all the time ... that's why I'm not sure if a single tap as a shorthand for actions is the best thing here...

**Comment by vc7ee** [comment]
Single tap seems to work better. In higher speed chats (immagine 1-2 message per second) how are you gonna swipe?
Swipe might be instead better used to edit your own message.

**Comment by tulir** [comment]
> how are you gonna swipe?

Exactly the same way you'd swipe in a chat with no new messages. After you start swiping, it shouldn't matter if the view scrolls down, the swipe gesture should still affect the same message until you let go.

**Comment by progserega** [comment]
I think simple tap on message is more nice for reply - it is more simply. This behavior is very nice in old Riot. I think that will nicely if this behavior will be in RiotX also.

**Comment by vc7ee** [comment]
Swipe could be used for pinning. I think there should be a fast way to edit your messages (you can also have for deleting, go to edit and press delete from there?) and swipe seems to be a great utilization. Since pins are not used often, both side swipes may be used for editing.
Though we can also argue that the user should have the right to edit half swipe left, half swipe right, full swipe left, full swipe right actions.

**Comment by bmarty** [comment]
@BillCarsonFr has implemented the swipe on left to start a reply in #382

**Comment by violoncelloCH** [comment]
Really nice implementation! Thanks!

**Comment by Mortein** [comment]
The swipe direction in #382 is backwards.

Reply is generally swiping left to right, not right to left.
