### ISSUE TITLE
Support matrix configured custom sounds

### ISSUE THREAD

**Issue by Half-Shot** [vector-im/riotX-android#169]
The feature landed in riot-web https://github.com/vector-im/riot-web/issues/2105, and would be cool to see it also work in riotX.

**Comment by BillCarsonFr** [comment]
Short answer, user can do it in the phone settings (notification channel setting)

More details:
Starting android N, notifications behavior (vibration, sound,  light, etc...) is defined directly in the phone settings via a 'notification channel'. 

The app does not directly set the behavior per notification, but directly post the notification in a given channel. If you try to change the sound in app, it will not have any effect, the user defined channel settings are used (if channel is muted, you cannot play a sound)
The channel is defined the first time the app is launched, and in the app stand point it is immutable (only the user can configure it in the phone settings).

It could be possible to set it in app by deleting the channel and recreate a new one (a bit hacky), if we want for example to have common sound settings in web and mobile.
