### ISSUE TITLE
Infinite loop at startup when migrating account from Riot

### ISSUE THREAD

**Issue by bjonnh** [vector-im/riotX-android#1699]
I cannot use RiotX (installed from the Beta Program PlayStore), it just keeps restarting the initial setup (the progress bar resets to zero and it start again getting account data, crypto keys, joined rooms etc)

I tried to remove (multiple times) cache and storage, reinstall… nothing worked. it just keeps doing that over and over (I left it for 30 min, it was still doing that)

OS is Android 9

**Comment by bjonnh** [comment]
I reverted back to Riot, and it was able to sync my account  in less than 5 seconds…

**Comment by bmarty** [comment]
What is your homeserver?
Have you sent rageshakes?

**Comment by bjonnh** [comment]
I can't send rageshakes it does nothing
I'm using the matrix server

**Comment by bjonnh** [comment]
Still happening with Element from Google Play Store.

**Comment by bjonnh** [comment]
I finally was able to do a rageshake and gave this issue number in the title. no idea if it went out as I got no confirmation…

**Comment by bjonnh** [comment]
I can make a video of the infinite loop if that help…

**Comment by ovitters** [comment]
I'm facing the same with both RiotX and Element. No idea what a rageshake is. Deleting data doesn't help. OS is Android 10.

I seldom use Riot. I have a Matrix account that's logged into a few IRC bridges (GimpNet, Freenode) and related channels.

**Comment by bjonnh** [comment]
Rageshake is when you shake your phone inside Riot/Element, it allows you to send a bug report that could help the developers find out what is wrong. Try shaking it a few times.

**Comment by bjonnh** [comment]
I uninstalled the google play one, rebooted, installed the f-droid one, same problem.

**Comment by bjonnh** [comment]
I just did a rageshake from the f-droid version with the github ID in the title.

**Comment by bjonnh** [comment]
If that can help, it keeps showing me a verification screen, and sometimes I can validate (from another session), but it still continues to display it… Even if the login was verified… (got the shields and okayed)

**Comment by bjonnh** [comment]
@ganfra  found the issue, I went to the settings and removed all the ignored users I had and it solved the issue. There was likely a corruption in the JSON data there.

I suppose you may want to still have a way to skip that JSON parsing and notify the user they have to check their account data…

**Comment by ganfra** [comment]
Thanks for checking, will be fixed in next release!

**Comment by ehuelsmann** [comment]
Same behaviour here. Care to elaborate on the steps to take?

**Comment by bjonnh** [comment]
@ehuelsmann I went to my settings in Element web, went to my blocked user list and removed them all. Then restarted element on Android and it solved the issue.

**Comment by bmarty** [comment]
Should be fixed by #1766
