### ISSUE TITLE
Implement e2ee - crypto

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#17]
Here is the recipe so far:

- [x] Import legacy code from Riot to RiotX
- [x] Make the code compil once
- [x] Migrate the network code to the new archi (Tasks, etc.)
- [ ] Migrate the realm code to the new archi
- [x] Create services to expose crypto API (CryptoService, KeysBackupService, SasVerificationService)
- [x] Import UI for SasVerification
  - [x] incoming request are displayed
    - [x] can be cancelled
    - [x] can be accepted
- [x] Import UI for KeysBackup
- [x] Plug in the crypto settings in main settings screen (display info, import/export keys, etc)
  - [x] Display device name + rename device
  - [X] Display device id + copy to clipboard
  - [X] Display device fingerprint + copy to clipboard
  - [x] Enable/Disable crypto to verified device only
  - [x] Display list of devices, and display device detail when clicking on a detail
    - [x] Delete a device
    - [x] Rename a device
  - [x] Export room keys (old method)
  - [x] Import room keys (old method)
  - [x] Open keys backup management
- [x] Plug in the crypto setting in room setting screen (the screen is not yet available) (See #178)
- [x] Manage crypto data from the sync 
  - [x] Handle encrypted to_device event
- [x] Send encrypted event
- [x] Decrypt encrypted event
- [X] Display message type `m.room.encryption` in the timeline

Also:

- [x] Clear crypto DB when user logouts
- [x] Introduce change from https://github.com/vector-im/riot-android/pull/3111
- [x] Introduce change from https://github.com/matrix-org/matrix-android-sdk/pull/467
- [x] KeysBackup: import change from https://github.com/vector-im/riot-android/pull/3127
- [ ] Code cleanup
- [x] Merge branch to develop

**Comment by bmarty** [comment]
Here is the recipe so far:

- [ ] Import legacy code from Riot to RiotX
- [ ] Make the code compil once
- [ ] Migrate the network code to the new archi (Tasks, etc.)
- [ ] Migrate the realm code to the new archi
- [ ] Create services to expose crypto API (CryptoService, KeysBackupService, SasVerificationService)
- [ ] Import UI for SasVerification
- [ ] Import UI for KeysBackup
- [ ] Plug in the crypto settings in main settings screen (display info, import/export keys, etc)
- [ ] Plug in the crypto setting in room setting screen (the screen is not yet available)
- [ ] Manage crypto data from the sync 
- [ ] Send encrypted event
- [ ] Decrypt encrypted event


- [ ] Code cleanup
- [ ] Merge branch to develop

**Comment by bmarty** [comment]
Looks like the issue is fully implemented!
