### ISSUE TITLE
Increase time before timeout on login

### ISSUE THREAD

**Issue by babolivier** [vector-im/riotX-android#170]
My homeserver can sometime get slow, especially on login. Currently, I can login on Riot Android, but RiotX fails with a timeout error before the login succeeds, so I guess the solution would be to increase the time limit before aborting.

**Comment by bmarty** [comment]
I've set the connect timeout to 1 minute, I hope it will fix your issue

**Comment by babolivier** [comment]
33f8059 doesn't seem to be doing the right thing: I've uninstalled RiotX from my phone, downloaded the latest APK for develop from BuildKite, installed it, and it still timed out after 30s.
