### ISSUE TITLE
Element crashes in loop after initial sync

### ISSUE THREAD

**Issue by lub** [vector-im/riotX-android#1709]
It just brings a popup "Element (Riot.im) keeps stopping" directly after starting it

I can't even send a rageshake

It happens after login and the first-sync-progress-bar

ftr 1.0.1-dev [205646062] (F-b3287) still syncs without issues after clearinf cache

**Comment by lub** [comment]
I'm happy to gather logs via other ways, I just don't know how

**Comment by lub** [comment]
I was able to send a rageshake :)

**Comment by kannanvm** [comment]
I had issues with v1 but updating to element-dbg 1.0.1 solved it.

**Comment by ganfra** [comment]
Should be fixed in next release, it's a proguard/realm issue. Thanks for pointing!

**Comment by bmarty** [comment]
Fixed by #1766, thanks for the follow up @lub !
