### ISSUE TITLE
Requesting avatar thumbnails in Element uses wrong http "user-agent" string

### ISSUE THREAD

**Issue by andyg1001** [vector-im/riotX-android#1725]
Since the migration to Element, user avatars are now no longer shown at all, just the coloured circle with a letter in it.  Changing my own avatar from the general settings screen works in the sense that the chosen picture is updated on my parallel Linux element-desktop installation (1.7.1) but I still don't get to see it in the Android client.  I don't know if this is also true of avatars for communities/group chats, but it may be.

This is definitely a regression from the previous Riot.im client on Android - which worked perfectly in this regard.

I am connecting to our own home-server, and in case this has an impact, the home-server is not on port 443 because this is assigned to another server in our NAT.

**Comment by andyg1001** [comment]
Ok, done some research.  The issue is not the different https port, but that when the client requests "GET /_matrix/media/r0/thumbnail/..." it doesn't use the normal http-agent "Element (Riot.im)/1.0.0 (Linux; U; Android 8.0.0 ...)" but a totally different one "Dalvik/2.1.0 (Linux; U; Android 8.0.0 ...)" and this is what the firewall is blocking.

I have checked all the way through the server logs.  This is the only message that uses this alternative http-agent.  All other messages use the normal one.

Can this be changed so that it uses the normal (correct?) http-agent for this message too?

**Comment by bmarty** [comment]
We should give the user agent to Glide

**Comment by andyg1001** [comment]
Just popping by to say this has been fixed in the latest update (v1.0.2).  Thank you!

**Comment by bmarty** [comment]
Fixed by #1766, thanks for the follow up @andyg1001 !
