### ISSUE TITLE
"Voice & Video" grayed out in Settings

### ISSUE THREAD

**Issue by 2011** [vector-im/riotX-android#1733]
Just installed (first time) from F-Droid (4010000). When I go to settings, I see "Voice & Video" grayed out (one of the reasons I installed the app :) ). Can anyone explain why?

Side question - the documentation indicates that I could sign up without providing an e-mail address, but I didn't have that option. Does the documentating require updating?

**Comment by rajil** [comment]
Duplicate of #1688

**Comment by 2011** [comment]
Okay, but how do I initiate a vocie or video call (I don't see any way to do that)? I thought (possibly incorrectly) that I needed to set up "Voice & Video" before the app would let me do that. :)

**Comment by rajil** [comment]
Go to a direct message and a phone icon would appear.
