### ISSUE TITLE
element login: cannot find a valid homeserver

### ISSUE THREAD

**Issue by donpdonp** [vector-im/riotX-android#1749]
I switched from riotx to element-android and I cannot login. I use the same credentials that work on riot-web and riotx with a self-hosted synapse. After filling in id and password it says "Unable to find a valid homeserver." I went to the element-android matrix room and another person is experiencing the same problem.

**Comment by vulet** [comment]
Do you have https://matrix.org/docs/spec/client_server/latest#get-well-known-matrix-client set up on your homeserver?

**Comment by donpdonp** [comment]
That was the problem, it was checking for that file. Is there an example file I can use?
```
"GET /.well-known/matrix/client HTTP/1.0" 404 169 "-" "Element (Riot.im)/1.0.0
```

Through a Custom&Advanced setting I can set the homeserver name and Element-android does not check for the .well-known file, so that is a workaround.

**Comment by vulet** [comment]
The docs have one:
```{
  "m.homeserver": {
    "base_url": "https://matrix.example.com"
  },
  "m.identity_server": {
    "base_url": "https://identity.example.com"
  },
  "org.example.custom.property": {
    "app_url": "https://custom.app.example.org"
  }
}
```
