### ISSUE TITLE
help for RIOT-ANDROID. after the last update to ELEMENT

### ISSUE THREAD

**Issue by Violet70** [vector-im/riotX-android#1755]
Hi ... in the new version for Android (Element) the search lens in the rooms is missing.  Before I always used it but now the search command in the rooms is totally absent.  On Element Desktop it works as usual.  Can someone help me?  Thank you

**Comment by duncanturk** [comment]
It's not implemented yet.
#47 is what you want.

**Comment by Violet70** [comment]
> Non è ancora implementato.
> [# 47](https://github.com/vector-im/riotX-android/issues/47) è quello che vuoi.

Thanks so much.  So do I just have to wait for the next update?

**Comment by duncanturk** [comment]
Yes, it will be included in a future update. But maybe not in the next.

**Comment by Violet70** [comment]
> Sì, sarà incluso in un futuro aggiornamento. Ma forse non nel prossimo.

Ok!  I thank you so much.  You have been very kind

**Comment by duncanturk** [comment]
No problem, thanks for supporting Element!
You may close this issue now since it's covered by #47.

**Comment by Violet70** [comment]
> Nessun problema, grazie per supportare Element!
> È possibile chiudere questo problema ora poiché è coperto dal [numero 47](https://github.com/vector-im/riotX-android/issues/47) .

Ok
