### ISSUE TITLE
Unable to send message in encrypted rooms

### ISSUE THREAD

**Issue by TheJJ** [vector-im/riotX-android#1771]
In some encrypted chats, no messages can be sent. The text stays red and at the bottom of a room.

Element-Android can read messages successfully that were sent by Element-Desktop in the same room.

The "helpful" error message is "Unable to send message".

In `adb logcat` there's no obvious further information.

**Comment by chris-dk** [comment]
Same for me, cannot write any messages in rooms. If I long press on my message there is always the status still sending. Writing in 1on1 encrypted chats is working flawless.
Using the the newest version of the self hosted Synapse homeserver.

**Comment by TheJJ** [comment]
**Clearing the cache** (Settings - General - Clear cache) has resolved this for me! Yay, now Element Android is finally usable again.

**Comment by TheJJ** [comment]
This seems to be a dup of #925
