### ISSUE TITLE
Speaker phone always on when calling

### ISSUE THREAD

**Issue by Rares95** [vector-im/riotX-android#1788]
For some phones the phone always sets itself for speaker when picking up. This should be an option somewhere...

**Comment by meyerrj** [comment]
This is related to #1688 I think...

On my device and a friend's, it defaults to the normal phone speaker, not the speaker phone, which is a small annoyance every time a video chat is initiated.

**Comment by Rares95** [comment]
Yes it is, it's the same for me. On my phone it defaults to normal speaker, on my friend loudspeaker, no matter if they call me or i call them... Also when they have headphones on it does it

**Comment by 532910** [comment]
a dup of #1685

**Comment by Rares95** [comment]
Duplicate issue
