### ISSUE TITLE
Popup when getting called only allows from dismissing the call

### ISSUE THREAD

**Issue by Rares95** [vector-im/riotX-android#1790]
![IMG_20200722_192400](https://user-images.githubusercontent.com/2606875/88215479-fef85800-cc5b-11ea-90b6-2fecdf58b393.jpg)

When getting called on Android this pops up. I can only hang-up though, not answer from it, which is very frustrating. I can only answer from the Notification area...

**Comment by 532910** [comment]
dup of #1753

**Comment by Rares95** [comment]
Duplicate issue
