### ISSUE TITLE
Notifications are disabled for this session after update to Element

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1801]
I've already enabled `notifications for this session` on 3 phones after update from Riot to Element. All three were samsungs.

**Comment by nakal** [comment]
The update seems to break notifications for every phone. Try to deinstall and install again. It fixed all notification issues for me.

**Comment by 532910** [comment]
> The update seems to break notifications for every phone.

This is false.

> Try to uninstall and install again.

The workaround for this issue is goto settings and enable `notifications for this session`.

This issue is not about breaking notifications, this issue is about breaking user experience.

**Comment by nakal** [comment]
> This issue is not about breaking notifications, this issue is about breaking user experience.

Ok, but for my case, even after enabling notifications in the settings manually, they haven't worked.

**Comment by jellykells** [comment]
I've also had to re-enable notifications for my device and the devices of a few users who updated. All devices previously had notifications enabled and working before the Element update.

**Comment by 532910** [comment]
Yep, looks like a dup of #1723
