### ISSUE TITLE
encrypted DMs stop working

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#1804]
This was on a new install of Element-Android 1.0 from F-Droid. Could not sent any message in encrypted DMs "Unable to sent message".

After clearing cache it works again. Sending messages in a newly created encrypted room (with the same people where DMs weren't working) did work the whole time. Element-web also worked the whole time.

@ganfra picked this out from the rage-shake: 
```
Tag: ## CRYPTO | encryptEventContent() : Unable to encrypt Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.
```

**Comment by TheJJ** [comment]
I guess this is #1771

**Comment by BillCarsonFr** [comment]
Closed this one and reopen https://github.com/vector-im/riotX-android/issues/925
