### ISSUE TITLE
Unread v4 rooms don't go away from home page when opened

### ISSUE THREAD

**Issue by tulir** [vector-im/riotX-android#181]
vector-im/riot-android#3187

**Comment by Half-Shot** [comment]
And v5 rooms. Because noitfs are stuck. It is *very* annoying not to be able to mark rooms as read.

**Comment by tulir** [comment]
Just to be clear: at least riot android is doing it completely wrong. You don't check event ids with a regex, you simply accept anything and url-encode when used in paths. I'm guessing riot x is currently doing it equally wrong.

Please fix this properly rather than again hacking in support for v4 ids.

**Comment by BillCarsonFr** [comment]
Can you provide step to reproduce? i am not able to reproduce it.
Is it related to eventID check?

**Comment by BillCarsonFr** [comment]
if the last events are collapsed state events I can see that the read receipt is not correctly updated (will be updated only if item is expanded), looking at this

**Comment by tulir** [comment]
Looks like it was again hackily patched for v4 ids a week ago, so technically this issue is resolved: https://github.com/vector-im/riotX-android/blob/develop/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/MatrixPatterns.kt#L42-L52

Not yet hackily patched in riot-android, so vector-im/riot-android#3187 is still relevant: https://github.com/matrix-org/matrix-android-sdk/blob/develop/matrix-sdk-core/src/main/java/org/matrix/androidsdk/core/MXPatterns.java#L50-L56

The problem is you're using regexes for validating event IDs, which you're not supposed to do. They're opaque strings. Your v1 event ID regex (`[A-Z0-9]+`) is wrong because it breaks if someone uses event ids with other characters (e.g. ponies.im). Using a regex for detecting event IDs within text is less bad, though I think even that is mostly unnecessary (if you see https://matrix.to/!room/$anything, you don't really need to check the format of `anything`, just use `\$[^\s]+` or something similarly permissive as the regex).

The specific problem: [Here](https://github.com/vector-im/riotX-android/blob/22c005d05a84324d9653d39c78a291de389789d3/matrix-sdk-android/src/main/java/im/vector/matrix/android/internal/session/room/read/SetReadMarkersTask.kt#L57) you use [isEventId](https://github.com/vector-im/riotX-android/blob/104ffc930dbdba2a40f16d1133f255d28d402bbb/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/MatrixPatterns.kt#L125-L130) to set the read marker. If someone is using custom event IDs or if the event id format changed in a new room version (as they did in v3 and v4), your code breaks for absolutely no good reason until you get around to patching it. If you call the set read markers function with an event id from an event's `event_id` field (as I assume you always do. Why would you ever read anything except a normal event with a trustworthy `event_id` field?), just trust that it's valid, you don't need to do unnecessary validations because that will break and has broken already three times (ponies.im custom v1 event ids, v3 event ids, v4 event ids)

**Comment by BillCarsonFr** [comment]
Thx tulir

**Comment by BillCarsonFr** [comment]
I wonder why this test is made, laybe for local echo :/, will test.
