### ISSUE TITLE
Key backup status

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1816]
Please add support to show if Key backup is configured, same as web version:
![image](https://user-images.githubusercontent.com/14617699/88494667-b4f6d580-cfbf-11ea-8427-1a4500fbfe84.png)

as now it looks so:
![image](https://user-images.githubusercontent.com/14617699/88494687-c63fe200-cfbf-11ea-9b38-ba3b992a0c9b.png)

**Comment by ralaud** [comment]
I did  configure my key in web client and then on android, for me it is showing this;

![IMG_20200727_040400.jpg](https://user-images.githubusercontent.com/27868982/88496824-d9e24d00-cfad-11ea-8c41-054d9752f8f3.jpg)

**Comment by BillCarsonFr** [comment]
You can manage the backup with this option 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/9841565/88524399-8dbcfa00-cff9-11ea-9848-2c7af8662844.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/9841565/88524475-a5947e00-cff9-11ea-95d3-dbc6098c7db3.png">

**Comment by 532910** [comment]
see #1820
