### ISSUE TITLE
Restricted messages (message power levels)

### ISSUE THREAD

**Issue by TR-SLimey** [vector-im/riotX-android#1824]
This was discussed a while ago on one of the Riot/Element chatrooms and recently a friend mentioned this feature so I thought I'd suggest it. The idea is that some messages in a room could be exclusively visible to users with a certain power level. This could be used to get the attention of room administrators when a user is breaking rules without that user realising, for example. This functionality could also be extended to allow showing messages to certain users exclusively. This would be a good alternative to DMing users from public chat rooms while seeking assistance etc.

As for the implementation, this could be done by sending a special e2ee message and only sending the keys to the users allowed to see it, or by trusting homeservers to only deliver the message to authorized users, but this seems very insecure.

**Comment by BillCarsonFr** [comment]
Hello @TR-SLimey , this is more a matrix spec issue, and belongs to https://github.com/matrix-org/matrix-doc
Take a look at this issue https://github.com/matrix-org/matrix-doc/issues/482
