### ISSUE TITLE
Element crashes on iPhone7 iOS 13.6

### ISSUE THREAD

**Issue by ajruwe** [vector-im/riotX-android#1825]
Hi element (riot.im) crashes also in loop (each 24 Hours) on iPhone 7. the only thing that helps is to uninstall and once again to install the app.

**Comment by 532910** [comment]
use https://github.com/vector-im/riotX-ios instead

**Comment by BillCarsonFr** [comment]
it's https://github.com/vector-im/riot-ios no X yet ^^
