### ISSUE TITLE
A user renaming themselves will increase the number of people in the room when searching for rooms

### ISSUE THREAD

**Issue by Rares95** [vector-im/riotX-android#1830]
![image](https://user-images.githubusercontent.com/2606875/88654919-4bb1b800-d0ce-11ea-85f4-f5ddfe6e4d67.png)
![image](https://user-images.githubusercontent.com/2606875/88654992-684df000-d0ce-11ea-9ac2-47e801fd7b8e.png)

As the title says, every time a user renames themselves, it increments the total people show in the Explorer by 1. Also on Desktop.

**Comment by BillCarsonFr** [comment]
I think user that left are also counted, not sure it's a client issue

**Comment by BillCarsonFr** [comment]
Closed as it's serve side, please see https://github.com/matrix-org/synapse/issues/1294
