### ISSUE TITLE
Ban shows up as user banning themself

### ISSUE THREAD

**Issue by Freakmiko** [vector-im/riotX-android#184]
![grafik](https://user-images.githubusercontent.com/2048635/59550633-2c5cd780-8f6d-11e9-99ce-4a5568699c96.png)

As seen in the above screenshot, the ban shows Matthew banning himself, which confused me for a second.  I saw this in the Matrix #matrix:matrix.org room ([perma](https://matrix.to/#/!QtykxKocfZaZOUrTwp:matrix.org/$15605846301168992orvrl:matrix.org?via=matrix.org&via=half-shot.uk&via=privacytools.io))

Seen on RiotX 0.1.0-190

**Comment by bmarty** [comment]
Thanks for reporting, we will fix that!
