### ISSUE TITLE
Compose field grows without bound

### ISSUE THREAD

**Issue by Skirmisher** [vector-im/riotX-android#1840]
The message composer in rooms does not scroll, and instead grows to fit the size of the message. With very long messages (e.g. after pasting a large volume of text), this causes the field to go off-screen under the room header, with no way to directly access the text at the top.

In the image below, the field takes up the entire screen between the keyboard and the header. There is a line of text under the header; the green text cursor is in that line of text (done by tapping elsewhere in the text and then dragging it up). The sliver of a white circle in the top-right is the "return to bottom" button, cut off by the status bar (cropped out in this screenshot).

![Screenshot_20200729-105258_Element_(Riot im)_1](https://user-images.githubusercontent.com/1535247/88840819-e7582c80-d191-11ea-8e5e-f753de6f8834.png)

**Comment by BillCarsonFr** [comment]
fixed on 1.0.1
