### ISSUE TITLE
Flair is grayed out in Settings 

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1852]
The same as #1733

![Screenshot_20200731-122751_Element_(Riot im)](https://user-images.githubusercontent.com/14617699/89021700-a1ce6780-d329-11ea-9f53-561cfc615ecd.png)

**Comment by BillCarsonFr** [comment]
Yes flair settings are not yet implemented. Should probably remove it until done

**Comment by bmarty** [comment]
Done in #1867

**Comment by 532910** [comment]
Fixed, thank you!
