### ISSUE TITLE
What does exclamation mark mean?

### ISSUE THREAD

**Issue by 532910** [vector-im/riotX-android#1855]
![image](https://user-images.githubusercontent.com/14617699/89101994-c56ade00-d40d-11ea-87d5-813487584410.png)

**Comment by 532910** [comment]
And the same on the other end:
![image](https://user-images.githubusercontent.com/14617699/89102107-a882da80-d40e-11ea-9712-387ad3915b06.png)

**Comment by Flam3z** [comment]
#1846
