### ISSUE TITLE
Reactions: Sort keys by time of first appearance

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#194]
From riot-web created by [jryans](https://github.com/jryans): vector-im/riot-web#9698  

...instead of by vote count.

**Comment by manuroe** [comment]
SGTM

**Comment by manuroe** [comment]
Added an [MSC comment](https://github.com/matrix-org/matrix-doc/pull/1849#pullrequestreview-244320323) to discuss whether the bundled reactions data will support this.

**Comment by manuroe** [comment]
Correct. To expand a little; that user behaviour is already fairly well engrained from usage on other platforms, and it also allows early reactors (including the message sender themselves) to instigate what reactions they want to see more of— e.g. 🍾 on announcements. 

That, plus the current functionality of reactions dancing around your screen as you interact with them is unexpected and pretty frustrating.

There could be an argument for sorting by number of reactions when viewing older messages, but (a) that might break the 'storytelling' aspect of choosing what order to send reactions and (b) it makes it more complicated than it needs to be— figuring out the heuristics for when to switch e.g. after an amount of time, but only on timeline load so existing reactions don't unexpectedly change sort order etc so I'd prefer to look at that as a future refinement, if at all.

**Comment by manuroe** [comment]
I think @nadonomy's argument was that it's less surprising, allows you to build "messages" out of the emoji ordering (like 🛫🇬🇧🛬), and it means the emoji key won't move out from under you when you increment it.

Is that correct @nadonomy?

**Comment by manuroe** [comment]
Are we certain we want this? Isn't vote count more informative?

**Comment by BillCarsonFr** [comment]
Already the case in RiotX
