### ISSUE TITLE
Reactions: Show at most N keys

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#195]
From riot-web created by [jryans](https://github.com/jryans): vector-im/riot-web#9570  

To avoid showing potentially 100s of reaction keys (where a "key" is a single emoji that many may have sent in aggregate, not a single vote) on a single message, we will limit to at most N keys. (This is intentionally written as just a limit without any sorting implied. See https://github.com/vector-im/riot-web/issues/9698 for sorting.)

For all rooms (unencrypted and encrypted), the client will show at most N keys inline with the message, and then add a "view more" disclosure to see the rest if there's more than that.

We're currently thinking N will be 8.

**Comment by BillCarsonFr** [comment]
Limited to 8 on riotX
