### ISSUE TITLE
Design for setting root screen

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#219]
Here is what we have so far (not on develop yet):

<img width="232" alt="image" src="https://user-images.githubusercontent.com/3940906/60086073-bd386d80-973a-11e9-88dc-9ea10c0ae5fb.png">

**Comment by nadonomy** [comment]
Added a comp (with exportable icons) from what I can see in this issue: https://zpl.io/2jMDpMr

If we need more master/detail views or settings components comping (toggles/inputs etc) let me know and I can add them.

**Comment by bmarty** [comment]
Fixed by #228
