### ISSUE TITLE
m.notice messages trigger push notifications

### ISSUE THREAD

**Issue by turt2live** [vector-im/riotX-android#238]
Suddenly I'm getting notifications for #matrix-spam:matrix.org and #riot-spam:matrix.org only on RiotX. My push rules should be preventing this.

**Comment by richvdh** [comment]
I'm suffering this too.

**Comment by bmarty** [comment]
Seems that we finally find the root cause of this (https://github.com/vector-im/riotX-android/commit/a4af6c1c99c0b9182fc4d906941c8338d796b41a)

**Comment by bmarty** [comment]
Fixed in #573
