### ISSUE TITLE
Room list (# tab) should be ordered by tag order and recent activity

### ISSUE THREAD

**Issue by turt2live** [vector-im/riotX-android#245]
I can't figure out how my favourites are ordered, but they aren't ordered correctly at all. As for the rest of the rooms: they're alphabetical, which is useless to me as someone with thousands of rooms. 

I'm more likely to miss messages now on RiotX because I don't have notifications enabled for most rooms, and the room list is not ordered by most recent rooms.

**Comment by tulir** [comment]
Both favorites and other rooms are ordered alphabetically, where Z > a.

This is the main blocker for me switching to Riot X (though room list searching would be nice too).

**Comment by fbruetting** [comment]
Guess that can be closed?

**Comment by turt2live** [comment]
oh, yes, indeed! Good catch.

**Comment by tulir** [comment]
Favorites still don't seem to be ordered by tag order

**Comment by turt2live** [comment]
personally I feel that's better for the mobile use case

**Comment by fbruetting** [comment]
Tag order is something more advanced and just confuses the regular dumb user. I’d file a separate feature request for that and close this.
