### ISSUE TITLE
long nickname message source cannot be view

### ISSUE THREAD

**Issue by grinapo** [vector-im/riotX-android#249]
If the nickname is too long the long-click window is missing the actual buttons, it's outside of the sceen.

![IMG_20190630_102016](https://user-images.githubusercontent.com/1056054/60395010-36660500-9b2d-11e9-8e6f-a7a575c223e3.png)

**Comment by bmarty** [comment]
Thanks fir feedback. Actions are not display for some event, we will handle it (like #209)

**Comment by bmarty** [comment]
It should be fixed on the last build, can you confirm please?

**Comment by bmarty** [comment]
Also this is displayed when the event is not sent yet. We should add a loader when this is the case

**Comment by grinapo** [comment]
> It should be fixed on the last build, can you confirm please?

It is fixed as far as my observations go. Thanks!

**Comment by bmarty** [comment]
Cool thanks!
