### ISSUE TITLE
Logging in on big accounts (e.g. mine) is unreliable

### ISSUE THREAD

**Issue by ara4n** [vector-im/riotX-android#270]
It feels like it's not retrying when there's a timeout to /sync.

**Comment by BrainBlasted** [comment]
I can confirm this. RiotX hovers at the "Importing account" stage for  a long time:

![](https://i.imgur.com/PNHtVCg.png)

I haven't gotten it to finish, and I've left it running in the background for hours.

**Comment by bmarty** [comment]
Is is better on the latest version of the app?

**Comment by bmarty** [comment]
Please re-open the issue if it's not better
