### ISSUE TITLE
Soft logout

### ISSUE THREAD

**Issue by turt2live** [vector-im/riotX-android#281]
see https://github.com/vector-im/riot-meta/issues/239 for the spec and how to test it.

- [x] SDK: Handle new CS API error code
- [x] Show the login page on soft logout without loosing user data
- [x] Rehydrate session reusing `device_id` and restart
- [x] Cache the softLogout state to display the login page directly on startup
- [x] Implement the login UX (https://zpl.io/a89QL5x)
- [x] Detect if all keys are backed up and use the right UX ^
- [x] "Clear all data" button
- SSO support: #430

**Comment by bmarty** [comment]
Fixed by #768
