### ISSUE TITLE
Room upgrade: Use the `server_name` parameter when joining the new room

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#303]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2550  

The client just needs to send a `server_name` alongside the join call to the new room. Convention is to use the tombstone event sender's server name.

Web PR: https://github.com/matrix-org/matrix-react-sdk/pull/3159

Discussion: https://matrix.to/#/!zVpPeWAObqutioiNzB:jki.re/$cKuuTGJdMD9lVWAUDRl9Tln1Ol1APbwJO1G6C2HtO6U?via=matrix.org&via=librepush.net&via=sw1v.org

**Comment by manuroe** [comment]
Riot-android issue: https://github.com/vector-im/riot-android/issues/3204

**Comment by ganfra** [comment]
Handled by https://github.com/vector-im/riotX-android/pull/449
