### ISSUE TITLE
Improve fullscreen media display

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#327]
Especially using full immersive mode when available

- [ ] Should display image (gifs?) and video
- [ ] Seamless animation from chat to full screen (shared element transition)
- [ ] Swipe left/right to see previous/next media in timeline
- [ ] Swipe Up/Down to dismiss
- [ ] Video should have play/pause control and media progress indicator
- [ ] Option menu to share / save
- [ ] Translucent top bar with basic info (sender / date / reactions)
- [ ] Single tab to toggle topbar visibility
- [ ] Double tap image to toggle max/min zoom
- [ ] pinch to zoom in/out
- [ ] Should support not yet downloaded / downloading media
- [ ] PIP mode for video?

**Comment by violoncelloCH** [comment]
also it would be nice, if one would be able to swipe in the image display view to go to the next / previous image/media element (if present in the room history)

**Comment by Medath** [comment]
To add on the suggestion of @violoncelloCH , it would be great if swiping up or down would bring you back to the chat screen (so you don't have to press the back button). Swiping left/right could still be used to browse previous/next media

**Comment by Destroyer** [comment]
any plans to at least add image zoom? it's really annoying because you can't save an image to the internal memory nor zoom, which makes sending big images/screenshots completly useless

**Comment by lub** [comment]
@Destroyer Did you happen to try it in unencrypted rooms? Because pinch to zoom should normally work (see #75). I've opened #1123 for e2ee rooms, because there it doesn't work for me.

**Comment by Destroyer** [comment]
I haven't because I use riotx e2e DMs 99% of the time, but you're competly right, it works for me in non-e2e rooms.

**Comment by rajil** [comment]
"Video should have play/pause control and media progress indicator", would be quite useful. There is no way to move back in the video.

**Comment by TR-SLimey** [comment]
Can we also add #1540 here?
