### ISSUE TITLE
Implement 'Jump to first unread message' feature in rooms using m.fully_read marker

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riotX-android#328]
Seems at now RiotX miss `Jump to first unread message` feature, that scroll room timeline to first unread message. This is very important feature for most of users, especially in rooms with many members. Also `X` action for mark all as read.

I can't find issue about implementing this feature, only about displaying read markers #84 in phase2. But displaying markers is not so important comparing to `Jump to first unread message` feature.

For implement jumping we can use `m.fully_read` marker from spec https://matrix.org/docs/spec/client_server/r0.4.0#fully-read-markers

So I suggest to implement `Jump to first unread message` earlier, than displaying read markers.

**Comment by MurzNN** [comment]
Ow, I look at wrong place https://github.com/vector-im/riotX-android/projects/1
Phase0 is finished, Phase1 is almost too: https://github.com/vector-im/riotX-android/milestones

**Comment by vc7ee** [comment]
Note: some users prefer to jump to first, without losing their last read position (read few first unread, then jump back to their last position)

**Comment by vc7ee** [comment]
Addition to ny comment: In discord I hate when I reply to someone, after sending the message, it automatically moves me to the bottom. RiotX already opens a new page what you can close with x, when you click jump to 1st.

**Comment by bmarty** [comment]
Related to #84

**Comment by bmarty** [comment]
-> next sprint

**Comment by progserega** [comment]
"Jump marker" some times freeze:

Video:
https://yadi.sk/i/qq-2DY3YCAAunQ

RiotX version: 0.7.0 G-b1099

**Comment by MurzNN** [comment]
Same problem for me with unmarkable as read messages sometimes. Workaround is scroll down to next messages (for hide problematic message) and use "jump to unread"
