### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#34]
Add support for account registration
- [x] Get Login Flows
- [x] Captcha step
- [x] Terms step (view terms in browser)
- [x] 3pid step
- [x] SSO (if the custom hs uses SSO, display immediately in webview)
- [x] Login fallback
- [x] Account creation fallback

Notes
- For now, for implementation ease transition screens in from the right, with the logo being a part of the scrollable view

**Comment by BillCarsonFr** [comment]
We should optimize for android O's auto fill
https://developer.android.com/guide/topics/text/autofill-optimize
