### ISSUE TITLE
Notification action: mark as read does not dismiss the notification

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#348]

**Comment by bmarty** [comment]
We can even say that the feature does not work at all

**Comment by BillCarsonFr** [comment]
I can't reproduce on my test device :/

**Comment by steef435** [comment]
On my device (Nokia 6.1 Plus, version 0.9.1 (G-b1360)), I do experience this behavior.
0. Get a message notification (see first screenshot)
1. Click on mark as read
2. The item is marked read (see disappearing notification dot app icon, but I also checked using Riot Desktop)
3. The notification disappears
4. Instantly, a new notification pops up. This skips the first line of the message and does not have any actions attached (see second screenshot)

Is there any more info I can provide?

[Screenshot 1](https://user-images.githubusercontent.com/1906214/70395065-5a424680-19fb-11ea-8536-e4ce1a0ae181.png)
[Screenshot 2](https://user-images.githubusercontent.com/1906214/70395071-5f9f9100-19fb-11ea-9c81-3553bd0d3e1f.png)
