### ISSUE TITLE
Username|Email address at login screen

### ISSUE THREAD

**Issue by adwaitrawat** [vector-im/riotX-android#354]
At the login in screen the app asks for the username, but I don't have a username and login using the email address. 

So I think it would be appropriate to write "username|email address" instead of just username, since I successfully logged in using the email address in the username field. Or make a different tabs for logging in using the username and email.

Which ever is easier for the developers.

**Comment by vc7ee** [comment]
also: old app has un&email or phone, combine them please! If user does not enter country code, after pressing log in, try to guess the location based on ip, if login fails, ask the user.

Me: "I don't know if I should make an issue out of it, but make sure the phone number, u/n and email field is the same. I had a person enter both their u/n and phone on the app and not being able to log on bc the phone number was not registered to any acc (while after clearing the phone field, it worked)..."

**Comment by bmarty** [comment]
@nadonomy what do you thing about the "Username" hint? Entering an email is working too.

![image](https://user-images.githubusercontent.com/3940906/71170057-aa6ea380-225a-11ea-9d9e-d84b69a28670.png)

**Comment by nadonomy** [comment]
@bmarty so presently both username and email work in the input? If so then changing the hint to "Username or email" is a no brainer.

Re signing in by phone number, is that supported? At some point we'd discussed letting the user input any of user/email/phone into a single input field but I can't recall where we got to with it.

**Comment by bmarty** [comment]
Yes, entering an email also work. So, I will update the wording to "Username or email". For phone number we will discuss it later. Thanks!

**Comment by bmarty** [comment]
Wording updated in 13439769a1cd51619dd5bde68cd0ecad3ad40958
@jtagcat could you please open a dedicated issue for your concern? Thanks
