### ISSUE TITLE
Emoji verification name discrepancy between riot-web and riotX

### ISSUE THREAD

**Issue by z3ntu** [vector-im/riotX-android#355]
Riot web:
![image](https://user-images.githubusercontent.com/3768500/61173765-2a039280-a598-11e9-9905-f34f66b82c2b.png)
Riot X: 
![image](https://user-images.githubusercontent.com/3768500/61173784-5e774e80-a598-11e9-80de-2bef29b3023e.png)

**Comment by ara4n** [comment]
wrench is US english; spanner is UK english. what locales are the apps in?

**Comment by z3ntu** [comment]
My phone is in "English (United States)" and secondary language "German (Austria)" and my PC is
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE=C
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
$ echo $LANGUAGE
eo:en_US
```
so both should use US English

**Comment by bmarty** [comment]
Thanks @z3ntu , it should be fixed in the next release of Riot-Android and of RiotX
