### ISSUE TITLE
Preformatted text is not shown in a monospace font

### ISSUE THREAD

**Issue by dov** [vector-im/riotX-android#356]
Neither verbatim text in an unspecified source language nor verbatim text in which the syntax is specified is shown in a monospace text as expected, and as is done in the web client.

Consider the following messages:

```json
{
  "content": {
    "body": "`‍`‍`\nSome verbatim text in an unspecified syntax.\n``‍`‍",
    "format": "org.matrix.custom.html",
    "formatted_body": "<pre><code>Some verbatim text in an unspecified syntax.\n</code></pre>\n",
    "msgtype": "m.text"
  },
«stuff deleted»
}
``
and

```json
{
  "content": {
    "body": "``‍`python\n# A comment\na = 'The quick'\nfor c in list(a):\n  print(c)\n``‍`",
    "format": "org.matrix.custom.html",
    "formatted_body": "<pre><code class=\"language-python\"># A comment\na = 'The quick'\nfor c in list(a):\n  print(c)\n</code></pre>\n",
    "msgtype": "m.text"
  },
 «stuff deleted»
}
```
(**Note:** if copying the above code that I inserted a ZWJ character between some of the backticks to inhibit markdown interpretation of the tripple backticks.)

that are shown as follows:

![foo](https://user-images.githubusercontent.com/338235/61175987-36e8ac00-a5c1-11e9-8089-0c9f858de769.png)

Version is 0.1.0 (G-52dced43)

**Comment by bmarty** [comment]
Related (but created before) #567

**Comment by bmarty** [comment]
Done in #654
