### ISSUE TITLE
If a word contains a username, it triggers a notification

### ISSUE THREAD

**Issue by qazip** [vector-im/riotX-android#359]
Annoyingly, If a word contains a username, it triggers a notification. Example:

My username is fortu. If someone types "fortunately", I'll be notified of that message.

**Comment by BillCarsonFr** [comment]
I just tried to unit test it and the ContainsDisplayNameCondition is not triggered in this case. :/
Could it be possible that it's another rule that triggers the notification?

Can you provide some more details, and way to reproduce?
Thanks!

**Comment by tulir** [comment]
Happens for me on build 0.2.0 (G-7e3b3001) / sdk 0.0.1 (7e3b3001).

> ContainsDisplayNameCondition

Maybe it's the username (mxid localpart), rather than displayname?

![image](https://user-images.githubusercontent.com/4224639/61444843-e1135b80-a954-11e9-81d0-2c61f0e8604f.png)

**Comment by qazip** [comment]
@BillCarsonFr, this is still happening to me. No news?

**Comment by ZerataX** [comment]
This happens for me with the keywords I've added.
