### ISSUE TITLE
reply is main feature in long tap menu list

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#368]
Mostly used feature is "reply", but first and second in menu is reactions, only then is "reply".

![Screenshot_20190715-220841](https://user-images.githubusercontent.com/1297163/61217575-53b4e900-a753-11e9-91ec-1e5dea6436a6.png)

I think "reply" need put at top of menu.

**Comment by progserega** [comment]
Also "Reply" near "return" button - and it is simply tap on "return", when try tap on "reply".

I think it is more nicely if menu will be such:

=======================
1. reply
2. copy                                      (this is see without need scroll menu)
3. Quick Reactions
4. Add reaction
=======================
5. quote
6. link                                          (this see after scroll menu)
7. report content
8. view source
========================

**Comment by bmarty** [comment]
And the quick reaction area is maybe too big, with a useless title. We will discuss this internally, thanks
