### ISSUE TITLE
tap on message - enable reply

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#369]
In old Riot-android - when user tap on message - all other messages will hided and edit dialog change background text to "reply". And if user type text and sending it - it is reply to selected message.
It is very nicely feature in old Riot. Reply - is most useed function. It is very nice, when mostly used function user can use by minimal click.
I hope this nice function also will be implemented in RiotX. :-)

**Comment by tulir** [comment]
Related to  #167

**Comment by bmarty** [comment]
We will implement #167 :)

**Comment by progserega** [comment]
Thank you!
