### ISSUE TITLE
RiotX use more energy even old Riot

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#376]
I was disable getting push events to RiotX (in RiotX settings), because I use video/voice calls. And I need receive push events about voice-call in old Riot.
But anyway with disabled push events, RiotX use network (3 hour and 39 minutes) and use more energy:

![Screenshot_20190716-201115](https://user-images.githubusercontent.com/1297163/61286576-7d7b1800-a806-11e9-8962-0aaa133fb1f9.png)
![Screenshot_20190716-201124](https://user-images.githubusercontent.com/1297163/61286590-82d86280-a806-11e9-9189-b8a2f4a76f81.png)
Why RiotX use network, when it must be sleep, while waiting push event?

**Comment by vc7ee** [comment]
*here comes ~~messenger~~ riot light* **don't ever do that**
![image](https://user-images.githubusercontent.com/38327267/61291835-230a9900-a7bf-11e9-85e9-dcf282970171.png)
*I'll provide a screenshot of my full system usage in few days, I just charged my phone to 100% :/*
