### ISSUE TITLE
Handle long click on room in the room list

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#395]
To display a bottom sheet, as we do on long click on message with possible action for the room.

It could be interesting to add an item at the bottom of a non empty room list to inform the user that there is action behind a long click. Suggested wording: "Long click on a room to see more options". This item could be hidden after the user has done the gesture once.

Currently in RiotWeb, we have:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/3940906/61475645-919c5200-a98b-11e9-9ebd-9f6df92bbc5f.png">

Also in Riot Android, we have an option to add the room to the mobile Home, as a shortcut.

**Comment by rkfg** [comment]
Is it not possible currently to leave a room in RiotX? I couldn't find that.

**Comment by bmarty** [comment]
No, not yet

**Comment by nadonomy** [comment]
Hey @bmarty, I've been looking at this in closer detail, and think the best thing to do would be to implement:

- Notification settings (Noisy / All / Mentions / Mute)
- Leave
- Settings

![Comp](https://user-images.githubusercontent.com/4626865/62586630-374c2e00-b873-11e9-8895-d595f17ee5f1.png)

So I've prepared icons for these here:

[riot-x-long-press.zip](https://github.com/vector-im/riotX-android/files/3474729/riot-x-long-press.zip)

I'm apprehensive to spend development time implementing Favourite, Low Priority or Direct Chat as they'll change in the not-far future as we work on Communities & Immutable DM's. Do you agree? Or would you prefer to implement them now for legacy parity, even if they turn out to be short lived?

**Comment by bmarty** [comment]
Thanks @nadonomy for the design, Ok to postpone "Favourite, Low Priority or Direct Chat"

**Comment by frandavid100** [comment]
"Also in Riot Android, we have an option to add the room to the mobile Home, as a shortcut".

Why not show favorited rooms in Home, instead of having a separate option for that?

**Comment by andycuccaro** [comment]
> Why not show favorited rooms in Home, instead of having a separate option for that?

That would be really convenient! I'd hope it ends up  being just like that.

**Comment by bmarty** [comment]
@nadonomy it's maybe a good idea to add a header to the bottom sheet with room avatar and name, as we do for bottom sheet of messages, what do you think?

**Comment by nadonomy** [comment]
Yeah that sounds good, to re-enforce the context.

**Comment by nadonomy** [comment]
@ganfra I've uploaded the artboard to Zeplin here, and also added a green check mark to show which notification setting is active:

https://zpl.io/a3dOWx1

I looked into adding an empty SVG node to standardise the size but then SVGO was stripping it on export. If the icon sizes are still problematic to work with when exporting from Zeplin let me know and we can figure something out.
