### ISSUE TITLE
"Mark all as read" option

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#396]
All rooms marked as read in one click.

On Riot Android, this is an option in the top right menu in the home

**Comment by nadonomy** [comment]
I think the most appropriate place to put this would actually be the top right menu:

![Screenshot_20190807-025643](https://user-images.githubusercontent.com/4626865/62586747-bccfde00-b873-11e9-9783-b19b3267c6d2.png)

Labelled as 'Mark all as read'.

As we develop the home screen we might want to consider having swipe gestures (similar to email apps like Mailbox, Google Inbox, etc) to mark as read, but I'd be hesitant to execute on any of that now until we further dogfood and iterate on things like https://github.com/vector-im/riotX-android/issues/171.
