### ISSUE TITLE
RiotX gets confused about the edited in an edited edited!

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/riotX-android#398]
To reproduce, send a message containing the string `*edited*`, edit this message and watch this happen:

![Screenshot_20190718-230121](https://user-images.githubusercontent.com/77743/61491733-2d3fb980-a9b0-11e9-9753-619544e40fd7.png)

(The first occurrence of "(edited)" is highlighted and linkified instead of the second one)

**Comment by BillCarsonFr** [comment]
Nice catch! thanks, fixed

**Comment by bmarty** [comment]
FTR c00dbce536a90f162831e57ccb23fb5f499d0252
