### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#40]
Settings screen
- [ ] User profile
- [ ] Local contacts
- [ ] User interface
- [ ] Home display
- [ ] Flair
- [x] Notifications
- [ ] Calls
- [ ] Ignored users
- [ ] Labs
- [ ] Crypto
- [ ] Crypto keys management
- [ ] Device
- [ ] Advanced
- [ ] Analytics
- [ ] Other
- [ ] Deactivate account

**Comment by PolynomialDivision** [comment]
Can u make the F-Droid build without analytics until you can disable it?

**Comment by bmarty** [comment]
I close this issue, will create issue dedicated to what is missing (or they already exist).

> Can u make the F-Droid build without analytics until you can disable it?

There is no analytics in Element
