### ISSUE TITLE
Add an item "View edit history"

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#401]
In the bottom sheet of any edited message.
Because the click on `(edited)` can be hard to discover

**Comment by nadonomy** [comment]
Needs an icon & to confirm where in the bottomsheet we display it.

**Comment by nadonomy** [comment]
Just checked production:

![Screenshot_20190807-020456](https://user-images.githubusercontent.com/4626865/62585493-ec7be780-b86d-11e9-9e23-38d8661917c9.png)

And I think the most sensible place to put it would be before View Source. I just drew this icon for us to use:

[view-edit-history.svg.zip](https://github.com/vector-im/riotX-android/files/3474653/view-edit-history.svg.zip)

@manuroe do you want to echo this issue on iOS? If so, pls tag me there and I'll adjust the stroke widths for that platform.

**Comment by bmarty** [comment]
Here what I've done so far (PR is coming)

<img width="635" alt="image" src="https://user-images.githubusercontent.com/3940906/62617835-176c4700-b913-11e9-8e51-2975dfef3a8e.png">

**Comment by bmarty** [comment]
Done in #466
