### ISSUE TITLE
Check clear cache function

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#408]
It seems that the initial sync is not done after a clear cache, or the DB is not well cleared...

**Comment by MurzNN** [comment]
Confirm issue, after clearing cache all my rooms lost names and will not reloaded.

**Comment by PatrickRose** [comment]
Can also confirm:

 * Samsung S7
 * RiotX 0.2.0 - `G-df6080b1`

I also am no longer able to send a message through RiotX after clearing the cache (but I don't know if that's related, let me know the best way of helping debug that)

**Comment by ganfra** [comment]
Should be fixed now with https://github.com/vector-im/riotX-android/pull/460
