### ISSUE TITLE
edit history not show diff for first edit

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#410]
If user edit his message once - edit history not show original message and not show diff between original message and first edit.

If user do second edit - edit history show diff between first and second edit. But not show diff between original message and first edit:
![Screenshot_20190720-103256](https://user-images.githubusercontent.com/1297163/61571885-72600a80-aada-11e9-91fa-a56826003f91.png)
![Screenshot_20190720-103330](https://user-images.githubusercontent.com/1297163/61571886-72f8a100-aada-11e9-9b94-6ed65a3ae48d.png)
![Screenshot_20190720-103337](https://user-images.githubusercontent.com/1297163/61571887-72f8a100-aada-11e9-8dad-ef67fcda2d96.png)
![Screenshot_20190720-103402](https://user-images.githubusercontent.com/1297163/61571888-72f8a100-aada-11e9-80ab-ff1279c5e3ee.png)

**Comment by BillCarsonFr** [comment]
Fixed in v0.2
