### ISSUE TITLE
markdown set off by default

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#412]
Markdown is good. I like markdown. I use markdown. But many users do not understand his. They want send `1*2*3` but it broken. They try send samba url `\\host\share` - and it broken... Admins must describe to users how they can disable this feature.

I think by default we need switch off markdown for all new users. Users, which know what  is this "markdown" - will enable it in settings.

**Comment by bmarty** [comment]
I totally agree with you, markdown is hard to understand for non tech user. It has already been discussed [here](https://github.com/vector-im/riot-android/issues/2285) and [here](https://github.com/vector-im/riot-android/issues/2557).

We need to make a decision internally about this.

**Comment by bmarty** [comment]
We will disable markdown by default

**Comment by progserega** [comment]
Thank you!
