### ISSUE TITLE
Slide-in reply icon is distorted

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#423]
![](https://i.imgur.com/h3DHoDd.png)

The swipe to reply icon looks a little stretched vertically.

You can see the difference compared to the reply icon at the bottom left above the keyboard here:

![](https://i.imgur.com/Cl6QOhJ.png)

This is on a Pixel XL, Android 9.

**Comment by BillCarsonFr** [comment]
Fixed in #495 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/9841565/63230833-52f2f500-c1e0-11e9-8817-600930eea7e1.png">
