### ISSUE TITLE
Photo selector is slow to load photos, no autorefresh

### ISSUE THREAD

**Issue by jtagcat** [vector-im/riotX-android#427]
Take photo with camera app -> Go to riot -> open chat -> attach image -> the photo isn't there
How to get the photo to appear: wait 30s, go back to chat and attempt to attach image again.
The photo selector should be autorefreshing (with maybe the riot.im app loading bar indicator as well) and if it can, be faster to load images.

**Comment by bmarty** [comment]
The photo selector library has been changed by #619, and now we are using the native picker which should be more reactive
