### ISSUE TITLE
Soft logout: Support SSO auth

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#430]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2597  

Make sure we can log in back after a soft logout on a homeserver running SSO auth.
Information to test against a SSO auth homeserver is pinned in the #softlogout-dev room.

- [x] Check soft logout display on SSO
- [ ] If the hydrated user ID doesn't match the session's user ID, overwrite
- [x] Pass the `device_id` in the fallback URL we use for SSO
- [ ] Final test when `device_id` is implemented on the fallback page (blocked by https://github.com/matrix-org/synapse/issues/5755).

**Comment by bmarty** [comment]
> If the hydrated user ID doesn't match the session's user ID, overwrite 

For the moment, we only display a dialog to ask the user to first clear data before signing in to another account
