### ISSUE TITLE
Make sure there are no ugly edge cases running Riot without an integrations manager

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#431]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2518  

From riot-web created by [lampholder](https://github.com/lampholder): vector-im/riot-web#10090  

Edge cases we need to manage (display an error or hide the feature):
- integration manager screen 
- Sticker picker
- jitsi conf call

Fixed in Riot-web by matrix-org/matrix-react-sdk#3115

**Comment by bmarty** [comment]
No integration manager in RiotX for the moment
