### ISSUE TITLE
Prompt to accept integration manager polices on use

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#432]
Before you:
- [ ] add a widget to a room
- [ ] use the sticker picker
- [ ] (TODO: Check we need that on mobile) allow a widget to load for you in a room
  * This does sort of work already with https://github.com/matrix-org/matrix-react-sdk/pull/3199, but the UX is such that your are prompted when entering a room with a widget, not when allowing it to display
  * Time of prompting for existing widgets fixed by https://github.com/matrix-org/matrix-react-sdk/pull/3240

You must read and agree to the policy documents provided by the integration manager.

Spec: https://github.com/matrix-org/matrix-doc/blob/dbkr/tos_2/proposals/2140-terms-of-service-2.md
Design: https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5d14ffed0c469a50ec390c47

From riot-web created by [lampholder](https://github.com/lampholder): vector-im/riot-web#10088

**Comment by bmarty** [comment]
No integration manager for the moment in RiotX
