### ISSUE TITLE
Settings: Ability to change the identity server

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#436]
This means:

SDK:
- [ ] Store identity server in Account Data
- [ ] We should probably also validate that it's really an IS (TODO?)
- [ ] We should also somehow validate that the HS permits access to this IS if it maintains a whitelist...  (TODO?)

App:
- [ ] Settings: Add it to the new "IDENTITY SERVER" section (https://zpl.io/brMdWo3)
- [ ] When we change IS, we'll need to fetch its policy docs and capture that the user has agreed to them
- [ ] Make sure the app can run without IS

Riot-web issue: https://github.com/vector-im/riot-web/issues/10094

**Comment by bmarty** [comment]
See #607
