### ISSUE TITLE
Settings: Add a Discovery section

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#438]
That allows our user to define which 3PIDs other users can use to discover our user.
This is different from 3PIDs the user can use to log in.

Zeplin: https://zpl.io/brMdWo3

- [ ] New section
<img width="477" alt="Screenshot 2019-07-26 at 09 52 23" src="https://user-images.githubusercontent.com/8418515/61935575-16d6c680-af8b-11e9-84ea-99fded153049.png">
- [ ] Update of the existing one
<img width="475" alt="Screenshot 2019-07-26 at 09 53 18" src="https://user-images.githubusercontent.com/8418515/61935644-379f1c00-af8b-11e9-87cd-9da2aaf10608.png">

Original riot-web issue: https://github.com/vector-im/riot-web/issues/10159

**Comment by bmarty** [comment]
See #607
