### ISSUE TITLE
Event with empty json in_reply_to fails to render, should be more lax?

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#447]
Following content will not be displayed on RX (Malformed event)

```
 "content": {
    "body": "riotx message parsing is broken 3:",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>riotx message parsing is broken 3:</p>",
    "m.relates_to": {
      "m.in_reply_to": {}
    }
```

**Comment by danteissaias** [comment]
https://github.com/vector-im/riotX-android/blob/c647648e79bf4085ea4244ac1695e4a137727d5b/matrix-sdk-android/src/main/java/im/vector/matrix/android/api/session/room/model/message/MessageContent.kt#L31-L33

This function appears to be the culprit.
