### ISSUE TITLE
RiotX Does Not Show When A User Inputs Invalid Credentials

### ISSUE THREAD

**Issue by BrainBlasted** [vector-im/riotX-android#454]
The expected behavior when a user inputs the wrong username/password is that an app shows an error regarding the credentials. This does not happen for RiotX. Instead, the app continues to try it's initial sync indefinitely.

If the app is closed during the "sync" after putting in your details, it will not remember your information afterward. This means a user will need to log in again if the sync is interrupted.

**Comment by BrainBlasted** [comment]
Updated to reflect a mistake 🤦🏾‍♂️

**Comment by bmarty** [comment]
I think this is ok with the new sign in flow.
Please re-open the issue if it is not the case.
