### ISSUE TITLE
Dark mode switching orientation in chat rooms is clearing background

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#457]
Step to reproduce: Open chat room, then switch orientation,  chat room will be white text on white background

<img width="426" alt="image" src="https://user-images.githubusercontent.com/9841565/62358664-6c741b80-b515-11e9-9555-0f2993e7ac5e.png">

**Comment by bmarty** [comment]
Related to #394 ?

**Comment by bmarty** [comment]
Fix confirmed
