### ISSUE TITLE
Handle error 429 when sending message

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#462]
Example of response body:
```
{"errcode":"M_LIMIT_EXCEEDED","error":"Too Many Requests","retry_after_ms":4758}
```

Currently, the SendWorker is stuck if such error occurs.

**Comment by ganfra** [comment]
It's handled by commit d696bd2830ba72cc23f85dcda12382362cc80d40

**Comment by bmarty** [comment]
@ganfra is there a way to use the "retry_after_ms" info?

**Comment by bmarty** [comment]
Any the fix is confirmed, thanks @ganfra
