### ISSUE TITLE
Rooms without an icon with names starting with an emoji do now show the emoji in the autogenerated icon

### ISSUE THREAD

**Issue by Munfred** [vector-im/riotX-android#477]
I use Tulir's mautrix hangouts bridge, and because the bridge doesn't let me change the room icon, I devised a workaround where I add an emoji as the first charachter in the Hangouts conversation name, that gets pulled into Matrix as the room name, and the the room icon will have that emoji instead of a letter, making it easier to spot because many rooms and conversations start with the same letter and have the same color.

Unfortunately that little hack does not work with Riot X at the moment, I just get a rotated square with a ? instead, see the picture below. This is not a huge deal (and I don't know if many other people take advantadge of this) but would be nice to address at some point.

And since I'm talking about putting emojis in room icons already, I'd like to mention one idea I had been thinking about: Distinctive room icons are really useful for quickly jumping between rooms, especially when you have many of them. But lot of people don't go through the truble of changing them. It has crossed my mind that perhaps it would be interesting to allow the user to easily make an emoji the room icon (particularly for 1 on 1 conversations). This could perhaps take the form of a button that randomizes the room emoji icon or let's the user pick one. And perhaps it would be interesting to allow the user to enable random emoji icons as a default for new conversations. Just food for thought :)

Thanks! 

![image](https://user-images.githubusercontent.com/12504176/62827589-b64ca980-bb86-11e9-8f98-5bb084acb5df.png)

**Comment by bmarty** [comment]
Hi @Munfred , this will be fixed in the next release (0.11.0)!
