### ISSUE TITLE
Integration manager (Matrix app manager) and Widgets

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#48]
Some related MSC : https://github.com/matrix-org/matrix-doc/pull/1956 

### Cases to handle
 - [x] Be able to disable integration manager in settings
 - [x] Be able to show configured integration manager in settings
 - [ ] Be able to edit integration manager url => need UI
 - [x] Be able to add/delete widgets 
 - [x] Be able to display Widget in a dedicated WebView
 - [x] Be able to show room widgets in RoomDetail   => need UI/UX
 - [x] Display Widget authorization popup
 - [x] Be able to send a sticker
 - [x] Be able to accept TOS

### Android Legacy

<img src="https://user-images.githubusercontent.com/8754928/81183797-e27b4680-8faf-11ea-861d-936d94b1c258.png" width="300">

<img src="https://user-images.githubusercontent.com/8754928/81183803-e4dda080-8faf-11ea-85bc-4d9ce95724cd.png" width="300">

<img src="https://user-images.githubusercontent.com/8754928/81183808-e60ecd80-8faf-11ea-8bf0-cd5e16ac1318.png" width="300">

<img src="https://user-images.githubusercontent.com/8754928/81183809-e6a76400-8faf-11ea-93b3-bb5b636dce00.png" width="300">

<img src="https://user-images.githubusercontent.com/8754928/81183811-e73ffa80-8faf-11ea-9897-f06eb0f69251.png" width="300">

<img src="https://user-images.githubusercontent.com/8754928/81183813-e7d89100-8faf-11ea-9828-a265147e17f8.png" width="300">

**Comment by Cadair** [comment]
Please also make the URL configurable to avoid the f-droid anti-feature that riot android has. :)

**Comment by bmarty** [comment]
FTR Terms screen will be added by #1354

**Comment by bmarty** [comment]
Done in #1425
