### ISSUE TITLE
Use the hashed v2 lookup API for 3PIDs

### ISSUE THREAD

**Issue by jryans** [vector-im/riotX-android#489]
Cloned from https://github.com/vector-im/riot-web/issues/10556.

This is being specced in [MSC2134](https://github.com/matrix-org/matrix-doc/blob/master/proposals/2134-identity-hash-lookup.md).

There's a `GET /_matrix/identity/v2/hash_details` endpoint on the IS that riot can call to see which hashing algorithms the server supports - Riot should use `sha256` if the server supports it, otherwise it should use `none` if that's all the server supports (we should think about whether `none` requires any sort of special warning, though we only expect it to be used in niche cases).

**Comment by bmarty** [comment]
See #607
