### ISSUE TITLE
Event formatter

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#5]
Format matrix events into readable, internationalised messages in the timeline:
- [ ] state events:
    - [ ] membership events
    - [ ] room name change
    - [ ] room avatar change
    - [ ] ...
- [ ] bing
- [ ] UTDs (Unable To Decrypt) errors 
- [ ] This must work for last messages displayed in rooms lists.

**Comment by bmarty** [comment]
I think we can close this one
