### ISSUE TITLE
Allow | in links

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#510]
![](https://i.imgur.com/LLOadMG.png)

I sent a link with a `|` character in it and RiotX stopped interpreting it as a link at this point.

**Comment by bmarty** [comment]
This is not a valid URL, `|` should be encoded with `%7C`, shouldn't it?

**Comment by anoadragon453** [comment]
Oh, probably. Well, maybe this is a skyscanner bug then :P
