### ISSUE TITLE
Read markers

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riotX-android#512]
(Internal) zeplin: https://zpl.io/VkeZXQg

![Riot X - Read Markers](https://user-images.githubusercontent.com/4626865/63528310-920e9800-c4b7-11e9-8252-8ddadaa717fe.png)

**Unread messages**
- [ ] Show unread messages banner when there are unread messages
- [ ] Tap anywhere to action banner, tap [x] to dismiss, also updating read marker
- [ ] Automatically hide banner after 10s of inactivity

**Scroll down / new messages**
- [ ] Show new messages floating button after scrolling up (shouldn't appear while actively scrolling)
- [ ] Show new messages badge on floating button if they appear while scrolled up

@bwindels or @ara4n we spoke in some detail about the read marker UX in Riot Web last year, with notes captured here: https://docs.google.com/document/d/1PAZYgCfrGJuDOYGTJ8HZH7Pd2LK0yUkW13C9FMwhWHw/edit#

Could either of you speak to the implementation we arrived at in the end?

**Comment by bwindels** [comment]
Yes, riot web does the following with the read markers (mostly unrelated to read receipts) currently:
 - if the read marker is above the viewport, we show an arrow up with a green badge with a dot in it to scroll up to the read marker. The read marker is set after the last visible message after 30s of user activity*.

![greendot](https://user-images.githubusercontent.com/274386/63520998-2511f700-c4e5-11e9-9d35-1930aee5aaa9.png)

 - if the read marker is in the viewport, no button is shown, and the read marker is put after the last visible message after 1s of user activity*.

 - if the read marker is below the viewport, we don't change it automatically. If new messages arrive, we show a badge on the arrow button to scroll down, but I don't think this is based on the position of read marker, it is just something we reset when you scroll to the bottom.

![redbadge](https://user-images.githubusercontent.com/274386/63521379-d57ffb00-c4e5-11e9-9f2d-d401cb348854.png)

* ask me what user activity means in riot web if your curious.

**Comment by bwindels** [comment]
Also see https://github.com/matrix-org/matrix-react-sdk/pull/2345#issue-237724855

**Comment by bmarty** [comment]
Handle in #592
