### ISSUE TITLE
No push notifications without using google play services

### ISSUE THREAD

**Issue by thoth101010** [vector-im/riotX-android#513]
I think that it would be great to be able to use push notifications without having google play services installed (and therofore without using firebase)

**Comment by bmarty** [comment]
Have you tried the F-Droid version of RiotX? It does not contains Google Play Services and you can get a nightly build here https://fdroid.krombel.de/

**Comment by thoth101010** [comment]
I hadn't tried with this version. And notifications work, thank you.

**Comment by Tuxicoman2** [comment]
I installed RiotX on a phone without GooglePlay Services.
What is the delay of your notifications? Is this like with Conversations(XMPP) where I get almost immediate notification ? Or like other android apps (email, etc...) where a 15min timeframe between checks is enforced by Android?

**Comment by immanuelfodor** [comment]
Have you found it out in the meantime @Tuxicoman2? I'm using the Play variant and considering the Fdroid version that's why the question.
