### ISSUE TITLE
Add ability to report content

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#515]
The PlayStore policies require that unappropriate content can be reported.

Option has to be added to the message bottom sheet. An icon is needed please @nadonomy.

Use same rules than for Riot-Android

Endpoint:
@POST("rooms/{roomId}/report/{eventId}")

**Comment by nadonomy** [comment]
Icon: [alert-triangle.svg.zip](https://github.com/vector-im/riotX-android/files/3530604/alert-triangle.svg.zip)

**Comment by bmarty** [comment]
It's worth noting that there is already an icon to report content:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/3940906/63919039-3788b500-ca3e-11e9-96c7-b2bdb6a0cfb3.png">

(Sorry @nadonomy)
@nadonomy : which one may we use then?

**Comment by bmarty** [comment]
FTR this is the (ugly) dialog we have currently on Riot-Android:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/3940906/65495627-5cded680-deb7-11e9-9bbd-c9f14a3bd3c6.png">

**Comment by nadonomy** [comment]
Added UI comps to Zeplin: https://zpl.io/25x5rdr

The intention is to provide quick shortcuts for common reasons for reporting. In the background could this just sent a report with the message with e.g. 'This message is inappropriate'?

Also, it would be super nice if the client could track the 'Report sent' states so if you go to report a message again you see it, however it's not the most important. At the least if the bottom sheet could update when sending for feedback that would be good.

If we don't want to implement the 'sent' states on the buttons, we could just use a 'Your report was sent [OK]' modal.
