### ISSUE TITLE
Picture uploads are unreliable, pictures are shown in wrong aspect ratio on desktop client

### ISSUE THREAD

**Issue by colemickens** [vector-im/riotX-android#517]
Every time I send a picture on RiotX, I hold my breath. Often times they time out, and then messages and pictures are sent out of order. Yesterday, a picture upload was marked "canceled" (with no option for me to do anything about it) and then started flitting between "timed out" and continuing to upload. It finally succeeded, but is a stretched, blurry mess when I view it from the web client.

**Comment by bmarty** [comment]
Hello @colemickens ,
Thanks for reporting. We definitely have to fix issue on image sending/rendering.
There is also some rotation pb to fix
