### ISSUE TITLE
Message transitions in encrypted rooms are jarring

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/riotX-android#518]
Sending a message in an encrypted room can be quite a ride:

1. After typing the message and hitting send, nothing happens for a second (or five)
2. Then, the message is inserted in the timeline in green (indicating encryption in progress)
3. The message transitions to grey (indicating sending)
4. The message transitions to black (local echo)
5. The message disappears, leaving empty white space
6. A new grey message with text *encrypted message* appears
7. *encrypted message* transitions to the correct text

Every step can take noticeable time, sometimes multiple seconds. During all of this, the timeline can wildly jump around, especially if someone else is sending messages concurrently into the same room.

**Comment by bmarty** [comment]
Yes, we have to improve this
