### ISSUE TITLE
Timber logging in release builds

### ISSUE THREAD

**Issue by PavelSynek** [vector-im/riotX-android#519]
RiotX logs all Timber messages in release build, including [message payloads](https://github.com/vector-im/riotX-android/blob/6d01a570fdcec11387614bb02612c81a4f149a7c/vector/src/main/java/im/vector/riotx/features/notifications/PushRuleTriggerListener.kt#L51).

Would you be open to PR which [plants Timber.DebugTree](https://github.com/vector-im/riotX-android/blob/6d01a570fdcec11387614bb02612c81a4f149a7c/vector/src/main/java/im/vector/riotx/VectorApplication.kt#L87) only for debug builds?

**Comment by bmarty** [comment]
We need the log for the Rageshake feature (log can be sent by user to help debug issue). But there is absolutely no reason to log message content, thanks for the good catch.
I add the issue to bucket.
