### ISSUE TITLE
Send media, file, take photo, take video

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#52]
Using a media preview screen before sending media to the room
- [x] Handle sending media - SDK side (audio,image, video, file)
- [x] File picker
- [x] Take picture with camera
- [x] Take video with camera
- [ ] Ask user for quality level before sending images

**Comment by ganfra** [comment]
The SDK stuff has been done. At the moment UI offers only picking media with help of a library.
It should be replaced by a homemade implementation.

**Comment by vurpo** [comment]
I wish Riot X rather used the standard Android file picker than the homemade one it uses now (like the current Riot.im app does). That would automatically allow for picking files to send from custom folders, external media, or from other apps (such as Nextcloud or Google Photos or whatever apps you have installed).

**Comment by vurpo** [comment]
To demonstrate, here I can choose files to upload from Nextcloud, from Google Photos, or from external SD cards or USB drives if I had any of those plugged in.

![Screenshot_20190611-123312_Files](https://user-images.githubusercontent.com/6452110/59261052-6f553d00-8c45-11e9-9417-0d52a82f23fa.png)

**Comment by bmarty** [comment]
@vurpo yes we will use the classical android file picker intent

**Comment by vc7ee** [comment]
@vurpo current Riot.im also allows the android one, though I for example, like that you can pick images in the app. The android picker could be under 'other file' picker (+ icon), since it can allow picking any file.

**Comment by progserega** [comment]
It will be nice if when send video - it will be recompress (many video have big size):
https://github.com/vector-im/riotX-android/issues/442

**Comment by ptman** [comment]
@progserega compress on the phone before uploading? or on the server before downloading?

**Comment by progserega** [comment]
On the phone before download - as in whatsapp.
Because if user will record HD video in 1040p - then 5 minutes will be big size. And it is will can not upload to server.

**Comment by jtagcat** [comment]
Note: Failure of uploading files (especially uploading files too big) results RiotX roadblocking (no messages in, no messages out and can't cancel sending the blocking video, though, notifications are received). Current resolution to the roadblock is to clear data of the app from android.

**Comment by matrixes** [comment]
I just had what I think is a similar issue as what @jtagcat mentions; I tried to upload a file on a slow network, and the upload stalled because of timeout. No matter how many times I retried, RiotX wouldn't be able to upload it.
So, in an attempt to see if I could circumvent the timeout, I crimped the file to 1/4 of the original and uploaded that instead.
However, I realised too late that I can't cancel any of the previous timed out upload attempts, so now I'm stuck with multiple upload items that never finishes and can't be cancelled.
Only clearing data and logging back in makes the app behave properly again.
Cancelling pending actions would certainly improve the user experience here.

**Comment by progserega** [comment]
RiotX is not usable for send images in original size (without alternatives scale size). If network is lower  then wifi or LTE - sending is a problem, because size of images from modern cameras is big.

**Comment by fbruetting** [comment]
If you shrink images, please provide a choice for three different quality levels and uncompressed!

**Comment by bmarty** [comment]
Ok, done in #619 
Image quality will be handled (maybe?) in #631
