### ISSUE TITLE
Message text is lost when a reply is added or removed

### ISSUE THREAD

**Issue by vurpo** [vector-im/riotX-android#529]
To reproduce: type some text into the message field and then choose "Reply" on a message in order to reply to it, or tap the red X to remove the reply after typing some text into the message field.

In both these cases, the message text field is cleared. This is inconvenient if you try to compose a message and afterwards decide to add/remove the reply to the message.

**Comment by bmarty** [comment]
Related to #552 , I'm working on it

**Comment by bmarty** [comment]
This is fixed in version 0.6.1, in #552.
