### ISSUE TITLE
Room details screen

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#54]
- [ ] Room title
- [ ] Room picture
- [ ] Room topic
- [ ] List of members
- [ ] List of files (excluded from showstopper)
- [ ] E2E state

**Comment by ara4n** [comment]
Showstoppers here are: List of members & Room title & Room topic & E2E state.

List of Files is least important.

**Comment by bmarty** [comment]
Handled in #843 

Attachments list is tracked in #860
