### ISSUE TITLE
characters being erased while I type in the room browser input

### ISSUE THREAD

**Issue by bbigras** [vector-im/riotX-android#545]
I was trying to type in this dialog and some characters were erased. Like if I was typing backspace.

![image](https://user-images.githubusercontent.com/24027/64191543-bae34580-ce46-11e9-9c80-d734ec6ef893.png)

I'm thinking maybe it happens because there's no matches but I'm trying to join a freenode channel.

**Comment by bmarty** [comment]
Yes, I can reproduce the issue if I type a new char during the request.
Also sometimes I observe a JobCancellationException, if I delete a char during the request.
The job cancellation is normal, but it should be hidden from the UI (this can be considered as a regression after what have been done on Jobs).

**Comment by bbigras** [comment]
Thanks!! :+1:
