### ISSUE TITLE
Value in Home Server at login without User Name fails

### ISSUE THREAD

**Issue by the-moog** [vector-im/riotX-android#579]
On initial install, entering a value in Home Server without entering a value in Username fails. It then reverts to the default https://matrix.org.
If no user name is entered and the home server field is edited, the username field should be focused, rather than pointlessly trying (and failing) to login.

**Comment by bmarty** [comment]
This has been fixed with the new login flow

**Comment by the-moog** [comment]
Just tried login with latest Google Play release of RiotX, I confirm that I logged in without issue.  I thought at first that I had no rooms or messages, but then realised I needed to press the # button.  Perhaps for a new registration that view should be a default. #834
