### ISSUE TITLE
Share to RiotX

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#58]
- [ ] Choose room to share element(s) to

**Comment by bbigras** [comment]
It would be nice to also support [DirectShare](https://developer.android.com/about/versions/marshmallow/android-6.0#direct-share) or the new [Sharing Shortcuts API](https://developer.android.com/preview/features/sharing).

**Comment by bmarty** [comment]
Fixed in #619 
@bbigras DirectShare will be handled in #652

**Comment by bbigras** [comment]
Awesome, thanks!
