### ISSUE TITLE
Few rooms listed and messages are ancient

### ISSUE THREAD

**Issue by the-moog** [vector-im/riotX-android#580]
Just gave RiotX a go.   Found that only three rooms are listed and the messages in those rooms are mostly ancient.  Only Synapse Admins is up to date.
Private IS/HS in use.

**Comment by bmarty** [comment]
Is your experience with RiotX better now?

**Comment by the-moog** [comment]
Yes it's much more usable

**Comment by bmarty** [comment]
Ok, thanks
