### ISSUE TITLE
Room member detail screen

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#59]

**Comment by nadonomy** [comment]
Using Riot Web & Android as a benchmark, it'd be good to design from a list of states & actions Riot X will be capable of by the end of Phase 2. So far I have:

- Profile picture
- Profile picture actions? Tap to enlarge? Save?
- Display name
- Matrix ID
- Display power level, edit if applicable
- Jump to read receipt? (Not sure this makes sense on mobile)
- Share link to user
- Mention (Not sure this makes sense on mobile?)
- Ignore
- DM
- E2E? How much of the device list should we dev for phase 2? Should we defer this until we dev cross-signing in a separate sprint in the near future?

**Comment by bmarty** [comment]
Done in #843 

Missing features are handled by #855, #856, #857, and #858
