### ISSUE TITLE
Opening links from RiotX reuses browser tab

### ISSUE THREAD

**Issue by ilmari** [vector-im/riotX-android#599]
When opening links from RiotX, they all open in the same browser tab (in Firefox at least) if it's left open.

This problem existed in Riot Android too (https://github.com/vector-im/riot-android/issues/381), so the fix is presumably something similar to https://github.com/vector-im/riot-android/commit/802135bc03246bc474fe0cc115c433941a3fbc20.

**Comment by bmarty** [comment]
Thanks @ilmari for reporting! It will be fixed in the next release
