### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#62]
- [ ] Integrate matomo
- [ ] Same level of report than Riot
- [ ] Opt-in (ask at first startup?)
- [ ] Disable in the settings (See #40)

**Comment by vc7ee** [comment]
Opt-in, but ask on say 10th startup? As for now registering, getting in to a room, verifying devices is a lot to deal with, on few first lsunches the user is just gonna press any button to get away from the unimportant thing to them at the current moment, maybe even without reading it.

**Comment by BloodyIron** [comment]
I think you mean matomo not piwik :package: 

For those of us looking to self-host riot+matrix completely private, if we could have a setting to force matomo tracking without user input, and not even having it be an option to disable, that'd be appreciated. I can understand this is not what works for the public riot infra though, but getting usage stats (forced, not-disable-able) for private infras would be mighty handy, and wouldn't need to startle users with asking if they want to opt in (they probably wont, defeating the point of it).

**Comment by bmarty** [comment]
For the moment we do not see any plus-value to integrate any analytics solution, so let's close this.
