### ISSUE TITLE
Preview media before sending them to rooms

### ISSUE THREAD

**Issue by nadonomy** [vector-im/riotX-android#631]
- Show which room you're sending media to
- Show a preview of the media
- Allow the user to enter a caption?

**Comment by fbruetting** [comment]
Pro caption. I really don’t know if I’m right here, but I suspect that you might reuse this preview screen/functionality when media later is to be forwarded to several people/rooms at once (once implemented). This way you can make sure that a certain text is sent to everybody receiving that media.

Might be a hassle and error-prone having to write a text/description/comment as a complete second step and then having to again choose exactly all the people/rooms which you sent the media to.

**Comment by Thatoo** [comment]
Is this the issue for image resizing? or https://github.com/vector-im/riotX-android/issues/761 ?
Is it coming?

**Comment by bmarty** [comment]
The issue is merged with #761
