### ISSUE TITLE
No device verification by default

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#633]
RiotX v0.6.1

In our encrypted room, I sometimes encountered the below shown warning screen about unverified devices. I have the option to send encrypted messages solely to verified devices deactivated. In regular Riot-Android, we can see similar warning screens.

I propose to ignore these verifications by default to make Riot more idiot friendly and usable for normal people. It would be better to only show an informational banner/window/wizard at first start, about if a user wants to enable device verification for enhanced security, with also a button/link to further information about what this means. This way, security-focused people will get this right from the start. All other users should get completely abstracted from that, with the exception of some informational dialogs, and just use Riot like how WhatsApp is implemented. Some users are really picky about UX, because the benchmark always is WhatsApp, and the question I encounter always is "why can't we just use WhatsApp/Threema/Telegram/Slack?!".

Background: In our organization, I proposed Matrix for being the new communication platform, after trying the extremely crappy Wire. We left Wire because of it's many bugs and errors all the time, and our people which are not used to OSS were getting pretty mad about that fact. Now when Matrix/Riot is also showing such warnings without real need, the non-technical people among us surely try to get us back to WhatsApp or some other proprietary platform, which I dislike for obvious reasons - solely because their UX being less alienated.

I'm absolutely sure that Riot would *heavyly* benefit from being fool-proof, because otherwise it likely would restrict it's user base to more advanced people. Please help me spreading the use of Matrix, because for many people, usability sadly matters way more than everything else, and these then drag bigger communities with some critical mass of privacy-interested people back to proprietary software. RiotX with it's vastly improved UX already is a huge success! But it still needs more polish. :/

// For whatever reason, I can't upload my screen shot on mobile view. Will do that later!

**Comment by nadonomy** [comment]
Hey @fbruetting— good news! We're actively working on this as we speak, having solved most of the critical thinking and interaction work, we're now formalising our execution plan per platform.

The general idea is that Riot decorates rooms extremely simply— with whether or not a room is encrypted, and then verification is completely opt in.

In practise in Riot X, it means verification only concerns users who opt into it, after tapping through Learn More in user profiles:

<img width="1083" alt="Screenshot 2019-10-23 at 09 47 05" src="https://user-images.githubusercontent.com/4626865/67375575-be5b9900-f57a-11e9-9c72-f842fbb4245a.png">

Expect to see more detailed designs & issues rising in our trackers soon!

**Comment by fbruetting** [comment]
Ah cool! Thank you for the detailed explanation. The image below shows what we received in Riot.im, in RiotX we saw some similar screen and that blocked messaging for a friend of mine. If those things got, cleared, that’s good to hear!
![Screenshot_20191020-175148__01](https://user-images.githubusercontent.com/10520767/68553496-369ed700-0422-11ea-85b3-cf7d70a473e3.jpg)

Additionally it would be cool if the red attention sign markers shown below could be removed from Matrix-Web in a similar way: 😎️
![Bildschirmfoto von 2019-11-11 01-11-48](https://user-images.githubusercontent.com/10520767/68553523-57672c80-0422-11ea-9a43-a6cf18ce31b0.png)

**Comment by fbruetting** [comment]
Should be solved, I haven’t seen those “untrusted devices in room – really send?” messages in quite some time.
