### ISSUE TITLE
Passphrase doesn't match (Export room keys)

### ISSUE THREAD

**Issue by krystiancha** [vector-im/riotX-android#644]
While exploring the app I found that you can't export room keys.

#### App version
0.7.0 -- Google Play build

#### Steps to reproduce:
1. Go to *Settings*.
2. Tap *Security & Privacy*.
3. Scroll down and tap *Export E2E room keys*.
4. Type the same text into *Create passphrase* and *Confirm passphrase* input fields.

#### Expected behavior:
I can tap the *EXPORT* button to export the keys.

#### Actual behavior:
* The button is grayed out.
* Tapping the button has no effect.
* The second input is outlined in red, a red circle with and exclamation mark is displayed and the text *Passphrase doesn't match* is visible.

![Screenshot](https://protecto-static.s3.eu-central-1.amazonaws.com/Screenshot_20191025-144329.png)

**Comment by bmarty** [comment]
Oh yes, something's wrong. Thanks @krystiancha for reporting. I add the issue to the current sprint, as it shouldn't be long to be fixed
