### ISSUE TITLE
RiotX forgets configured font size

### ISSUE THREAD

**Issue by hpdeifel** [vector-im/riotX-android#645]
Since the latest update (0.7.0) from the play store, RiotX sometimes reverts to using "normal" as font size, even though I have set it to "small". This only happens when switching to the app, not while it is in the foreground.

When this happens, the font size in settings still shows "small" and resetting it to actually be "small" entails switching to "normal", leaving settings, entering settings again and then setting it to "small".

**Comment by maralorn** [comment]
I can reproduce this, too. It happens on every fresh start of the app. Also this is definitely a regression. Because it had been working before that update.
