### ISSUE TITLE
Make read receipts look like other membership changes

### ISSUE THREAD

**Issue by frandavid100** [vector-im/riotX-android#662]
I'm not sure why read receipts look different from the rest of membership changes in Riotx, but I think conversations would look cleaner if they looked the same instead.

To the left, the way they currently look. To the right, the way I'd like them to look.

![image](https://user-images.githubusercontent.com/694794/68082162-8fb2ad80-fe19-11e9-965a-36685316a6ac.png)

Would you consider making that change?

**Comment by ara4n** [comment]
it’s a deliberate choice to put RRs on the RHS to differentiate from membership changes. thanks for the suggestion though :)

**Comment by MegaArthur** [comment]
It certainly helps avoid confusion when they are the way they are right now. It's like that in all other messaging apps

**Comment by fbruetting** [comment]
@frandavid100 How would you then mark up read receipts for users having read membership changes. 😂️

**Comment by MegaArthur** [comment]
@frandavid100 After all, if you *really* want them to look like that, you can just build your own version with a tiny change in the code
