### ISSUE TITLE
Different emoticons labels between Riot desktop and Riotx

### ISSUE THREAD

**Issue by DamienCassou** [vector-im/riotX-android#671]
This seems similar to #355 but this one has been closed and the problem persists in 0.8.0-dev (157295240, F-b1171, downloaded from f-droid repo by Krombel, riotx-dev-fdroid).

**Comment by bmarty** [comment]
Is your local set to en-US?

Ref: https://github.com/vector-im/riotX-android/blob/develop/matrix-sdk-android/src/main/res/values-en-rUS/strings.xml#L6

**Comment by bmarty** [comment]
After a quick investigation, the Android system may consider that default language is EN-US, as does Android Studio:
Default:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/3940906/68313191-7b3e1180-00b4-11ea-81eb-10528eea8881.png">
en-US:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/3940906/68313223-85f8a680-00b4-11ea-8fb6-c495be6dcc32.png">
So in our case, we should do the same and create a resource directory for en-GB

**Comment by DamienCassou** [comment]
> Is your local set to en-US?

I think it is because my language is set to "English (United States)"
