### ISSUE TITLE
Cannot see user profile

### ISSUE THREAD

**Issue by saveriob** [vector-im/riotX-android#688]
Maybe I am missing something obvious, but I cannot understand how to see a user profile (and, for example, start a verification process) in RiotX. If it's there and I just missed it, please consider this as a suggestion for the user interface. 
I tried long presses and clicking on almost anything and I cannot get to this
https://github.com/vector-im/riotX-android/issues/633#issuecomment-545340644

**Comment by bmarty** [comment]
Hi @saveriob , this is not available yet in RiotX and will be handled soon (see #59)
