### ISSUE TITLE
Switch font size support

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#69]
Related to #40

**Comment by maralorn** [comment]
I am on Version 0.21.0 [40021002] (G-b2731) on Android 7.1.1 and the font size option has no effect at all for me.

This worked until roughly half a year ago. Then the font size switched back to normal after restart, as in #805. Now it does not change at all.

**Comment by Ai-rin** [comment]
@maralorn Exactly! I experience same problem. 
Those font size issues are preventing me from trying out RiotX, I have to stick with old Riot.
