### ISSUE TITLE
Prevent RiotX from popping into the foreground after opening

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#694]
A very annoying feature of riot-android is that it would force itself in front of you when it finishes loading after opening it from a cold start. RiotX seems to have inherited this behaviour, possibly by reusing some old components.

Android 10 disables this behaviour, but it would be nice to prevent it in-app until then.

**Comment by bmarty** [comment]
Yes, let's fix this annoying behavior

**Comment by bmarty** [comment]
Can't reproduce this. Please reopen if it is still the case

**Comment by anoadragon453** [comment]
Cool :+1: Make sure you're testing on a Android 9 or lower device though :)
