### ISSUE TITLE
Installation fails on Android 5.0.2

### ISSUE THREAD

**Issue by ZoomRmc** [vector-im/riotX-android#696]
Installation fails on on Android 5.0.2., kernel 3.10.54.

RiotX stopped installing somewhere after commit 0632870be13105b48c2a49bd13d301a2e00d832f, the latest build I can install is 979, later ones giving me `[INSTALL_FAILED_DEXOPT]` There were some library version upgrades after mentioned commit, which may be the source of a regression.
Both GPlay and FDroid builds fail.

Most probably it's a buggy phone ROM, but I'd like to know what triggers the fail.

**Comment by ZoomRmc** [comment]
Sorry for bumping, but I would really like to hear at least some guesses of what's wrong and where to dig.

**Comment by bmarty** [comment]
Sorry, no idea

**Comment by ZoomRmc** [comment]
So the issue is basically a buggy ROM and not specific to RiotX. Some libraries were bumped during a windows specified in initial report and caused installation to fail.

If you have such issue, try to contact your vendor's support, or more realistically, upgrade your phone's firmware.
Sorry for spamming the issues.
