### ISSUE TITLE
No Known Servers error on trying to join upgraded room

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#697]
cc @turt2live

During the mass matrix community room upgrade, I attempted to click on a couple tombstone links but hit No Known Servers on every one.

I've sent a rageshake for my attempt on Synapse Announcements.

**Comment by violoncelloCH** [comment]
same for me

**Comment by anoadragon453** [comment]
My guess is that RiotX is just trying to /join the room ID that's given using the local homeserver, but if another server upgrades the room your local server will not be able to join it without the client telling it which server to ask for information.

In the case of room upgrades, the server the client should specify is that of the sender of the tombstone, as their server is the one that upgraded the room.

Use this endpoint: https://matrix.org/docs/spec/client_server/unstable#post-matrix-client-r0-join-roomidoralias and provide the sender of the tombstone in the `server_name` query parameter.
