### ISSUE TITLE
Bug / Unwanted draft 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#698]
Step to reproduce:

1) long press to edit a message, then close the message preview on top of the composer and then delete all text in the composer
2) Swipe to reply on another message, and type something then send

-> Actual : the composer comes back to the previous edit state (that I explicitly discarded and cleared)

**Comment by enzingerm** [comment]
Even when returning to the room list after deleting all text in the composer (and closing the preview) the room is marked with some kind of "draft" icon. When I switch back to the room and send some message, the edit draft appears again.

**Comment by BillCarsonFr** [comment]
https://matrix.to/#/!gGkYcJLTzcNrfERksd:matrix.org/$9hPggzxUwb2oe74DKEvkeoaWkG9vquieHoxa1A2yYEk?via=matrix.org&via=privacytools.io&via=tchncs.de

**Comment by 7h3kk1d** [comment]
I'm also seeing this and have a draft I can't remove.

**Comment by jandem** [comment]
I had this problem and "Clear cache" under Settings => General fixed it. (I also tried clearing the app's cache in Android's settings but that didn't help.)

**Comment by nunoperalta** [comment]
This happens to me too. Very very inconvenient and obtrusive. I believe this should be looked into with high priority :) Thanks!

**Comment by bmarty** [comment]
(Finally) fixed in #1665
