### ISSUE TITLE
Specific room isn't loading

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#700]
The #fosdem:half-shot.uk isn't loading for me in riotX. It loads fine in riot-web. riotX just shows the loading spinner.

Clearing cache doesn't make a difference. Rageshake sent.

**Comment by Bubu** [comment]
This fixed itself after a few days. I'll leave it open if maybe the rageshake shows something.

**Comment by bmarty** [comment]
Ok, thanks for the update
