### ISSUE TITLE
Unable To save Photos

### ISSUE THREAD

**Issue by Flam3z** [vector-im/riotX-android#704]
When viewing a sent photo by any user, there is no option to save the photo when you are in the chat and when you view it in a bigger scale when pressing to view.

**Comment by bmarty** [comment]
Yes, this will be handled soon, thanks for creating the issue

**Comment by Soundtoxin** [comment]
This has been bothering me as well. I am trying to use RiotX full-time and this is probably the biggest usability issue right now. Looking forward to a fix.

**Comment by duncanturk** [comment]
Is this covered by #973 ?

**Comment by auscompgeek** [comment]
It does look like #973 is a duplicate of this issue.

**Comment by duncanturk** [comment]
This may be closed than @Flam3z
