### ISSUE TITLE
[SDK] MSC2241 / verification in DMs 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#707]
see https://github.com/matrix-org/matrix-js-sdk/pull/1050/files

- [ ] Add a new transport layer: to_device -> event
- [ ] Adapt new content format - /!\ content hash in e2e room
- [ ] Find the right DM, create it if required
- [ ] UI will provide the DM if there are several DMs

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2850)
