### ISSUE TITLE
Launcher icon

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#71]
- [x] Launcher icon
- [x] Notification Icon for Android Status Bar 
- [ ] Theme for first Activity (See Riot)

**Comment by bmarty** [comment]
Currently Riot element has been reported (#97)

**Comment by nadonomy** [comment]
Launcher & status bar icons, both legacy & adaptive can all be found in this zip: https://matrix.org/_matrix/media/v1/download/matrix.org/MWOQOPtXZbUDEPCDhyIWlCME
