### ISSUE TITLE
 Verifications in DMS / Handle incoming transactions #709 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#710]
<img width="226" alt="image" src="https://user-images.githubusercontent.com/9841565/70069410-0518c600-15f2-11ea-8bcf-8fe991a7da6a.png">

<img width="617" alt="image" src="https://user-images.githubusercontent.com/9841565/70069442-11048800-15f2-11ea-9bd2-e6f0391090c7.png">

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2853)
