### ISSUE TITLE
Last two characters in markdown title seem in default style

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riotX-android#715]
On riot-web this shows as a title entirely, but on riotX the last two characters are not as big or bold.
![image](https://user-images.githubusercontent.com/24435423/69725914-9afaaf80-111f-11ea-9820-920d60b19698.png)

**Comment by Bubu** [comment]
Just sent a rageshake for this.

**Comment by bmarty** [comment]
Not reproduced anymore
