### ISSUE TITLE
RiotX uses [displayname](matrix.to...) format for the body of mentions

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#739]
When you mention someone in a pill, it inserts a markdown-format link into the `body` of the event (perhaps in order to generate the correct html for `formatted_body`?) This messes up things like the IRC bridge, which rely on a username being a mention instead of a link. Thus, when someone writes `<pill>john</pill>: hi!` in an IRC bridged room, it comes across in IRC as `[john](https://matrix.to/...): hi!` instead of `john: hi!`.

The spec [states](https://matrix.org/docs/spec/client_server/unstable#user-room-and-group-mentions) that messages containing a mention look like the following:

```
{
    "body": "Hello Alice!",
    "msgtype": "m.text",
    "format": "org.matrix.custom.html",
    "formatted_body": "Hello <a href='https://matrix.to/#/@alice:example.org'>Alice</a>!"
}
```

**Comment by BillCarsonFr** [comment]
Ok, spotted. Happens when autoMarkdown is ON
