### ISSUE TITLE
Retrieve the HS url from the Riot URL

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#744]
When the user enter the URL of a riot web client, the application should try to get the homeserver url from the config file. The wording is "Enter the address of a server or a Riot you want to connect to" but the app does not do the job. 

Ex: https://valere-staging.riot.im -> we get a 404, but we should test https://valere-staging.riot.im/config.json to retrieve the HS url (field **default_hs_url**)

Also the 404 is not displayed properly, to test with a url which is not a homeserver

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2876)
