### ISSUE TITLE
Add simple media Viewer

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#75]
- [x] When user click on a media in a room, the original media (and not the thumbnail) is displayed in fullscreen.
- [x] During original media download, the thumbnail (if it exists) may be displayed along with a loader
- [x] The possibility to see other media of the room by swipping left/right is not needed for now.
- [x] Image can be zoomed by pinching, but the method used on Riot legacy seems to lead to crash because of too much memory usage.

**Comment by ganfra** [comment]
Maybe try https://github.com/Piasy/BigImageViewer for reduce memory usage

**Comment by bmarty** [comment]
Done
