### ISSUE TITLE
Several settings are non-functional

### ISSUE THREAD

**Issue by schwukas** [vector-im/riotX-android#751]
I noticed that several settings under `Settings`->`Settings` are not actually changing the behaviour they are supposed to change. The list below lists those options that did not have any effect for me. 

* Show timestamp for all messages.
* Show timestamp in 12-hours format.
* Show read receipts.
* Show join and leave events.
* Show account events. (handle/avatar changed)
* Send message with enter key.

I'm on a Sony Xperia XZ2 Compact (**H8324**) with **Android Version 9** (stock, no mods) and the latest RiotX from the play store (0.9.1).

I can submit a rage shake report if so desired.

**Comment by bmarty** [comment]
Thanks for the report.
All broken settings are import from old Riot, we have to plug them or to do some cleanup.

**Comment by fbruetting** [comment]
> Show join and leave events.

Works for me…?

**Comment by schwukas** [comment]
So you can show **or** hide them? I can see them but disabling it doesn't do anything.
