### ISSUE TITLE
Show skip to bottom FAB while scrolling down

### ISSUE THREAD

**Issue by steef435** [vector-im/riotX-android#752]
# Current behavior
The current behavior for the skip to bottom FAB in a chat screen is: while not at the bottom and not scrolling, show the FAB after a short delay. So it is not shown while scrolling down.

# Issue
I would like be able to click skip to button while scrolling down. Use case: I start scrolling but realize it will take a lot of scrolling to get to the bottom, so I click on the skip to bottom FAB. With the current implementation, I have to wait for the scrolling movement to die down completely.

# Suggested behavior (inspired by Telegram app)
The button should appear and stay visible when:
- scrolling down

The button should disappear again:
- when reaching the bottom (by scroll or by click)
- when scrolling up

(so if you scroll down a bit, it should appear and stay visible until you scroll up)

**Comment by steef435** [comment]
What are your thoughts on this @bmarty? I'm willing to implement this (try at least, I have little Android experience), but I realize there are many ways to do the logic for this little button.

For now I have looked a bit into it and only _added_ the behavior that it shows while scrolling down (so it still pops up when the user is not on the bottom and not scrolling) [here](https://github.com/steef435/riotX-android/commit/958c435447ac482e86586e52bdb7254ddfce076f).

May I submit a pull request, or would you like me to remove the popup when not scrolling first? Again, I can imagine you would want to think this design decision over. Do tell if I should let this rest.

**Comment by bmarty** [comment]
Hello @steef435 , I only see your second comment now.
I've implemented the desired behavior here: https://github.com/vector-im/riotX-android/pull/817

Please let me know if it suits your need. Thanks
Benoit

**Comment by steef435** [comment]
Buildkite build works great on my phone, thanks!

The original idea was to not let the button show up when not scrolling (regardless of whether we are at the bottom or not), as Telegram does it. But this way is probably better since there is no other visual cue of not being at the bottom otherwise (and both WhatsApp and Signal _do_ show the button at rest).
Thank you!

**Comment by bmarty** [comment]
Thanks @steef435 for your test and feedback :). And yes, we want RiotX to be better than any other messaging app :)
