### ISSUE TITLE
New encrypted keys message doesn't make grammatical sense and is confusing

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riotX-android#757]
![Screenshot_20191210-115809](https://user-images.githubusercontent.com/1342360/70527749-83bab980-1b44-11ea-8f91-fd662eda8f9a.png)

"New encrypted messages keys" doesn't make grammatical sense. It should be something like "New encrypted message keys", though as a user I still have no idea what that actually means.

**Comment by BillCarsonFr** [comment]
Thanks will see what to do with the copy.
This shows up when you have keybackup enabled on your account, and it's trusted (i.e. new keys are beeing uploaded correctly), and that we detect that this backup contains keys that you don't know
