### ISSUE TITLE
Room overview shows deleted messages as “Encrypted message”

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#758]
v0.9.1

When the last message of a room got deleted, the room overview shows “Encrypted message” as the room preview (i.e. last message preview). Instead, either “Deleted message” or the last existent message content should be shown.

Hint: My RiotX version is German, so I translated the message text.

**Comment by bmarty** [comment]
Is it for an encrypted room?

**Comment by bmarty** [comment]
Ok, I reproduce the bug

**Comment by bmarty** [comment]
Note that it's not better on clear room, the room show an empty area in this case
