### ISSUE TITLE
Images preview and resizing

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/riotX-android#761]
When uploading a image RiotX doesnt ask in which size (Small, medium, big, original). It uses the full filesize.

Also the settings->preferences-> standardcompression are ignored.

I hope i place this at the right place.

**Comment by Thatoo** [comment]
It's a problem for self hosted synapse server with slow internet connection.
Being able to resize pictures is also an environmental friendly feature :-)

**Comment by bmarty** [comment]
FTR The settings has been commented out for the next release.
Image resizing is a missing feature though

**Comment by Thatoo** [comment]
@bmarty : Where is this comment?
I don't see this issue in RiotX - Phase 2 project ...
And I don't see it being part of v0.14.0.

**Comment by fbruetting** [comment]
The code for being able to select the image quality in RiotX’s settings was commented out (because these settings did not lead to any action). Should be re-activated once the implementation is here (which might be in the coming two/three weeks, as this issue was tagged for the next sprint). 😉

**Comment by bmarty** [comment]
So the current choice are those one so far:

Case 1: Share to RiotX (from thirs party app): after selecting a room, a dialog confirm that this is the correct room. When sharing text (url or whatever), it just fill the composer (saving the preview draft if any) but **does not** send the event.
Case 2: in a room, when sharing an media from gallery or camera: we display a preview of the medias ready to be send with option to crop, rotate, and compress each media. Captions will be handle in a dedicated issue.
Case 3: in a room, when sharing something of type file, no compression occurs if any images are selected. There is no preview and no possible media edition in this case.

**Comment by fbruetting** [comment]
To case 1:
* Does that work for multiple images?
* Is image compression available here?

And what happens when there is some saved text in the composer of a room, like a draft? In case of 1:1 it could make sense to append the to-be-shated text (maybe even ask the user?). For 1:n I think it would be better to stash the draft and pre-fill that text for usage afterwards. 🤔

**Comment by bmarty** [comment]
> Does that work for multiple images?

yes

> Is image compression available here?

yes

> And what happens when there is some saved text in the composer of a room, like a draft? In case of 1:1 it could make sense to append the to-be-shated text (maybe even ask the user?). For 1:n I think it would be better to stash the draft and pre-fill that text for usage afterwards. 🤔

good point, yes, maybe try to do what you describe

**Comment by ganfra** [comment]
We also have to handle the case where you select multiple rooms. You won't be able to prefill text in that case I guess

**Comment by bmarty** [comment]
Done in #1010
