### ISSUE TITLE
SDK | DM Key verification - Support aggregation of m.references

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#763]
In order to display security events in timeline, we need to be able to navigate event references to perform some checks.

**Comment by BillCarsonFr** [comment]
see https://github.com/vector-im/riotX-android/pull/765

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2884)
