### ISSUE TITLE
Sharing things to RiotX contacts: List not sorted by date/time

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#771]
v0.10.0

When I share media to RiotX, the list (for selecting the contact/room to share to) is not sorted by a criteria. Would be good if the list could be sorted by last action, so that the most current rooms and contacts are at the top of the list!

**Comment by bmarty** [comment]
We can use the breadcrumbs index to improve this, with some header: "recent rooms", "other rooms"
