### ISSUE TITLE
Referencing-autocompletion suggests people which are not in that room

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#772]
RiotX v0.10.0

Some weeks back I falsely invited a wrong person into a room. He declined the invitation and has never been a member of the room. Still, when I type in the `@` sign, his name gets listed in the autocompletion suggestions.

**Comment by bmarty** [comment]
Ok, thanks for reporting. I think it's fixed in version 0.12.0.
Could you please confirm and close this issue if it is the case please?
Thanks

**Comment by bmarty** [comment]
Note that only joined users will be in the autocompletion list ([ref](https://github.com/vector-im/riotX-android/blob/0f7d59a8c786efc4006a6cdf95b236f742060be4/vector/src/main/java/im/vector/riotx/features/autocomplete/member/AutocompleteMemberPresenter.kt#L65))

**Comment by fbruetting** [comment]
Yes, that’s fixed, thank you!

**Comment by bmarty** [comment]
Thanks,
FTR I will remove the current user from the autocompletion member list

**Comment by fbruetting** [comment]
“FTR”?

**Comment by bmarty** [comment]
For The Record :)
