### ISSUE TITLE
Opening "Security and Privacy" settings crashes the app and makes the whole phone freeze up

### ISSUE THREAD

**Issue by SharkyRawr** [vector-im/riotX-android#775]
- Using RiotX, logged in on my own Homeserver
- restored my keys using the provided mechanism
- trying to go in to "Security and privacy" settings results in a crash and freezes up the whole android OS as seen in the screenshot: ![Screenshot_20191216-133905](https://user-images.githubusercontent.com/246984/70907839-2e7e1c80-200a-11ea-8f41-cdbf495ebc1f.png)

Running on a Pixel 3, Android 10

**Comment by bmarty** [comment]
Security and privacy screen has been rework on #798 , the freeze will maybe be fixed. Without logs I cannot be sure of what happened.
Please tell me if it is fixed in the next version v0.12.0 (not yet release)

**Comment by bmarty** [comment]
Please reopen if it happens again
