### ISSUE TITLE
Profile picture disappears on resume

### ISSUE THREAD

**Issue by gjabell** [vector-im/riotX-android#777]
Small bug, but the small profile picture in the top left-hand side of the home screen will disappear and be replaced by the default profile picture after resuming the app.

Reproducable by opening the app, returning to the home screen, and then reopening the app from the recent apps switcher menu.

**Comment by steef435** [comment]
It also happens after entering a room and then going back to the room list, so I think it happens every time the fragment is recreated after first launch. I think it has to do with the group change event but I can't figure out why it does get properly populated at launch then

**Comment by bmarty** [comment]
Thanks, there is a bug indeed. We will check that

**Comment by gjabell** [comment]
Haven't run into this issue lately; seems to be fixed?

**Comment by bpcurse** [comment]
In v0.11.0 gplay on Android 6.0.1 it still persists. Is this fixed in master?

**Comment by steef435** [comment]
@bpcurse: indeed, see [CHANGES.md](https://github.com/vector-im/riotX-android/blob/develop/CHANGES.md).
