### ISSUE TITLE
Emoji picker in message composer

### ISSUE THREAD

**Issue by bpcurse** [vector-im/riotX-android#780]
There is no emoji picker, when you enter a colon ":" (Feature Parity: Web/Desktop)

Sorry in advance if this a duplicate (can't believe it has not been posted before) but I have looked through all open issue captions and none seems to deal with this basic issue?

**Comment by bmarty** [comment]
Also, you could be able to type emoji directly from the keyboard, which is not possible on desktop.

**Comment by bpcurse** [comment]
Yes that is possible, but it would be more intuitive if you could use the leading colon syntax as well to enter emoji names or open the emoji picker just like the web-client.
Thank you for taking this into consideration.
