### ISSUE TITLE
Cross-signing in SDK

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#790]
From riot-ios created by [manuroe](https://github.com/manuroe): vector-im/riot-ios#2890  

As per https://github.com/uhoreg/matrix-doc/blob/cross-signing2/proposals/1756-cross-signing.md

- [x] Create my user's signing keys: master, self-signing (SSK), user-signing (USK)
- [ ] Delegate the storage of private parts outside of the module. Note that the storage will be delegate to SSSS
- [x] CS API to manage public parts
     - [x] upload: 'POST /keys/device_signing/upload'
     - [x] fetch: update response handling of existing `POST /keys/query`
- [x] Store `CrossSigningInfo` like `MXDeviceInfo`
- [x] CS API for signatures: `POST /keys/signatures/upload` and `GET /keys/query`
- [ ] ...

As reference the JS sdk exposes the following API, we should probably offer the same service
- [ ] `resetCrossSigningKeys(level)`
- [ ] `getCrossSigningId(type) -> String`
- [x] `getStoredCrossSigningInfoForUser(userId) -> CrossSigningInfo`
- [x] `checkUserTrust(userId) -> UserTrustLevel`
- [x] `checkDeviceTrust(userId, deviceId) -> DeviceTrustLevel`
- [x] `checkOwnCrossSigningTrust() -> DeviceTrustLevel`
- [x] `checkCrossSigningPrivateKey(privateKey, expectedPublicKey) -> Bool`

Missing, TBD:
- [x] SDK API to mark a user as verified
- [ ] ...

**Comment by BillCarsonFr** [comment]
Closed.
Follow up issues:
#944
