### ISSUE TITLE
Infinite spinner on loading next part of messages after "Jump to unread" 

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riotX-android#791]
Riotx sometimes (often) don't load next (newer) part of messages from timeline, when I use "jump to unread" - I see infinite spinner. But if I jump to bottom and scroll up time-line to unread point manually - messages are loaded successfully.

I use own quick homeserver, and old Riot-Android works well, so problem is not on server side.

**Comment by montvid** [comment]
Same bug with 0.12 release.

**Comment by pwr22** [comment]
I also see this - it's kind of forcing me back to Riot right now :cry:

**Comment by bmarty** [comment]
Fixed in #945

**Comment by MurzNN** [comment]
I have same problem on 0.15 version :(
