### ISSUE TITLE
Messages sent when user is invited are not decryptable when the invited user joins the room

### ISSUE THREAD

**Issue by scottlahay** [vector-im/riotX-android#803]
Creating a room that is 
- Encrypted
- History visibility set to on invite   

Users can not decrypt messages sent before they joined the room

![image](https://user-images.githubusercontent.com/13167739/71755855-8a85d500-2e41-11ea-9b34-e5de1001d64a.png)

**Comment by bmarty** [comment]
Thanks for reporting, we will check that
