### ISSUE TITLE
Joining rooms from directory via federation isn't working.

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#808]
RiotX tries to join via roomId which doesn't work. Synapse just return "No known servers".

This happens from the PublicRooms list view and from the RoomPreview view.

**Comment by Bubu** [comment]
I tried fixing that as well, one part of the solution might look like this:

```diff
diff --git a/vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt b/vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
index 1e625cff..586b2eb8 100644
--- a/vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
+++ b/vector/src/main/java/im/vector/riotx/features/roomdirectory/PublicRoomsFragment.kt
@@ -126,7 +126,7 @@ class PublicRoomsFragment @Inject constructor(
 
     override fun onPublicRoomJoin(publicRoom: PublicRoom) {
         Timber.v("PublicRoomJoinClicked: $publicRoom")
-        viewModel.handle(RoomDirectoryAction.JoinRoom(publicRoom.roomId))
+        viewModel.handle(RoomDirectoryAction.JoinRoom(publicRoom.canonicalAlias?:publicRoom.roomId))
     }
 
     override fun loadMore() {
```

That works, but I'm unsure if falling back to roomId in case the canonicalAlias is Null is a sensible thing. I'd guess it probably isn't and showing an error message might be more sensible. (I'm also unsure if a room can show up in a directory and the canonicalalias be unset.)

In the RoomPreview View the room alias which we need for the join is apparently not currently available, so that needs slightly more changes. It might also make sense to show it in the UI anyway?

**Comment by bmarty** [comment]
Note that using the roomId as a fallback when canonical alias is missing, will not be worse than the code we have today

**Comment by twouters** [comment]
Shouldn't this be added to the phase 2 project or is that limited to new features?
Not sure if there's a list of blockers but I think this belongs in it :-)

Not being able to join rooms is no fun :(
