### ISSUE TITLE
play-services-oss-licenses is a proproetary library

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#814]
This dependency is as far as I can determine non-free:
`implementation 'com.google.android.gms:play-services-oss-licenses:17.0.0'`

The import path is com.google.android.gms.* which is a pretty good sign, that this part of the proprietary play services,

So at least for the f-droid build this cannot be included.

Ref #428

**Comment by Bubu** [comment]
To clarify: the gradle plugin is open source: https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin

The library for showing the license view isn't though.

**Comment by bmarty** [comment]
Ok, I remove this for F-Droid build
