### ISSUE TITLE
building from tags appends -dev version suffix

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#815]
When trying to build version v0.11.0 I got instead version v0.11.0-dev because of this https://github.com/vector-im/riotX-android/blob/develop/vector/build.gradle#L65

**Comment by bmarty** [comment]
I have to admit, it suits our needs to build a version for the PlayStore, but not other cases.
What do you propose?

**Comment by Bubu** [comment]
I don't really know. Quick googling shows that `git describe --exact-match --tags` can tell you if you have checked out a git tag or not. Maybe that can be used.
CC @krombel
