### ISSUE TITLE
[crypto] add /discardsession session command

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#819]
Add this command to create a new encryption session in a room in order to mitigate unable do decrypt issues.

-> see web https://github.com/matrix-org/matrix-react-sdk/commit/d9fb88246a32e75047ff6ec512c9ecab11b08b4c

Forces the current outbound group session in an encrypted room to be discarded

https://github.com/matrix-org/matrix-doc/pull/1719

**Comment by bmarty** [comment]
Done in 9b320ed3c78de5590e96785c8100325eddff962f
