### ISSUE TITLE
version code scheme broken

### ISSUE THREAD

**Issue by Bubu** [vector-im/riotX-android#827]
A non-universal build of an earlier version should never have a higher VC than a universal build for a newer version.

When trying to upgrade from riotX-0.12-dev armv8 to riotX-0.13-dev universal I was confronted with a downgrade from 177798783 to 157858035. This should really not be a downgrade.

**Comment by Bubu** [comment]
FTR, this also creates a major headache for f-droid distribution of architecture specific apks because f-droid keeps the last X versions (by versioncode) available in the repo.
In the current case the newest version of the universal build will *always* be considered older then first version of the universal apk.

**Comment by bmarty** [comment]
Universal APKs are not intended to be released on any stores. It is generated by the CI to let people who does not know which APK to install from the CI to use it.

Also the current rule for version code is computed [here](https://github.com/vector-im/riotX-android/blob/8c9c65837d5f14afe7407df7808297ab0c271d3f/vector/build.gradle#L99):
- on develop branch: build from timestamp, to please @krombel who releases the develop version of the app on his F-Droid repository, and that requires an incremented versionCode for each build (https://fdroid.krombel.de/).
- on other branches: build with minor/major/patch values

The version code you're talking about (177798783, 157858035) are clearly based on timestamp, modulo the value used to distinguish the arch ([ref](https://github.com/vector-im/riotX-android/blob/8c9c65837d5f14afe7407df7808297ab0c271d3f/vector/build.gradle#L147))

**Comment by Bubu** [comment]
> Universal APKs are not intended to be released on any stores. It is generated by the CI to let people who does not know which APK to install from the CI to use it.

Doesn't matter, the same applies for armv8 (v0.11.0 - 20001100) > armv7 (v0.12.0 - 10001200). If yu have an armv8 device you can still install armv7 versions. And you should still be able to update from an older version of the app to any newer version.

> The version code you're talking about (177798783, 157858035) are clearly based on timestamp, modulo the value used to distinguish the arch

Also doesn't matter, it's similarly broken for releases. The arch should only determine the least significant bits of the CV.

**Comment by bmarty** [comment]
I do not understand. If you have a armv8 device, you do not want to use the armv7 version of the APK.

Also the arch determine the higher significant bits partially following [this strategy](https://software.intel.com/en-us/android/articles/google-play-supports-cpu-architecture-filtering-for-multiple-apk)

**Comment by Bubu** [comment]
>  you do not want to use the armv7 version of the APK.

I might, if armv8 isn't available (yet) for some reason.

But what's more important, in the current scheme consider it an upgrade to install any earlier armv8 version over the latest armv7 version, which I could have installed on an armv8 device at an earlier point. Which will of course completely break everything because of db migrations, etc.

> Also the arch determines the higher significant bits for partially following this strategy

It seems whoever at intel wrote that had no idea what they are doing. This advice is wrong and harmful. Please look at how any other app on the play store assigns their version codes per architecture:

https://apkpure.com/facebook/com.facebook.katana/variant/252.0.0.22.355-APK
https://apkpure.com/whatsapp-messenger/com.whatsapp/variant/2.19.330-APK
https://apkpure.com/telegram/org.telegram.messenger/variant/5.12.1-APK

**Comment by bmarty** [comment]
Ok, I get all the points.

So the proposal is to compute version code like this:
- move the arch bits to the less significant bits
- add 40_000_000 for compatibility reason with the previous way we computed VC

So for version say "1.2.3" of the application we will get for the version code:
- 40_102_030 for universal APK
- 40_102_031 for armeabi-v7a APK
- 40_102_032 for arm64-v8a APK
- 40_102_033 for x86 APK
- 40_102_034 for x86_64 APK

For version code computed from timestamp, I think it can be the same, but we should reduce the timestamp by subtracting a close date (say timestamp for January first 2020), and divide it by a greater value than 10 (say 100, so +1 every 100 seconds), and add 200_000_000 for compatibility reason.

So for a version generated **today** (January 10th 2020) we will get:
Current timestamp: 1_578_664_924
Timestamp of January first 2020: 1_577_836_800
Diff: 828_124
/100: 8_281
So:
- 200_082_810 for universal APK
- 200_082_811 for armeabi-v7a APK
- 200_082_812 for arm64-v8a APK
- 200_082_813 for x86 APK
- 200_082_814 for x86_64 APK

For an APK generated in **January 1st 2100** we will get:
Timestamp: 4_102_444_800
Timestamp of January first 2020: 1_577_836_800
Diff: 2_524_608_000
/100: 25_246_080
So:
- 452_460_800 for universal APK
- 452_460_801 for armeabi-v7a APK
- 452_460_802 for arm64-v8a APK
- 452_460_803 for x86 APK
- 452_460_804 for x86_64 APK

Please let me know if it suits your needs and also if you see a mistake in my computation

NB: Max value for VersionCode is 2_100_000_000

**Comment by Bubu** [comment]
I think you calculations are wrong for the last timestamp example:

Shouldn't it be 200_000_000 + 25_246_080 = 225_246_080 ?

Apart from that, all what you wrote makes sense and should work for all distribution channels. :tada:

**Comment by bmarty** [comment]
I read it twice again, and it seems correct to me. The last digit is for the arch. So we shift the timestamp 1 digit to the left.

**Comment by Bubu** [comment]
I don't know :woman_shrugging: . But either way doesn't make a difference to functionality here.
