### ISSUE TITLE
Enable e2e by default when creating DM

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#837]
With possibility to opt-out.

Screen to update (create DM screen):

<img width="366" alt="image" src="https://user-images.githubusercontent.com/3940906/72277361-1235c580-3632-11ea-82f4-785d6cccf902.png">

In this screen we should have somewhere a check box, checked by default, to enable encryption for the room the user is creating.

Also we should consider to update the create room screen, to add a check box, not checked by default, for the same purpose:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/3940906/72277533-62ad2300-3632-11ea-87a2-ace1a338e282.png">

@nadonomy could you propose some UX, especially for the create DM screen. It's more straightforward on the create room screen, but feel free to propose something too

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2911)

**Comment by bmarty** [comment]
The DM part is handled by #907
