### ISSUE TITLE
Joins, parts and other non-chat items should not indicate the room has new messages in the room list

### ISSUE THREAD

**Issue by Standard8** [vector-im/riotX-android#864]
When I'm viewing the room list in dark mode, there's a indicator bar on the side which generally indicates new messages.

However, it also indicates when there's only joins/parts or other admin type information.

As a user, I don't want to be going through the rooms thinking there's new messages just to find out that someone has joined or has changed their profile picture.

**Comment by EmmanuelMess** [comment]
Dupe of #864?

**Comment by Standard8** [comment]
> Dupe of #864?

Wrong number? That's this issue.

**Comment by Standard8** [comment]
Sorry, didn't see the update due to the edit. Yes, looks like this is a duplicate of #588

**Comment by Standard8** [comment]
Duplicate of #588
