### ISSUE TITLE
Improve the way RiotX checks network connectivity

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#873]
As discussed [here](https://matrix.to/#/!gGkYcJLTzcNrfERksd:matrix.org/$TcaZN3aarAJYxgsGcz3DA4cyU9ysfo4EujIBNSEZrBo?via=matrix.org&via=privacytools.io&via=feneas.org) and in #561 , RiotX should avoid using a third party URL to check for homeserver reachability.

Also the wording could be change from "There is no network connection right now" to "RiotX cannot get or send new messages", and the banner could be clickable to open a diagnostic screen, the same way we trouble shoot notifications issues.

The network trouble shoot should check:
- if airplane mode is on (quick fix: open device network settings)
- if wifi is on (quick fix: open device network settings)
- if mobile network is on (quick fix: open device network settings)
- if the homeserver is reachable and alive. If NO and Wifi is on, we could explain that maybe the wifi router has no internet access

The lib we use ([merlin](https://github.com/novoda/merlin) and `MerlinsBeard`) can help to perform some of the checks

**Comment by bmarty** [comment]
FTR Merlin uses https://connectivitycheck.android.com/generate_204 to check internet access. Ideally, the homeserver should provide the same type of endpoint.

**Comment by krombel** [comment]
matrix-js-sdk (and therefore riot-web) uses the `/versions` endpoint to check for connectivity ([Reference](https://github.com/matrix-org/matrix-js-sdk/blob/22e6cfaebb0a549f2617b2a89de1f67796463f9a/src/sync.js#L1393-L1394))
It is more or less a static content so can be used for such purposes ([Spec](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-versions)).

**Comment by bmarty** [comment]
Fixed in #945 (no troubleshoot screen for the moment)
