### ISSUE TITLE
Add support for /rainbow command

### ISSUE THREAD

**Issue by bmarty** [vector-im/riotX-android#879]

**Comment by rubo77** [comment]
What does the command do? Is this documented somewhere?

**Comment by Atrate** [comment]
@rubo77 It makes the text rainbow-colored, try it out on Riot desktop/web

**Comment by rubo77** [comment]
I created a readme for all commands, I found in https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/SlashCommands.js#L863: 

https://gist.github.com/rubo77/81d776f0ebd8175b7d62f051a62e46ef
