### ISSUE TITLE
wrong sequience and big timeout after network is up

### ISSUE THREAD

**Issue by progserega** [vector-im/riotX-android#882]
"no network" is not gone, when network is up:
Steps to reproduce:

1. air-mode is on, wifi - is off
2. open RiotX, send "test1" text in room
3. switch off screen for 3-15 minutes
4. switch on screen, set wifi to "on" state
5. On PC - I get message from RiotX in this room (for other account)
6. type "test2" on PC and send it to this room
7. open RiotX and see splash "no network", but wifi is on!
8. wait ~5 minutes... - then RiotX play sound and show "new message"

This is ~5 minutes is bad.

If on step 8 I send text from RiotX - I see it on PC (but RiotX show "no network splash"), but if I send text from PC to RiotX - text not received by RiotX. After ~5 minutes - this text received by RiotX and splash is gone, but sequence of messages in RiotX - is wrong:

![Screenshot_2020-01-21-22-08-17](https://user-images.githubusercontent.com/1297163/72804394-fe2a3d80-3c9b-11ea-80bb-9befa099342f.png)
![Screenshot_2020-01-21-22-08-54](https://user-images.githubusercontent.com/1297163/72804396-fec2d400-3c9b-11ea-88cc-fd3174c2def0.png)
![web-riot](https://user-images.githubusercontent.com/1297163/72804398-fec2d400-3c9b-11ea-9ed2-d67bbdf696a7.png)

**Comment by bmarty** [comment]
Fixed in #945
