### ISSUE TITLE
Can we hide the algo used when turning on encryption

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#897]
From riot-web created by [AmandineLP](https://github.com/AmandineLP): vector-im/riot-web#8829  

at least on /app as 'Amandine turned on end-to-end encryption (algorithm m.megolm.v1.aes-sha2)' is ugly as hell

**Comment by jryans** [comment]
While chatting more with @ara4n, he would like to have some kind of handling of unknown algorithms at the same time as the propose hiding here. I think he came up with a decent approach:

* When the algorithm is the one we expect (`m.megolm.v1.aes-sha2`), hide the algorithm as in this existing PR: %(senderName)s turned on end-to-end encryption.
* For anything else, show the algorithm as unrecognised: %(senderName)s turned on end-to-end encryption (unrecognised algorithm %(algorithm)s).

**Comment by bmarty** [comment]
@jryans I think it could even warn a bit more if `m.megolm.v1.aes-sha2` is already the current algo in a e2e room, like, say: "%(senderName)s is trying to change end-to-end encryption algorithm of the room to %(algorithm)s, which is forbidden". Not sure that it can happen (the sent event should probably be rejected by the homeserver?)
