### ISSUE TITLE
[feature request]: extreme mute

### ISSUE THREAD

**Issue by Rik44444** [vector-im/riotX-android#900]
i have a feature request:
a normal mute function, whereby you do not receive notifications of the group or chat
but secondly (this will be really a big plus for RiotX if it is able to implement it! No other messenging app has it: 
an 'extreme mute' function, whereby you 1) do not receive notifications of the group or chat (as in normal mute), but also as an extra for the extreme mute **2) the group or chat also does not end up on the top of your list of messages when something is posted in that group or chat, but just stays either completely on the bottom or is ranked in your message list based on YOUR last post.** Use case: i have several groups that i cannot leave (eg some work groups) but where my input is not needed on a daily or even weekly basis. I'd like to be able to check this group every once in a while, when i feel like it, instead of being prompted every time that this group exists.

**Comment by bpcurse** [comment]
Interesting, but isn't your use case already covered by setting these rooms to "low priority", so they are grouped separately on the bottom of the "rooms" view?

**Comment by Rik44444** [comment]
completely right, sorry i did not know about this yet! thanks!
