### ISSUE TITLE
Negotiate E2E by default for DMs

### ISSUE THREAD

**Issue by manuroe** [vector-im/riotX-android#907]
From riot-web created by [jryans](https://github.com/jryans): vector-im/riot-web#12005  

When the cross-signing labs flag is on, we want to create DMs as E2E by default. There are no UX changes or toggles in the create DM flow for this. Since not all users support E2E yet (bots, bridges, people with only non-E2E clients), we need to be a bit careful.

When creating the DM room, check if the other user has shared device keys. If yes, then create an encrypted room, otherwise fallback to unencrypted.

**Comment by bmarty** [comment]
Done in #916
