### ISSUE TITLE
Video calling broken in Riot IM

### ISSUE THREAD

**Issue by rajil** [vector-im/riotX-android#915]
Hello,

Video calling on the Riot IM is broken and causes the app to crash on hangup. This has been report multiple times ([#3370](https://github.com/vector-im/riot-android/issues/3370), [ #3311](https://github.com/vector-im/riot-android/issues/3311), [#3266](https://github.com/vector-im/riot-android/issues/3266), [#496](https://github.com/matrix-org/matrix-android-sdk/issues/496)).

Can we have somebody look at that since it is supposed to be stable code and RiotX does not support video yet.

**Comment by bmarty** [comment]
Yes, I'm having a look on it
