### ISSUE TITLE
Correct interpretation of matrix internal links

### ISSUE THREAD

**Issue by bpcurse** [vector-im/riotX-android#917]
If you receive a room name in a message e.g. #room:my.matrixserver.tld, the "#room:" part is not included in the link and RiotX tries to open the rest in a browser.

It should enter/open the room instead. The same happens with communities and user IDs.
Riot as Web/Desktop Client handles this correctly.

RiotX 0.13.0 (gplay)

**Comment by bmarty** [comment]
(Linkification of matrix item has been disabled after work on pills)
It will be restored

**Comment by bpcurse** [comment]
Closing in favor of #972

**Comment by bmarty** [comment]
Oh yes, thanks @bpcurse
