### ISSUE TITLE
Warn if link text doesn't match link target

### ISSUE THREAD

**Issue by tilpner** [vector-im/riotX-android#922]
Currently (version 0.13.0-dev (FDroid)), there is no indication when a link doesn't match its target.

The message `[https://foo.bar](https://quuux.bar)` displays like
![image](https://user-images.githubusercontent.com/4322055/73479297-a4a6ca80-438f-11ea-9ff1-148312f82cf3.png)

But when clicked, it opens the users browser to load `https://quuux.bar`.
While sometimes benign, there are many malicious uses of this behaviour, such as tracking link access via a URL redirection service, tricking people into opening shocking media at a workplace, or phishing.

Even if the user is aware of this behaviour, it's non-trivial to guard against this. With the web version of Riot, the real destination is displayed when the user hovers over the link, but not so with RiotX. Long-clicking the message or link also doesn't reveal the real destination.

Such surprises are unwelcome and should be warned about, either with an icon next to the link, or a confirmation dialog after clicking it (and before sending the "open" intent).

This behaviour should trigger whenever both the link text and link target are valid URLs that will result in an intent being sent, and the values are not identical.

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/3137)

**Comment by tilpner** [comment]
Thank you, @onurays! <3
