### ISSUE TITLE
Disappeared in the playstore

### ISSUE THREAD

**Issue by Wandelstock** [vector-im/riotX-android#932]
With the update to version 14, the app disappeared from the playstore on my Chomebook.

Model and type: Acer Chromebook 11
(11" no-touchscreen)

**Comment by bmarty** [comment]
Is it still the case with v0.14.3? I do not see any reason for this to occurs from our update

**Comment by Wandelstock** [comment]
No update for Chromebook anymore, maybe you added a permission that needs a touchscreen?

**Comment by Wandelstock** [comment]
![Screenshot 2020-02-06 at 12 16 02](https://user-images.githubusercontent.com/58773587/73932541-dad9d200-48da-11ea-8409-e8973d26cd94.png)

Red text: This app doesnt work anymore on this device, please contact the Maker <g>
