### ISSUE TITLE
Emoji verification: Options not fully visible

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#937]
When you do Emoji verification, you at first just see the „They don’t match“ – you have to swipe that screen up to see the second option „They do match“. Would be nice if that popover could be fully shown. ;)

Sadly made no screen shot back then…

**Comment by anoadragon453** [comment]
Also ran into this confusing problem. Here's a screenshot: 

![](https://i.imgur.com/TEiywEw.png)

**Comment by fbruetting** [comment]
At a friend of mine, even both options were hidden below the lower screen border.
