### ISSUE TITLE
Hide removed (redacted) messages 

### ISSUE THREAD

**Issue by nr458h** [vector-im/riotX-android#951]
Hi all,

I would like to propose an idea. In my communication I do have some workflows (with others and with myself) where I often remove messages.
Those rooms are clutterd with removed messages-bars. So I want to ask for a setting, where I can hide a message completly when I remove it.
(I do understand, that this not removes the message from other servers ...)

So thanks anyway for the great app.

**Comment by fbruetting** [comment]
Swiping over that placeholder might be a good solution (preferably in the other direction than replying).

**Comment by nr458h** [comment]
i think there are in general two options:
1. make it a general option to hide removed messages (than it belongs to the settings) or
2. make it an option per message, than it needs to be an interaction with the message

As I don't the a personal use in the placeholder (as I do understand that there is somewhere my message) I would prefer the general option switch (maybe in the advanced area)

**Comment by fbruetting** [comment]
Your first option is implemented in Riot-Web, so there’s a good chance that it might come to RiotX, too.

**Comment by vsatmydynipnet** [comment]
+1 for this one. i have lot of rooms like a notepad, where things are posted and deleted again. now after moving to riotx i see masses of empty boxes.

**Comment by nr458h** [comment]
I updated my app yesterday and so the new option to hide the app. Many thanks!
