### ISSUE TITLE
Duplicate device in list of verified sessions.

### ISSUE THREAD

**Issue by lassepe** [vector-im/riotX-android#954]
After verifying another users device with `v0.14.2` riotx, the verified device is now shown multiple times in the list of sessions with this user. (accessed via: "click on top bar in private chat with this user"  -> 2 people -> <name of other user> -> Security: learn more).

Both verified devices have the same device ID and are shown as "Mobile device". I know that this user did not verify his devices among  each other (so there should not be any cross signing going on).
Interestingly, the other user also sees the same bug: e.g. two mobile devices listed as verified sessions with the same device id. However, I ran verification between riotweb and the riotx session verified by this user. Thus, as per cross signing, he should see my desktop session listed with the verified sessions --- not a second mobile device.

Note: this issue persists after an update to `v0.14.3`

**Comment by lassepe** [comment]
Addendum: I just realized that at the time I ran verification between my desktop client and my mobile device, I was using legacy verification (electron client using riot web 1.5.8). Thus, I guess no cross-signing took place (?). Still, symptomatically the problem persists, though potentially unrelated to cross-signing.

**Comment by fbruetting** [comment]
Also saw this on my friends’ phone after I initiated the cross signing with her.

But I just now recognized that I’m pretty sure that I haven’t activated cross-signing in her settings before doing the cross-signing (freshly installed RiotX). Can that be true and work even with deactivated cross-signing (or is that activated by default)…? 🤨

**Comment by fbruetting** [comment]
= #1329 ?

**Comment by lassepe** [comment]
I guess so. Feel free to close this to keep the repo tidy.
