### ISSUE TITLE
CrossSigning / Update Shield Logic for DM

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riotX-android#963]
#see https://github.com/vector-im/riot-web/issues/12214

There are some cases where this doesn't happen today, e.g. if you have not verified one of your own devices, all rooms would go red (even large public rooms where you have no intention verifying users).

To make the experience more straightforward, we decided after chatting with @dbkr and @nadonomy to add the additional check that green / red states are only shown if you have verified at least one user in the room. If you haven't, the room is black.

Summary doc on shields:  https://docs.google.com/document/d/1RFUN0YRrOs8QZwiblaUbs4wWR0BjA0hBJ27rKJ57Zvk/edit

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2975)

**Comment by BillCarsonFr** [comment]
Users/DMs
None: e2e off in the room
Black: Encryption is enabled (I don’t care about their devices)
Red: I’ve verified them and an unverified device exists or they were previously verified and their cross-signing identity has changed
Green: I’ve verified them and all of their devices are verified

Rooms
None: e2e off in the room
Black: Encryption is enabled AND no users in the room are verified by current user
Red: A red user exists in the room AND (at least one user in room verified by current user OR no one else in the room)
Green: All users are green AND (at least one user in room verified by current user OR no one else in the room)
The state of all users, including yourself, is considered when decorating a room)
The somewhat complex parenthetical bits above are to avoid a case where you have an unverified device (since “a red user exists” includes yourself) and would have caused black rooms to go red if we didn’t add a check for other verified users.

Messages
No badge is shown by default
Warning badge if sent by a user you have verified with an untrusted device
Warning badge if unencrypted in E2E room
