### ISSUE TITLE
Deletion of messages should show a confirmation

### ISSUE THREAD

**Issue by fbruetting** [vector-im/riotX-android#967]
v0.14.3

I just deleted a message, because I haven’t correctly hit the “copy” field. Would be really nice if accidentially destructive actions could be prevented by some confirmation popup etc!

**Comment by bmarty** [comment]
Yes, we will do that, thanks for the suggestion

**Comment by iav** [comment]
I propose not to ask for confirmation, but propose "undo" action for about 10 seconds.

**Comment by bmarty** [comment]
> I propose not to ask for confirmation, but propose "undo" action for about 10 seconds.

That's a good idea, but we will add a prompt to ask eventually for a reason. We keep the confirmation dialog for the moment.

See #977
