### ISSUE TITLE
All messages send notifications even in "mentions only" rooms

### ISSUE THREAD

**Issue by tulir** [vector-im/riotX-android#980]
Probably regressed by #975 since it touched the relevant code. All of the rooms below have "Mentions only" notifications, and none of the messages mentioned me:

![Screenshot_20200210_182026_temp](https://user-images.githubusercontent.com/4224639/74168281-28837100-4c32-11ea-88fa-beab1650a663.jpg)

**Comment by bmarty** [comment]
Thanks @tulir ,
I've done a quick investigation and fixed the pb.
